### ISSUE TITLE
Remove alpha channel

### ISSUE THREAD

**Issue by ajay1685** [kleisauke/net-vips#100]
I am using NetVips and VIPS with openslide to read whole slide RGB images and save as TIFF, how do I specify to only read highest level from pyramid (full resolution) and remove alpha channel. Here is a snippet of my code

```
        Dim im = Image.NewFromFile(svsPath, access:=Enums.Access.Sequential)
        If im.HasAlpha() Then
            Debug.WriteLine("Image has alpha channel")
        End If

        im.SetProgress(True)
        im.SignalConnect(Enums.Signals.Eval, New Image.EvalDelegate(AddressOf EvalHandler))

        Dim Height = im.Height
        Dim nb_bands = im.Bands
        Dim Width = im.Width
        im = im.Copy()
        im.Set(NetVips.GValue.GIntType, "page-height", Height)

        Dim saveOption As New VOption
        saveOption.Add("compression", Enums.ForeignTiffCompression.None)
        im.WriteToFile(tiffPath, saveOption)
        im.Close()
        im.Dispose()

```
I tried this, but I don't think that is the correct syntax for VB.NET

```
im = im[:-1]
```

**Comment by kleisauke** [comment]
C# 8 offers the range expression (`[0..^1]`), which is somewhat similar to Python's slice notation. Unfortunately, this cannot be implemented in NetVips as this operator is not overloadable.

If you want to separate the alpha channel from the image; you'll need to use the [`ExtractBand`](https://libvips.github.io/libvips/API/current/libvips-conversion.html#vips-extract-band) function. For example:
```csharp
// Separate alpha channel
var withoutAlpha = im.ExtractBand(0, im.Bands - 1);
var alpha = im[im.Bands - 1];
```

**Comment by ajay1685** [comment]
Thank you, this is what I was looking for, it worked as intended.
```
im = im.ExtractBand(0, im.Bands - 1)
```

SVS file:

```
 .\vipsheader 'large-40x-01.svs'
large-40x-01.svs: 127487x35229 uchar, 4 bands, srgb, openslideload

```
resulting TIFF file:
```
 .\vipsheader 'large-40x-01.tif'
large-40x-01.tif: 127487x35229 uchar, 3 bands, srgb, tiffload
```
