### ISSUE TITLE
Error loading image from stream

### ISSUE THREAD

**Issue by lfroe** [kleisauke/net-vips#101]
Hi,
I'm pretty new to netvips/libvips, so let me apologize in advance in case I'm doing something obvious wrong :).
I am trying to load a png-Image from S3 and then process it using
`var img = Image.NewFromStream(stream, access: Enums.Access.Random);` and I keep getting this error:
`pngload_source: IDAT stream too short`.
This only happens with NetVips 1.2.4 and NetVips Native 8.10.1. If I downgrade to 1.2.3/8.9.2 everything works fine.
Any help on this would be greatly appreciated.

**Comment by kleisauke** [comment]
The prebuilt binaries provided by NetVips have switched from libpng to libspng for reading PNG files in v8.10.0, so it could be a issue in libspng or within the implementation of this loader in libvips. Are you able to provide a minimal, standalone code sample that demonstrates this issue?

@jcupitt I tried to emulate a extremely slow read/write operation in [`test_connections.c`](https://github.com/libvips/libvips/blob/master/test/test_connections.c), see commit https://github.com/libvips/libvips/commit/88ad9b390a6f4f36ceb2ac4f1facdabae4ad8ff4. Strangely enough this fails with libspng. Commit https://github.com/kleisauke/libvips/commit/9c7030fd342d84d661eff96b3bea1db59af3955d fixes this for me, but I'm not sure if the EOF detection is correct now.

**Comment by jcupitt** [comment]
You're right, it should loop there. I'll have a look at the other uses of `vips_source_read()`.

I think your EOF detection is correct. Would you like to make a PR?

**Comment by jcupitt** [comment]
Or I can do it, of course.

**Comment by jcupitt** [comment]
I cherry-picked your patch, so don't worry about the PR. Thanks!

**Comment by jcupitt** [comment]
OK, this fix should be in 8.10.3, thanks for the report!

I added loops to heifload and ppmload as well. The others look OK.

**Comment by kleisauke** [comment]
Thanks! It look like there is a `data += result;` and `q += bytes_read;` missing in https://github.com/libvips/libvips/commit/ff450497ff38a330eca0f38ed38324779e461523, am I right? I think `vips_source_read` now overwrites the same buffer for subsequent calls.

**Comment by kleisauke** [comment]
Oh, and the ppm loader should probably also check for `bytes_read < 0` to detect reading errors.

**Comment by jcupitt** [comment]
*groans* going too fast again. 

Thanks!

**Comment by jcupitt** [comment]
Yup, and from reading the giflib sources it seems the read function there should loop as well. Sorry, I should have done this in a branch.

**Comment by kleisauke** [comment]
[NetVips.Native v8.10.5(.1)](https://www.nuget.org/packages/NetVips.Native/8.10.5.1) is now available. The network stream sample was extended with commit https://github.com/kleisauke/net-vips/commit/2b8d25d330373a1dee44d346121671db12181d8b to test this. Let me know if this works for you!

**Comment by kleisauke** [comment]
Hope this helped, please re-open if this problem is still occurring.
