### ISSUE TITLE
Save TIFF Stream

### ISSUE THREAD

**Issue by randyridge** [kleisauke/net-vips#107]
It looks like TiffsaveStream/Target should be supportable?  And I gather from the libvips docs that GIF Stream/Target via Magick doesn't appear to have stream/target support?

**Comment by kleisauke** [comment]
`Tiffsave{Target,Stream}` and `Magicksave{Target,Stream}` are currently unsupported. This requires support for `vips_tiffsave_target` and `vips_magicksave_target` in libvips.

See https://github.com/libvips/libvips/issues/1541 for an overview of the remaining loaders and savers that might be reworked.

**Comment by kleisauke** [comment]
[NetVips v2.2.0](https://www.nuget.org/packages/NetVips/2.2.0) and [NetVips.Native v8.13.0](https://www.nuget.org/packages/NetVips.Native/8.13.0) is now available with `Tiffsave{Target,Stream}` included - see:
https://www.libvips.org/2022/05/28/What's-new-in-8.13.html#tiffsave-and-dzsave-to-target
