### ISSUE TITLE
Pngsave colours

### ISSUE THREAD

**Issue by randyridge** [kleisauke/net-vips#109]
Sharp makes use of what appears to be an old, but supported  colours argument on pngsave....

I've manually added it to Image.Generated.cs and verified that it appears to work.  Was this just a missing argument or was there a reason it's not here?  I don't see it listed in the libbips api docs...

**Comment by kleisauke** [comment]
The `@colours` parameter of `pngsave` save was deprecated with https://github.com/libvips/libvips/commit/4bf27acccbf3e660522feade3ad5aebcb4a61075 in favor of the new `@bitdepth` parameter (released in libvips 8.10). The old `@colours` parameter is now being transformed to `@bitdepth` with:
https://github.com/libvips/libvips/blob/5634377fa02e553692b24e097a23ebd0e6c6a927/libvips/foreign/pngsave.c#L130-L134

**Comment by randyridge** [comment]
Thanks, I'll go double check but I had an issue with bitdepth, I'll try to see if I can track it down this week.

**Comment by kleisauke** [comment]
I forgot to mention that the `@palette` parameter, which is automatically enabled when low bit depth is requested for RGB/RGBA images, requires libvips compiled with support for libimagequant. The Windows `-all` variant released on https://github.com/libvips/libvips/releases and https://github.com/libvips/build-win64-mxe/releases does not include this dependency.

**Comment by randyridge** [comment]
Thanks, I obviously didn't get to checking it 'this week' :D, it looks like the bump to 2.0.0 ended up with about 90 errors, mostly around image.Set and enums, I'll try to battle my way through them and verify png is doing what I expect, I've just absolutely been hammered with Real Life™.

**Comment by kleisauke** [comment]
FWIW, if you were using:
```csharp
image.Pngsave("x.png", bitdepth: 16);
```
Then you might encounter this warning:
```
(process:11191): GLib-GObject-WARNING **: 15:52:12.447: value "16" of type 'gint' is invalid or out of range for property 'bitdepth' of type 'gint'
```

This has been recently fixed in libvips, see commit https://github.com/libvips/libvips/commit/a274a2f7e6e0cdfe9b51eb40ab92d1da0fd2623a. The fix will be available in libvips/NetVips.Native 8.12.

**Comment by kleisauke** [comment]
A release candidate of NetVips.Native v8.12.0 is now available for testing.
https://www.nuget.org/packages/NetVips.Native/8.12.0-rc1

**Comment by kleisauke** [comment]
[NetVips.Native v8.12.1](https://www.nuget.org/packages/NetVips.Native/8.12.1) is now available. I'll close, please feel free to re-open if there's still a problem.
