### ISSUE TITLE
Can't load pdf files

### ISSUE THREAD

**Issue by gjactat** [kleisauke/net-vips#11]
Hello,

I'm giving net-vips a shot to replace Magick.Net. Unfortunately, I'm stuck with PDF file loading.
I tried the following:

```
var image = Image.NewFromFile(fileUrl);
var thumbnail = image.ThumbnailImage(300);
thumbnail.WriteToFile(outputFile);
```

Where "fileUrl" is the full path to a pdf file (I tried a few different ones).
This sample code returns the following exception : 

```
Exception non gérée : NetVips.VipsException: unable to load from file C:\Downloads\VIPS\1501750297.pdf
VipsForeignLoad: "C:\Downloads\VIPS\1501750297.pdf" is not a known file format

   à NetVips.Image.NewFromFile(String vipsFilename, Nullable`1 memory, String access, Nullable`1 fail, VOption kwargs)
   à LibVipsTest.Program.Main(String[] args) dans C:\DATA\SOURCES\CSHARP\LibVipsTest\LibVipsTest\Program.cs:ligne 25
```

Net-vips is referenced via Nuget.
I must be missing something. Could you please give me a hint ?

Windows 10 Pro
Project built with x64 target

**Comment by gjactat** [comment]
I also tried the "PdfLoad" method on the Image class : 

```
var image = Image.Pdfload(fileUrl);
var thumbnail = image.ThumbnailImage(300);
thumbnail.WriteToFile(string.Concat(fileUrl, ".thumb.jpg"));

```

Wich returns the following exception :

```
Exception non gérée : NetVips.VipsException: no such operation pdfload
VipsOperation: class "pdfload" not found

   à NetVips.Operation.NewFromName(String operationName)
   à NetVips.Operation.Call(String operationName, VOption kwargs, Object[] args)
   à NetVips.Image.Pdfload(String filename, Nullable`1 memory, String access, Nullable`1 page, Nullable`1 n, Nullable`1 fail, Nullable`1 dpi, Nullable`1 scale)
   à LibVipsTest.Program.Main(String[] args) dans C:\DATA\SOURCES\CSHARP\LibVipsTest\LibVipsTest\Program.cs:ligne 29
```

Hope this helps

**Comment by kleisauke** [comment]
libvips supports PDF via poppler. Poppler is licenced under the GPL, so it's slightly problematic to distribute binaries with it compiled in. If you need PDF support in NetVips, you need to install libvips yourself and include poppler support. This is easy to do on linux hosts or macOS.

On Windows you'll need to use a globally-installed libvips. Set the `UseGlobalLibvips` property to `true`:
```xml
<PropertyGroup>
  <UseGlobalLibvips>true</UseGlobalLibvips>
</PropertyGroup>
```
And download the `vips-dev-w64-all-x.y.z.zip` libvips binary. You'll need to add the `vips-dev-x.y.z\bin` directory to your `PATH` environment variable. I've written a complete tutorial [here](https://github.com/kleisauke/net-vips/issues/3#issuecomment-386236773).

Note that the libvips binary `vips-dev-w64-all-x.y.z.zip` contains ALL the file format loaders that libvips supports, including some very minor ones, and a complete copy of ImageMagick. It can process many different file types, but it is also rather vulnerable to hacking.

I also distribute the latest pre-compiled libvips Windows binaries [here](https://github.com/kleisauke/build-win64-mxe/releases). The advantage of this distribution is that all dependencies are updated to the latest version (where possible), so it'll reduce the attack surface. Hopefully this distribution will be incorporated in the official libvips binaries (see https://github.com/jcupitt/build-win64/issues/22).

**Comment by gjactat** [comment]
Works like a charm !
Thank your for your quick and detailed answer !
