### ISSUE TITLE
how to call vips_addalpha()

### ISSUE THREAD

**Issue by Martinay** [kleisauke/net-vips#116]
The vips library has the `vips_addalpha ()` function.
https://libvips.github.io/libvips/API/current/libvips-conversion.html#vips-addalpha

Is it possible to use this function with the .Net Binding?

I only found a binding for the method `vips_image_hasalpha ()` and a similar issue for the ruby binding https://github.com/libvips/ruby-vips/issues/168 .

I added for now the workaround mentioned in the ruby binding

```
var maxAlpha = (editImage.Interpretation == Enums.Interpretation.Grey16 || editImage.Interpretation == Enums.Interpretation.Rgb16)
                            ? 65535
                            : 255;
editImage = editImage.BandjoinConst(new [] { maxAlpha });
```

Thank you for your help and this amazing library.

**Comment by kleisauke** [comment]
Hi @Martinay,

You're right, this convenience function was missing. I just added it with commit https://github.com/kleisauke/net-vips/commit/81dbca8a7fc13be5d0bbbe955b648380533f3c7d.

If you want to test this, you can use the nightly version of NetVips. Add the `https://ci.appveyor.com/nuget/net-vips` feed in the `<packageSources>` section of your `NuGet.config`:
```xml
<packageSources>
  <add key="netvips-nightly" value="https://ci.appveyor.com/nuget/net-vips" />
</packageSources>
```

And update NetVips to 2.0.0 (build number 248 - prerelease). This will be part of the v2.0.0 release.

**Comment by Martinay** [comment]
Great :) . Thank you very much for your help

**Comment by kleisauke** [comment]
[NetVips v2.0.0](https://www.nuget.org/packages/NetVips/2.0.0) is now available.
