### ISSUE TITLE
Unable to load 'libvips-42.dll'

### ISSUE THREAD

**Issue by nicetomytyuk** [kleisauke/net-vips#120]
When i'm trying to do a Thumbnail with the following code i get the error that 'libvips-42.dll' could not be find.

But i actually installed from NuGet the NetVips.Native.x86 and i'm running the application at x86...

**Comment by kleisauke** [comment]
Curious, that should work out-of-the-box. I assume you tested this on Windows? Also, do you know which exception was thrown? When there is a 32/64-bit mismatch it usually gives an `BadImageFormatException` (`0x8007000B`), but it might also throw an `DllNotFoundException` (`0x8007007E`). It sounds like you ran into the latter one.

You could try to install the [`NetVips.Native`](https://www.nuget.org/packages/NetVips.Native/) NuGet package, it will automatically choose the appropriate NetVips.Native.* package based on which OS/bitness it's running on. This can be useful for cross-platform deployments.

**Comment by nicetomytyuk** [comment]
Hi, @kleisauke actually the exception was the `0x8007000B`, after some attemps to make it work even after installing NetVips.Native it was still returning the same exception. So to solve it i've installed the `NetVips.Native` then from the x86 folder i've moved the `libvips-42.dll` to the bin folder and than it worked as expected.

**Comment by kleisauke** [comment]
Comment https://github.com/kleisauke/net-vips/issues/136#issuecomment-907620737 might be relevant here too, I'm relabeling this issue as bug.

**Comment by kleisauke** [comment]
[NetVips.Native v8.11.3.1](https://www.nuget.org/packages/NetVips.Native/8.11.3.1) is now available which should fix this. Please feel free to re-open if the original problem persists.
