### ISSUE TITLE
Disposing objects in 2.0.0 version

### ISSUE THREAD

**Issue by AndrePScope** [kleisauke/net-vips#122]
Hi NetVips!

I am migrating the project to the new NetVips version 2.0.0
But I faced with problems of object disposing.

F.e. we have this test code. 
The code should return the Image created from a file but with some modifications.

```c#
public static Image CreateImage(string filename, int maxWidth, int maxHeight, int density)
{
	using var image1 = Image.NewFromFile(filename, access: Enums.Access.Sequential);
	using var image2 = image1.Copy(xres: density / 25.4, yres: density / 25.4);
	var image3 = image2.Resize(0.5);

	return image3;
}
```

This method returned the problem object. 
I get an exception when I try to read this object: 
**System.ObjectDisposedException**: _'Safe handle has been closed.
Object name: 'SafeHandle'.'_

The object is disposed already because the parent object is disposed. 

What I have to change in the CreateImage method which should return the correct object?
Probably the objects created inside the method should be created without **"using"** syntax...
Is it so?

___

**I am using** 
- NetVips 2.0.0
- NetVips.Native 8.10.6

**Comment by AndrePScope** [comment]
Hi!
Maybe I see the reason of the problem. The deal is that Resize does not create a new object but returns the same object (not like a Copy method or Mutate or Composite or Flatten or... ). 

So the next code will work well:
```c#
public static Image CreateImage(string filename, int maxWidth, int maxHeight, int density)
{
	using var image1 = Image.NewFromFile(filename, access: Enums.Access.Sequential);
	var image2 = image1.Copy(xres: density / 25.4, yres: density / 25.4);
	var image3 = image2.Resize(0.5);

	return image3;
}
```

So, if I want to dispose object asap, then I have to know somehow does the method returns a new or a current object.
If the method returns a new object then the previous object can be disposed, if the method returns current, then not.

Is my guess right?

**Comment by kleisauke** [comment]
The disposing usage looks OK. Perhaps the returned image was disposed too early? For example, this would be incorrect:
```diff
@@ -2,7 +2,7 @@ public static Image CreateImage(string filename, int maxWidth, int maxHeight, in
 {
     using var image1 = Image.NewFromFile(filename, access: Enums.Access.Sequential);
     using var image2 = image1.Copy(xres: density / 25.4, yres: density / 25.4);
-    var image3 = image2.Resize(0.5);
+    using var image3 = image2.Resize(0.5);
 
     return image3;
 }
```

For calling that function, you could safely use the `using` statement on that function, e.g.:
```csharp
using var image = CreateImage("lichtenstein.jpg", 200, 200, 1);
image.WriteToFile("thumbnail.jpg");
```
