### ISSUE TITLE
Jpg XL support

### ISSUE THREAD

**Issue by fredprodibi** [kleisauke/net-vips#123]
Hello I saw jcupitt working on jpg XL support in libvips https://github.com/libvips/libvips/pull/2181

This feature is really great and I would like to know if you have any plan to add it into .net vips as well?

Thank you

**Comment by kleisauke** [comment]
It should be automatically supported when libvips is compiled against JPEG-XL. The convenient `Jxlload*` and `JxlSave*` methods will be added to NetVips when libvips 8.11 is released.

For inclusion in the pre-built binaries, it still feels a bit too experimental (for e.g. it's missing metadata support and the standard isn't finalized yet). Also, I'd want to see [wg1/jpeg-xl#220](https://gitlab.com/wg1/jpeg-xl/-/issues/220) happen first as the current lack of useful commit messages is going to make debugging possible regressions much more complex.

**Comment by kleisauke** [comment]
The convenient `Jxlload*` and `Jxlsave*` methods are available in [NetVips v2.0.1](https://www.nuget.org/packages/NetVips/2.0.1). For testing this on Windows, you can use the "all" variant released on the `build-win64-mxe` repository:
https://github.com/libvips/build-win64-mxe/releases/tag/v8.11.0

See also https://github.com/lovell/sharp/issues/2731#issuecomment-847292093 for an exhaustive list of upstream issues that needs to be addressed before it's included in the pre-built libvips binaries.

**Comment by kleisauke** [comment]
Closing in favor of https://github.com/libvips/build-win64-mxe/issues/40.
