### ISSUE TITLE
Saved HEIC files are corrupted on subsequent API use

### ISSUE THREAD

**Issue by george-polevoy** [kleisauke/net-vips#126]
When saving HEIC, only the first file get's written correctly.

Subsequent API calls result in corrupted and good files randomly. By corrupted files I assume those displayed incorrectly by MacOS Preview application.

With the following code, all of the files are created, but only in-process-netwips-q5.heic is always written correctly.
The other files are broken. All or some of them.

``` C#
                using var image = Image.NewFromFile(imageFileName, access: Enums.Access.Sequential);

                foreach (var q in new[] {5, 10, 20, 30, 40, 50, 60})
                {
                    try
                    {
                        image
                            .WriteToFile(
                                $"output/in-process-netvips-q{q}.heic",
                                new VOption
                                {
                                    {"Q", q}
                                }
                            );
                    }
                    catch (Exception e)
                    {
                        Console.Error.WriteLine($"Exception from NetVips: {e}");
                    }
```
My current workaround is:

``` C#
                    using var p = Process.Start(new ProcessStartInfo(
                        "vips",
                        $"copy {imageFileName} output/out-of-process-vips-q{q}.heic[Q={q}]"));
                    p.WaitForExit();
```

**Comment by kleisauke** [comment]
Hi @george-polevoy,

Sequential images can be streamed only once, so the solution is just to open each time you need to scan an image.
```diff
@@ -1,9 +1,8 @@
-using var image = Image.NewFromFile(imageFileName, access: Enums.Access.Sequential);
-
 foreach (var q in new[] {5, 10, 20, 30, 40, 50, 60})
 {
     try
     {
+        using var image = Image.NewFromFile(imageFileName, access: Enums.Access.Sequential);
         image.WriteToFile($"output/in-process-netvips-q{q}.heic", new VOption
         {
             {"Q", q},
```
(each subsequent `NewFromFile` call will "rewind" the image, so performance will be fine)

You can also open the image in random access mode. However, this is at the expense of performance, since the entire image is decoded at the first pixel access and stored in a memory buffer (for small images) or a temporary file (for large ones).

There's a handy chapter in the docs explaining how libvips opens files, which gives some more background.
http://libvips.github.io/libvips/API/current/How-it-opens-files.md.html

**Comment by george-polevoy** [comment]
I've tried, no luck.
Also, if the problem would be in sequential access, only one file (the first one) should be created. In fact, just some of the files are corrupt. Some of the subsequent files get written correctly, and some of the corrupt files can be interpreted by some conversion libraries out there. For example, if I attach a corrupt file to Slack message, it get's displayed correctly.

Anyway, some sort of exception should be thrown instead of successfully writing some sort of corrupt files.

**Comment by kleisauke** [comment]
I could not reproduce this with the above "patched" variant of your sample code using libheif 1.12.0 and x265 3.5. Which version of libheif and x265 was this tested on? AFAIK, libheif prior to version 1.12.0 could indeed produce images that cannot be read on macOS.

If you are using an environment based on Ubuntu/Debian, you might consider using libheif PPA, which includes the most recent versions of the dependencies needed for AVIF/HEIC support. See for e.g. commit https://github.com/jcupitt/docker-builds/commit/fdb4c22e4def01e6131b31d362da7dd7ccc7f331 for a way of doing this.

**Comment by kleisauke** [comment]
I hope this information helped. Please feel free to re-open with more details if further assistance is required.
