### ISSUE TITLE
How to work with BMP in NetVips

### ISSUE THREAD

**Issue by AndrePScope** [kleisauke/net-vips#127]
Hi @kleisauke !

I know that lib-vips does not work with **BMP** directly, but work via **IM** or **GM** only.

So, this code does not work from the box:
```C#
try
{
	using var image = Image.NewFromFile("C:\\Temp\\000001.jpg", access: Enums.Access.Sequential);
	image.WriteToFile("C:\\Temp\\000001.bmp");
}
catch (Exception e)
{
	//unable to write to file C:\Temp\000001.bmp
	//VipsForeignSave: "C:\Temp\000001.bmp" is not a known file format
	Console.WriteLine(e);
}
```

Could you help me, what I have to do in NetVips to process BMP files?

Thank you in advance!!!

**Comment by kleisauke** [comment]
For BMP images, you could use `System.Drawing` and the [`NetVips.Extensions`](https://www.nuget.org/packages/NetVips.Extensions/) NuGet package (for converting a GDI+ bitmap to NetVips and vice versa).

See https://github.com/kleisauke/net-vips/issues/7#issuecomment-496896976 for the reason why ImageMagick is not included in the prebuilt libvips binaries released on NuGet.

**Comment by AndrePScope** [comment]
Hi @kleisauke !

Thank you very much for your feedback!
I did not know about `NetVips.Extensions`. 

This is really what I need! :)
