### ISSUE TITLE
Webp loader will lock the file after dispose

### ISSUE THREAD

**Issue by EYHN** [kleisauke/net-vips#128]
I found a few similar issues: #12, #84
The same problem seems to occur with `webp`

Use the following code to reproduce on windows

``` csharp
using (var sourceVipsImage = Image.NewFromFile(@".\Test WebP.webp"))
{
    sourceVipsImage.WriteToFile("out.png");
}

var a = File.Open(@".\Test WebP.webp", FileMode.Open, FileAccess.Read); // System.IO.IOException
```

**Comment by kleisauke** [comment]
Hello, please see https://github.com/kleisauke/net-vips/issues/6#issuecomment-394379299 and [the corresponding libvips documentation](https://libvips.github.io/libvips/API/current/VipsOperation.html#vips-cache-set-max-files).

```diff
@@ -1,3 +1,5 @@
+Cache.MaxFiles = 0;
+
 using (var sourceVipsImage = Image.NewFromFile(@".\Test WebP.webp"))
 {
     sourceVipsImage.WriteToFile("out.png");
```

**Comment by EYHN** [comment]
cool, thank you for the quick response, this solved my problem perfectly.

**Comment by kleisauke** [comment]
@EYHN I noticed that you distribute the `-all` variant on NuGet which contains GPL-licensed dependencies. Could you please remove all references to NetVips, as well as my name? And if that's not possible, could you set the package to private/unlisted?

fwiw, you can also host your own NuGet feed, or using a local NuGet package feed, which might be more appropriate. See for details: https://docs.microsoft.com/en-us/nuget/hosting-packages/overview

**Comment by EYHN** [comment]
I am very sorry, I have deleted these packages on nuget.

<img width="888" alt="image" src="https://user-images.githubusercontent.com/13579374/120956367-faf6fb00-c785-11eb-9ca7-28d1939d23c4.png">
