### ISSUE TITLE
Application crash at writing to png file

### ISSUE THREAD

**Issue by goarsna** [kleisauke/net-vips#13]
Hi,
If I try to save to a PNG file NetVips crashes and the result file has 0 bytes. There is no exception and no warning showing up.

Sample code:
```
var image = Image.NewFromFile("test.png"); // load whatever file you want
image.Pngsave("result.png"); // 0 bytes result file 
```

The error seems to occur in calling ```VipsOperation.VipsCacheOperationBuild(op);``` in **Operation.cs**, line **265**.

Using vips.exe from Windows PowerShell works like expected:
```
.\vips.exe pngload grayscale.png png.v
.\vips.exe pngsave png.v result.png
```
I could reproduce this error using libvips 8.6.3, 8.6.4, 8.6.5 and 8.5.9.

Do you have any idea what could be causing this strange behavior?

Thank you in advance.

**Comment by kleisauke** [comment]
I couldn't reproduce this with:

```csharp
var logFunc = new LogFunc(Log.PrintLogFunction);
var handlerId = Log.SetLogHandler("VIPS", Enums.LogLevelFlags.All, logFunc);

var image = Image.NewFromFile("images/PNG_transparency_demonstration_1.png");
image.Pngsave("result.png");

Log.RemoveLogHandler("VIPS", handlerId);

Console.ReadLine();
```


I assume that you tested this on Windows? If not, ignore the next lines.

You mentioned that you could reproduce this on various libvips versions. Have you correctly set your `PATH` environment variable? And did you include this property in your `csproj` file:

```xml
<PropertyGroup>
  <UseGlobalLibvips>true</UseGlobalLibvips>
</PropertyGroup>
```

I suspect this could be a DLL load issue. You could try to test `vips.exe` outside the `bin` directory or to use the bundled libvips (just remove `<UseGlobalLibvips>true</UseGlobalLibvips>`).

**Comment by goarsna** [comment]
Thank you very much for your quick help!

Indeed i didn't set the UseGlobalLibvips option. and the error was caused by another library referencing a different libvips version.
One library used NetVips 1.0.2 and copied external libvips DLLs to the output folder. The other one uses NetVips 1.0.4 and the packed DLLs.
