### ISSUE TITLE
Porting some old Emgu code to NetVips

### ISSUE THREAD

**Issue by blasky** [kleisauke/net-vips#130]
Hello. I am in the process of porting some old Emgu.CV code over to NetVips.

I have several individual grayscale channel images that I've already created according to some normalized min and max threshold values, and colorized with a NetVips.Image.Maplut() operation (...first experience with Maplut()...that was fun), and combined into the final image.

The individual channel images I am producing look reasonably correct to me, relative to the old code. (Some further tweaking, sure, but generally correct color and range and etc. compared to the old code artifacts.)

![image](https://user-images.githubusercontent.com/2916904/121737544-dbc1db80-caad-11eb-807f-aa60524c3bd2.png)
![image](https://user-images.githubusercontent.com/2916904/121737631-f6945000-caad-11eb-90cb-8f131d8d1d01.png)
![image](https://user-images.githubusercontent.com/2916904/121737698-0ca21080-caae-11eb-8489-7a7dceccc9e5.png)
![image](https://user-images.githubusercontent.com/2916904/121737754-1fb4e080-caae-11eb-861e-fd4c5ad22db8.png)

The old code would then combine these images with a CvInvoke.Add() operation which, according to the docs, "...Adds one array to another one: dst(I)=src1(I)+src2(I)". So naturally I started with a NetVips "+" operation in my channel loop like:
```
finalImg = finalImg + channelImg;
```
When that wasn't looking right, I switched to a NetVips.Image.Composite() operation so I could try different blending modes. 
```
finalImg = finalImg.Composite(channelImg, BlendMode.Add);  // ...and other blend modes
```
But nothing looks quite like the old CvInvoke.Add(). The image on the left is the old Emgu code. The image on the right is my new NetVips image.

![image](https://user-images.githubusercontent.com/2916904/121739202-1fb5e000-cab0-11eb-9ac2-0a3a0825b3cd.png)

Seems like an add is an add is an add. I feel like I've already done the more significant work. But clearly I'm missing something in my understanding of the old add operation and the new. Any ideas? Thanks so much, as always.

**Comment by kleisauke** [comment]
I think OpenCV's arithmetic addition operation is similar to that of libvips (`vips_add`). I tried this with `Emgu.CV`:
<details>
  <summary>Details</summary>

```csharp
// Image sources: https://github.com/kleisauke/net-vips/issues/130
var images = new[]
{
    "121737544-dbc1db80-caad-11eb-807f-aa60524c3bd2.png",
    "121737631-f6945000-caad-11eb-90cb-8f131d8d1d01.png",
    "121737698-0ca21080-caae-11eb-8489-7a7dceccc9e5.png",
    "121737754-1fb4e080-caae-11eb-861e-fd4c5ad22db8.png",
};

var im1 = CvInvoke.Imread(images[0], ImreadModes.Unchanged);
var im2 = CvInvoke.Imread(images[1], ImreadModes.Unchanged);
var im3 = CvInvoke.Imread(images[2], ImreadModes.Unchanged);
var im4 = CvInvoke.Imread(images[3], ImreadModes.Unchanged);

// OpenCV requires that images have the same dimensions for arithmetic operations
var width = Math.Min(im1.Width, Math.Min(im2.Width, Math.Min(im3.Width, im4.Width)));
var height = Math.Min(im1.Height, Math.Min(im2.Height, Math.Min(im3.Height, im4.Height)));

im1 = new Mat(im1, new Rectangle(0, 0, width, height));
im2 = new Mat(im2, new Rectangle(0, 0, width, height));
im3 = new Mat(im3, new Rectangle(0, 0, width, height));
im4 = new Mat(im4, new Rectangle(0, 0, width, height));

var im5 = new Mat(new Size(width, height), DepthType.Cv8U, 4);
CvInvoke.Add(im1, im2, im5);
var im6 = new Mat(new Size(width, height), DepthType.Cv8U, 4);
CvInvoke.Add(im3, im4, im6);
var final = new Mat(new Size(width, height), DepthType.Cv8U, 4);
CvInvoke.Add(im5, im6, final);
final.Save("opencv.png");
```
</details>

Which produces:
![opencv](https://user-images.githubusercontent.com/12746591/121811428-b4613f00-cc64-11eb-9037-98779091ecd0.png)

The equivalent in NetVips is:

<details>
  <summary>Details</summary>

```csharp
// Image sources: https://github.com/kleisauke/net-vips/issues/130
var images = new[]
{
    "121737544-dbc1db80-caad-11eb-807f-aa60524c3bd2.png",
    "121737631-f6945000-caad-11eb-90cb-8f131d8d1d01.png",
    "121737698-0ca21080-caae-11eb-8489-7a7dceccc9e5.png",
    "121737754-1fb4e080-caae-11eb-861e-fd4c5ad22db8.png",
};

using var im1 = Image.NewFromFile(images[0], access: Enums.Access.Sequential);
using var im2 = Image.NewFromFile(images[1], access: Enums.Access.Sequential);
using var im3 = Image.NewFromFile(images[2], access: Enums.Access.Sequential);
using var im4 = Image.NewFromFile(images[3], access: Enums.Access.Sequential);

// Add the 4 images
using var final = im1 + im2 + im3 + im4;
// Or (ensuring that these images are disposed early):
//using var im5 = im1 + im2;
//using var im6 = im3 + im4;
//using var final = im5 + im6;

final.WriteToFile("vips.png");
```
</details>

Which produces:
![vips](https://user-images.githubusercontent.com/12746591/121811359-7bc16580-cc64-11eb-8bb6-4915297f76b9.png)

**Comment by blasky** [comment]
Thanks. I really appreciate not just the commentary, but the extra effort running the experiment as well. I did something very similar to this after I posted. The good news is that an add truly is just an add in both libraries. And I find that comforting.

So now the question for me is what is different about the input images going into the add operation. It's either that my port of the thresholding and normalizing of the grayscale range is off or the look up table colorizing is off. I will do a side by side comparison of each step prior to the add to see if I can identify my error.

Thanks.

**Comment by blasky** [comment]
Closing this issue. Thanks. My issue was LUT related. I was following the example Maplut() operation here...
https://github.com/kleisauke/net-vips/blob/master/samples/NetVips.Samples/Samples/Duotone.cs

And this was similar to a libvips example I had seen as well. Both examples built the LUTs as CIELAB indexes then converted to another color  space. But building the LUT this way means that the l, a, and b are transitioning in the LUT. And this was producing small color variations compared to my original Emgu code that was using an RGB LUT.

I am now creating my LUT as an RGB gradient directly. This produces the same gradient as the original. And it's simpler code, too, without the unnecessary CIELAB conversion steps.

![image](https://user-images.githubusercontent.com/2916904/122488008-6b292c00-cf91-11eb-9e13-a5621d84301e.png)
