### ISSUE TITLE
Set is not a member of Image

### ISSUE THREAD

**Issue by ajay1685** [kleisauke/net-vips#132]
My minimum working example in VB.NET

```
Dim im As Image
im = Image.Openslideload(filePath, autocrop:=True, access:=Access.Sequential)
'make a copy to be able to modify image metadata
im = im.Copy()
im.Set(GValue.GIntType, "page-height", im.Height)
im.WriteToFile(tiffPath)
```

This used to work before installing NetVips 2.0.0, I am using `vips-dev-w64-all-8.11.0.zip` binaries for windows

**Comment by kleisauke** [comment]
This would be the correct usage (in C#) to set the page height in NetVips 2.0:
```csharp
var image = Image.Openslideload("CMU-1-Small-Region.svs", access: Enums.Access.Sequential, autocrop: true);
image = image.Mutate(mutable => mutable.Set(GValue.GIntType, "page-height", mutable.Height));
image.WriteToFile("output.tiff");
```
(see also https://libvips.github.io/libvips/2021/03/08/ruby-vips-mutate.html)

**Comment by ajay1685** [comment]
Thank you! I just discovered that some of the APIs in LibVips were removed from `Image` and now available only under `MutableImage`.
Here is my VB.NET sample for mutable image
```ruby
im = im.Mutate(Sub(mutable)
                   mutable.[Set](GValue.GIntType, "page-height", im.Height)
               End Sub)
```
