### ISSUE TITLE
DZSave massive increase in memory usage in netvips.native.win-x64  8.11 vs 8.8

### ISSUE THREAD

**Issue by paulghodgson** [kleisauke/net-vips#135]
When using different versions I am seeing massive memory differences when using DZSave against an image made of multiple tiles.
In this case ~1000 4 band pngs at 2117 x 2048
netvips.native.win-x64 8.11 uses about 7gb of memory where as 8.8 uses less than 2gb.  
It's worth noting that 8.11 also seems to be about 25% faster so I suspect some optimisation has occurred.

```
  NetVips.NetVips.Concurrency = 2;
  Environment.SetEnvironmentVariable("VIPS_DISC_THRESHOLD", "10m");
  Cache.Max = 0;

  var tiles = new List<Image>();

  foreach(var path in vipsImageRepo.imageFilePaths)
  {
      var page = Image.NewFromFile(path, access: Enums.Access.Random, memory: false);
      tiles.Add(page);
  }

  var result = Image.Arrayjoin(tiles.ToArray(), shim: 0, vspacing: 0, across: 1, valign: Enums.Align.Low );
  result.Dzsave(outputPath, tileSize: 800, depth: Enums.ForeignDzDepth.One, suffix: ".jpg[Q=95]", container: Enums.ForeignDzContainer.Fs);
```

**Comment by kleisauke** [comment]
Hi @paulghodgson,

There were a lot of changes between libvips 8.8 and 8.11, could you reproduce this increased memory usage with libvips 8.10? In libvips 8.11 the [threading system was revamped](https://libvips.github.io/libvips/2021/06/04/What's-new-in-8.11.html#thread-recycling), which might explain why it is 25%(!) faster in your tests. Although, an ~5 GB memory increase certainly looks odd.

I tried this test program:
```csharp
namespace ConsoleApp
{
    using System;
    using NetVips;

    class Program
    {
        static void Main(string[] args)
        {
            NetVips.Concurrency = 2;
            Cache.Max = 0;

            var images = new Image[1500];
            for (var i = 0; i < 1500; i++)
            {
                // Image source: https://upload.wikimedia.org/wikipedia/commons/4/47/PNG_transparency_demonstration_1.png (800 x 600 pixels)
                images[i] = Image.NewFromFile("PNG_transparency_demonstration_1.png", access: Enums.Access.Sequential);
            }

            var image = Image.Arrayjoin(images, across: 1);
            image.Dzsave("huge", tileSize: 800, depth: Enums.ForeignDzDepth.One, suffix: ".jpg[Q=95]");
            Console.ReadKey();
        }
    }
}
```

On my Windows PC, this seems to consume 2.6 GB of memory at its peak. Opening the image in [random access mode](https://libvips.github.io/libvips/API/current/How-it-opens-files.md.html#random-access-via-load-library) (`access: Enums.Access.Random`) seems to consume 5.2 GB of memory at its peak. So, it might be worth opening the image in sequential mode instead (if possible):
```diff	
@@ -6,7 +6,7 @@ var tiles = new List<Image>();
 
 foreach (var path in vipsImageRepo.imageFilePaths)
 {
-    var page = Image.NewFromFile(path, access: Enums.Access.Random, memory: false);
+    var page = Image.NewFromFile(path, access: Enums.Access.Sequential);
     tiles.Add(page);
 }
 
```

@jcupitt Do you think this could be caused by the thread recycling feature of libvips 8.11? I remembered that I had some issues with `dzsave` in https://github.com/libvips/libvips/discussions/2038, but that was related to the number of threads spawned rather than its memory usage.

**Comment by jcupitt** [comment]
Sorry, I can't think of anything that might cause that. 

As Kleis says, there were a lot of changes. I think we'd need to try to narrow down the point where memuse rose. 

I tried at the command-line:

```
$ /usr/bin/time -f %M:%e \
    vips arrayjoin "$(echo *.png)" x.dz[tile-size=800,depth=one,suffix=.jpg[Q=95]] --across 1
18873448:67.26
```

So 18gb (!!) and 67s. But this PC has 32 threads -- if I limit concurrency, it's:

```
$ VIPS_CONCURRENCY=1 /usr/bin/time -f %M:%e \
    vips arrayjoin "$(echo *.png)" x.dz[tile-size=800,depth=one,suffix=.jpg[Q=95]] --across 1
4480736:93.76
```

4.4GB and 93s.

**Comment by jcupitt** [comment]
I tried with 8.8:

```
$ VIPS_CONCURRENCY=1 /usr/bin/time -f %M:%e vips arrayjoin "$(echo *.png)" x.dz[tile-size=800,depth=one,suffix=.jpg[Q=95]] --across 1
3363224:100.76
```

3.3GB and 100s.

Could it be the new PNG loader, perhaps? Maybe the old one shut down and freed memory earlier?

**Comment by paulghodgson** [comment]
I can confirm that I am seeing reduced memory usage with Enum.Access.Sequential and am now trying with concurrency =1 and SequentialUnbuffered to see if there are any extra gains.

I don't know if it helps narrowing down the issue but I am seeing similarly high memory usage in native.linux-x64 including in **v8.80**

**Comment by paulghodgson** [comment]
@kleisauke  I've modified your test program to include setting the VIPS_DISC_THRESHOLD and using larger images as per my use case as follows -

```
namespace vipsspike
{
    using System;
    using NetVips;
    class Program
    {
        static void Main(string[] args)
        {
            NetVips.Concurrency = 2;
            Environment.SetEnvironmentVariable("VIPS_DISC_THRESHOLD", "10m");
            Cache.Max = 0;

            var images = new Image[1500];
            for (var i = 0; i < 1500; i++)
            {
                // Image source: 6.07mb png 2427x2048 32 bit
                images[i] = Image.NewFromFile("00017.png", access: Enums.Access.Random);
            }

            var image = Image.Arrayjoin(images, across: 1);
            image.Dzsave("huge", tileSize: 800, depth: Enums.ForeignDzDepth.One, suffix: ".jpg[Q=95]");

            Console.WriteLine("done");
            Console.ReadKey();
        }

    }
}
```
I ran a few tests but the highlights suggest that there is a sweet spot with v<8.10, Random file access and a threshold of 10m.
Also it seems that the issue was introduce in v8.10 as v9.92 performs as well as v8.8
 
v8.8 RANDOM file access,  threshold 10m - 2.8gb
v8.8 RANDOM file access,  threshold not set - 13.5gb forcibly stopped (as point made)
v8.11 - RANDOM file access,  threshold 10m - 12gb forcibly stopped
v8.10 - RANDOM file access,  threshold 10m - 11gb forcibly stopped 
v8.9 - RANDOM file access,  threshold 10m - slow memory growth
v8.9.2 - RANDOM file access,  threshold 10m - 2.5gb

From a personal point of view, my aim here is to be able to produce deepzoom images from up to 32gb of tiled images usual on machines with limited resources running either Windows or Linux.  There may be a better approach and quite possibly I may be asking too much of VIPS but if you are able to provide any guidance on this it would be very much appreciated.

**Comment by jcupitt** [comment]
8.10 switched to a new PNG load library and introduced a new framework for load and save, so that sounds like the issue. Perhaps we can tune the PNG loader a bit to drop memory use.

`RANDOM` plus a small threshold makes libvips convert your PNGs to VIPS format behind your back. You could convert your PNGs to VIPS yourself and save the time, for example:

```
$ vips crop ../Opera-icon-high-res.png x.v 0 0 2117 2048
$ for i in {1..1000}; do cp x.v $i.v; done
$ VIPS_CONCURRENCY=4 /usr/bin/time -f %M:%e \
    vips arrayjoin "$(echo *.v)" x.dz[tile-size=800,depth=one,suffix=.jpg[Q=95]] --across 1
159384:37.99
$
```

150MB and 37s. VIPS images are uncompressed, so you'll need a lot of disk space, of course.

**Comment by paulghodgson** [comment]
@jcupitt thanks for the approach for my use case it used <100mb RAM although it also used 30GB of disk space :-D  I think that may actually be fine.  There's some additional testing I need to do (Linux, Container, mounted volume on cloud platform and the like) but this looks promising.  Thanks for your help!

If the dzsave performance is fixed I will be sure to test it out.

**Comment by jcupitt** [comment]
I think I found a simple fix --- arrayjoin now signals `::minimise` when process is well past an input image, and `::minimise` on a seq tilecache frees memory, since we no longer make them persistent.

I see:

```
$ VIPS_CONCURRENCY=4 /usr/bin/time -f %M:%e     vips arrayjoin "$(echo y*.png)" x.dz[tile-size=800,depth=one,suffix=.jpg[Q=95]] --across 1
638212:100.84
```

ie. 630 MB of memory, down from 4.6 GB. It works with any input source, not just PNG, and saves a lot of file descriptors too.

**Comment by paulghodgson** [comment]
Thanks John,
Any idea on when this enhancement is likely to be released?  I am happy to test a release candidate if that helps at all.

**Comment by jcupitt** [comment]
It's going to be a feature in 8.12, so perhaps before Christmas? 

You can build the head of git master now if you'd like to try it out.

**Comment by kleisauke** [comment]
If you want, I could provide the pre-compiled libvips Windows binaries build from the master branch (for testing purposes).

**Comment by kleisauke** [comment]
@jcupitt I may have found a race (only when concurrency > 1) when the file descriptors are closed with the sample program mentioned in https://github.com/kleisauke/net-vips/issues/135#issuecomment-880662751, which seems to cause a crash on Windows. See these attached GDB logs for some more details:
[gdb.log](https://github.com/kleisauke/net-vips/files/7172236/gdb.log)
[gdb-concurrency-1.log](https://github.com/kleisauke/net-vips/files/7172237/gdb-concurrency-1.log)
(libvips was build with debug symbols from commit https://github.com/libvips/build-win64-mxe/commit/eb38b78f58ba7be9dd9daff731a0e0947373ff58)

Let me know if you want to track this in a separate issue.

**Comment by jcupitt** [comment]
Oh no! Does linux race too? I'll see if I can make a reproducer in py.

**Comment by kleisauke** [comment]
I'm not sure if this is reproducible on Linux, let me test.

Note that the `ucrtbase!_invalid_parameter_noinfo` backtrace is a security feature of UCRT, similar to https://github.com/lovell/sharp/issues/2494#issuecomment-749498530. Perhaps the `close()` call was done on an already closed file? If that's the case, then it will fail silently under Linux and not raise an exception (AFAIK).

**Comment by kleisauke** [comment]
I couldn't reproduce this crash on Linux. But compiling this program:
```c
#include <assert.h>
#include <fcntl.h>
#include <stdio.h>

int main() {
    int fd = open("foo.txt", O_RDONLY | O_CREAT);

    printf("fd = %d\n", fd);

    assert(fd != -1);

    close(fd);
    close(fd);

    return 0;
}
```
against the debug version of UCRT (i.e. with the `/MTd` compiler option) produces this error:
![fd-close-twice](https://user-images.githubusercontent.com/12746591/133595082-1ee0cd53-d98e-4430-a4ca-4f4012e9bb6c.png)

Which I think is the same crash as the one in the above mentioned NetVips program.

Here's a reproducer in C:
```c
#include <vips/vips.h>

int main(int argc, char **argv) {
    VipsObject *context;
    VipsImage *image;
    VipsImage **images;
    int i;

    if (VIPS_INIT(argv[0]))
        vips_error_exit(NULL);

    if (argc != 3)
        vips_error_exit("usage: %s infile outfile", argv[0]);

    vips_cache_set_max(0);

    const int n_images = 1500;

    context = VIPS_OBJECT(vips_image_new());
    images = (VipsImage **) vips_object_local_array(context, n_images);

    for (i = 0; i < n_images; i++)
        if (!(images[i] = vips_image_new_from_file(
                  argv[1], "access", VIPS_ACCESS_SEQUENTIAL, NULL))) {
            g_object_unref(context);
            vips_error_exit(NULL);
        }

    if (vips_arrayjoin(images, &image, n_images, "across", 1, NULL)) {
        g_object_unref(context);
        vips_error_exit(NULL);
    }

    if (vips_image_write_to_file(image, argv[2], NULL)) {
        g_object_unref(image);
        g_object_unref(context);
        vips_error_exit(NULL);
    }

    g_object_unref(image);
    g_object_unref(context);

    return 0;
}
```

Compile with:
```powershell
PS> cl /Zi /MTd /IC:\vips-dev-8.12\include /IC:\vips-dev-8.12\include\glib-2.0 /IC:\vips-dev-8.12\lib\glib-2.0\include test.c /link /libpath:C:\vips-dev-8.12\lib libvips.lib libglib-2.0.lib libgobject-2.0.lib
```

Or:
```bash
$ gcc -g -Wall test.c `pkg-config vips --cflags --libs`
```

Test on Linux:
```bash
$ curl -LO https://upload.wikimedia.org/wikipedia/commons/4/47/PNG_transparency_demonstration_1.png
# Print only failed close syscalls
$ strace -Z -fe trace=close ./a.out PNG_transparency_demonstration_1.png x.dz[tile-size=800,depth=one,suffix=.jpg[Q=95]] > strace-failed.log 2>&1
```

[strace-failed.log](https://github.com/kleisauke/net-vips/files/7176931/strace-failed.log)

**Comment by jcupitt** [comment]
Oh fantastic detective work. This sounds like a simple thing to fix, I'll have a look.

**Comment by jcupitt** [comment]
I think this fixes it:

```patch
diff --git a/libvips/iofuncs/source.c b/libvips/iofuncs/source.c
index 41746d05..aed00822 100644
--- a/libvips/iofuncs/source.c
+++ b/libvips/iofuncs/source.c
@@ -578,6 +578,10 @@ vips_source_minimise( VipsSource *source )
 
        (void) vips_source_test_features( source );
 
+       /* Sources can be shared between threads, so this can race.
+        */
+       g_mutex_lock( vips__global_lock );
+
        if( connection->filename &&
                connection->descriptor != -1 &&
                connection->tracked_descriptor == connection->descriptor &&
@@ -593,6 +597,8 @@ vips_source_minimise( VipsSource *source )
                connection->descriptor = -1;
        }
 
+       g_mutex_unlock( vips__global_lock );
+
        SANITY( source );
 }
```

I foolishly hadn't considered shared sources :(

**Comment by jcupitt** [comment]
Thinking again, a better solution is to have a lock for minimise. I'll make a PR.

**Comment by kleisauke** [comment]
I remembered that we had some issues with minimise before and that commit https://github.com/libvips/libvips/commit/8752a76e668c5a176aeaa34502fe7212fa76415f resolved that. Do you think a separate lock for minimise could partially revert that commit?

**Comment by jcupitt** [comment]
Oh interesting, I'd forgotten that one. I think that has to stay, since tiled TIFFs can have multiple active readers. We mustn't minimise while a thread is still trying to read something.

**Comment by jcupitt** [comment]
I think this is a better patch, and also fixes the issue:


```patch
diff --git a/libvips/iofuncs/image.c b/libvips/iofuncs/image.c
index 93cec059..c59f28a7 100644
--- a/libvips/iofuncs/image.c
+++ b/libvips/iofuncs/image.c
@@ -387,6 +387,10 @@ int vips__progress = 0;
  */
 char *vips__disc_threshold = NULL;
 
+/* Minimise needs a lock.
+ */
+static GMutex *vips__minimise_lock = NULL;
+
 static guint vips_image_signals[SIG_LAST] = { 0 };
 
 G_DEFINE_TYPE( VipsImage, vips_image, VIPS_TYPE_OBJECT );
@@ -1322,8 +1326,7 @@ vips_image_class_init( VipsImageClass *class )
         *
         * The ::minimise signal is emitted when an image has been asked to
         * minimise memory usage. All non-essential caches are dropped. 
-        * See
-        * vips_image_minimise_all().
+        * See vips_image_minimise_all().
         */
        vips_image_signals[SIG_MINIMISE] = g_signal_new( "minimise",
                G_TYPE_FROM_CLASS( class ),
@@ -1333,6 +1336,7 @@ vips_image_class_init( VipsImageClass *class )
                g_cclosure_marshal_VOID__VOID,
                G_TYPE_NONE, 0 );
 
+       vips__minimise_lock = vips_g_mutex_new();
 }
 
 static void
@@ -1446,8 +1450,15 @@ vips_image_minimise_all_cb( VipsImage *image, void *a, void *b )
 void 
 vips_image_minimise_all( VipsImage *image )
 {
+       /* Minimisation will modify things like sources, so we can't run it
+        * from many threads.
+        */
+       g_mutex_lock( vips__minimise_lock );
+
        (void) vips__link_map( image, TRUE,
                (VipsSListMap2Fn) vips_image_minimise_all_cb, NULL, NULL );
+
+       g_mutex_unlock( vips__minimise_lock );
 }
 
 /**
```

**Comment by kleisauke** [comment]
Thanks John! I can confirm that both patches resolves the crash.

While testing this I also noticed another issue. When removing the `Console.ReadKey()` (i.e. don't wait for user input before closing) from the test program mentioned in https://github.com/kleisauke/net-vips/issues/135#issuecomment-880662751, it seems to deadlock here in GLib:
https://github.com/GNOME/glib/blob/1da68b3f069bf43c2fa60c508740809aef1c604b/glib/gthreadpool.c#L936
(Possibly due to threads on Windows being terminated before the `atexit` registered functions are executed, similar to the issue resolved in commit https://github.com/libvips/libvips/commit/4c263a36e9e728b5ab5cc1f4f3cafe5738a6b6e7)

Somehow the `persistent` removal from `vips_sequential` seemed to cause this, as I didn't saw this issue when I reverted that (see commit https://github.com/libvips/build-win64-mxe/commit/4beeafc50799d3554b3071352198c39bf738aba5). I also didn't saw this behavior when setting the `@wait` param to `FALSE` in the `g_thread_pool_free` call (see commit https://github.com/libvips/build-win64-mxe/commit/ce4e06cf3ee259ced69005cd947c74c4a7b21fa2).

WDYT? I think the preferred way is to not wait for unfinished tasks when the threadpool is freed. Let me know if you want a PR for that (AFAIK, it only affects the master branch, I couldn't reproduce this on 8.11.3).

**Comment by jcupitt** [comment]
That's great!

We probably shouldn't release stuff in `atexit()` and just use it for leak reporting. As Remi said, there are no guarantees about ordering of exit handlers, so it's always going to be dangerous. Users should call `vips_shutdown()` if they want things cleaned up.

Does adding a `vips_shutdown()` call resolve this? That might be an even simpler solution.

**Comment by kleisauke** [comment]
After further testing, I was able to resolve this simply by doing this:
```diff
--- a/Program.cs
+++ b/Program.cs
@@ -16,7 +16,7 @@
                 images[i] = Image.NewFromFile("PNG_transparency_demonstration_1.png", access: Enums.Access.Sequential);
             }
 
-            var image = Image.Arrayjoin(images, across: 1);
+            using var image = Image.Arrayjoin(images, across: 1);
             image.Dzsave("huge", tileSize: 800, depth: Enums.ForeignDzDepth.One, suffix: ".jpg[Q=95]");
 
             Console.WriteLine("Done!");
```

Which ensures that the output image is disposed early. So, it looks like somehow the `atexit` registered functions are executed before the GC cycle kicks in (as also noticed in comment https://github.com/kleisauke/net-vips/issues/114#issuecomment-784997101). 

FWIW, I could also reproduce this in C with doing:
```diff
--- a/test.c
+++ b/test.c
@@ -37,7 +37,6 @@ int main(int argc, char **argv) {
         vips_error_exit(NULL);
     }
 
-    g_object_unref(image);
     g_object_unref(context);
 
     return 0;
```


> We probably shouldn't release stuff in `atexit()` and just use it for leak reporting. As Remi said, there are no guarantees about ordering of exit handlers, so it's always going to be dangerous. Users should call `vips_shutdown()` if they want things cleaned up.

But wouldn't that break API compatibility? If `vips_shutdown()` needs to be called explicitly, a lot of bindings and downstream projects must also be updated. Additionally, in previous versions `vips_shutdown()` would end up being called twice (unless libvips is configured with `ac_cv_func_atexit=no`).

> Does adding a `vips_shutdown()` call resolve this? That might be an even simpler solution.

I can confirm that calling `vips_shutdown()` also resolves that. Though, it's not currently available in NetVips, so the following thing is required.
```diff
--- a/Program.cs
+++ b/Program.cs
@@ -1,10 +1,17 @@
 ﻿namespace ConsoleApp
 {
     using System;
+    using System.Security;
+    using System.Runtime.InteropServices;
     using NetVips;
 
     class Program
     {
+        [SuppressUnmanagedCodeSecurity]
+        [DllImport("libvips-42.dll", CallingConvention = CallingConvention.Cdecl,
+            EntryPoint = "vips_shutdown")]
+        private static extern void VipsShutdown();
+
         static void Main(string[] args)
         {
             Cache.Max = 0;
@@ -20,6 +27,8 @@
             image.Dzsave("huge", tileSize: 800, depth: Enums.ForeignDzDepth.One, suffix: ".jpg[Q=95]");
 
             Console.WriteLine("Done!");
+
+            VipsShutdown();
         }
     }
 }
```

**Comment by jcupitt** [comment]
> But wouldn't that break API compatibility? If vips_shutdown() needs to be called explicitly, a lot of bindings and downstream projects must also be updated. Additionally, in previous versions vips_shutdown() would end up being called twice (unless libvips is configured with ac_cv_func_atexit=no).

I think `vips_shutdown()` is optional though, isn't it? On linux anyway, you can just exit and the OS will clean things up.  `vips_shutdown()` is there for leak checking. Does win need threads to be joined before a thread can terminate?

It's harmless to call `vips_shutdown()` many times.

**Comment by jcupitt** [comment]
> So, it looks like somehow the atexit registered functions are executed before the GC cycle kicks in (as also noticed in comment #114 (comment)).

Ouch! Yes, win process termination is very unpredictable, we had this issue a couple of months ago. 

Every DLL can have its own C runtime, which means you can have many atexit call stacks. When a process ends, main() (or equivalent) returns 0 and the C runtime /for main/ starts cleaning up by calling its atexit stack. But that's only atexit for the main thread! It doesn't know about the C runtimes for any DLLs the process has loaded, so they are not triggered at that point.

Instead, ExitProcess handling starts, and the first thing it does is forcibly kill all running threads (argh), and only much later, when unloading DLLs, will it run atexit handling for any other runtimes.

So atexit() called in a library on windows will execute in a mysterious dark world when most of the process has already gone and few of the usual rules apply. In particular, any assumptions you might have about threading are toast.

**Comment by jcupitt** [comment]
I can't remember, were we talking about this back in June? Anyway, there's was interesting post by Raymond Chen about this.

https://devblogs.microsoft.com/oldnewthing/20070503-00/?p=27003

**Comment by kleisauke** [comment]
> I think `vips_shutdown()` is optional though, isn't it? On linux anyway, you can just exit and the OS will clean things up. `vips_shutdown()` is there for leak checking.

I didn't realize `vips_shutdown()` was optional. But you're right, this is only useful for LSan/valgrind and the OS will clean things up because the program is basically over. Given this, perhaps we should only do the `atexit` thing when `FUZZING_BUILD_MODE_UNSAFE_FOR_PRODUCTION` is defined?

BTW, I noticed that `vips__global_lock` is now also freed (with `vips_g_mutex_free`) on shutdown. Does the `vips__minimise_lock` above also needs to be freed in `vips_shutdown`? If so, we might also need to do the same for `vips_tracked_mutex`, `vips_text_lock`, `vips_cache_lock`, `vips__meta_lock`, `vips__object_all_lock`, ouch.

> Does win need threads to be joined before a thread can terminate?

Not sure, let me check by configuring libvips for Windows with `ac_cv_func_atexit=no`.

> It's harmless to call `vips_shutdown()` many times.

Ah, yes you're right. Sorry for the confusion.

> I can't remember, were we talking about this back in June

Yes, we had a discussion about this before on Gitter (which led to commit https://github.com/libvips/libvips/commit/4c263a36e9e728b5ab5cc1f4f3cafe5738a6b6e7). The blog post from https://www.luke1410.de/blog/2017/02/the-trouble-of-separate-module-atexit-stacks/ is also interesting.

**Comment by jcupitt** [comment]
Ah that's right. I keep forgetting which bit of social media I was talking about what on with whom :-( sorry.

Yes, I wondered about freeing `vips__minimise_lock`. Let's not bother, I'm sure it's harmless to just leave it.

Here's a PR with a possible fix --- only use `atexit()` for leak checking, and users must call `vips_shutdown()` themselves if they want a clean exit (but it's fine to have a dirty exit if you like, or if vips_shutdown() is hard to hook into process termination).

https://github.com/libvips/libvips/pull/2439

What do you think?

**Comment by kleisauke** [comment]
Don't worry, next time I'll track those bugs in GitHub instead. Gitter isn't made for that.

I can confirm that both issues (the crash and deadlock) are resolved with PR https://github.com/libvips/libvips/pull/2439! I had to apply commit https://github.com/kleisauke/libvips/commit/57b8b7fadf10c0f09f7baec7885701839e1a212e (build fix) and https://github.com/kleisauke/libvips/commit/b4f9364ffdbf23cfa7945abc9c2bfc5ab485def4 (`VIPS_LEAK` fix) to make this work.

I forgot to mention that the test program now consumes 500 MB of memory at its peak, which is great since it was previously consumed 2.6 GB.

**Comment by jcupitt** [comment]
Yes, the minimise stuff is a *huge* saving for arrayjoin. We could do the same kind of thing in insert, perhaps.

I noticed something bad with this variant of your test program:

```C
/* compile with:
 *
 * gcc -g -Wall try330.c `pkg-config vips --cflags --libs`
 */

#include <vips/vips.h>
    
int 
main(int argc, char **argv) 
{
    VipsObject *context;
    VipsImage *image;
    VipsImage **images;
    int n_images;
    int i;

    if (VIPS_INIT(argv[0]))
        vips_error_exit(NULL);

    if (argc != 4)
        vips_error_exit("usage: %s infile outfile 4", argv[0]);

    n_images = atoi(argv[3]);
    context = VIPS_OBJECT(vips_image_new());
    images = (VipsImage **) vips_object_local_array(context, n_images);

    for (i = 0; i < n_images; i++)
        if (!(images[i] = vips_image_new_from_file(argv[1], 
                "access", VIPS_ACCESS_SEQUENTIAL, NULL))) {
            g_object_unref(context);
            vips_error_exit(NULL);
        }

    if (vips_arrayjoin(images, &image, n_images, "across", 1, NULL)) {
        g_object_unref(context);
        vips_error_exit(NULL);
    }

    if (vips_image_write_to_file(image, argv[2], NULL)) {
        g_object_unref(image);
        g_object_unref(context);
        vips_error_exit(NULL);
    }

    g_object_unref(image);
    g_object_unref(context);

    return 0;
}
```

I see:

```
$ ./a.out ~/pics/k2.jpg x.tif 1
$ ./a.out ~/pics/k2.jpg x.tif 10
$ ./a.out ~/pics/k2.jpg x.tif 100

(process:806177): VIPS-WARNING **: 18:58:54.572: error in tile 0 x 1920
VipsJpeg: out of order read at line 2048
```

It seems to just be for JPEG sources. The output format doesn't matter.

**Comment by jcupitt** [comment]
I'll merge that PR, with your leak patch.

**Comment by kleisauke** [comment]
Great, thanks John! I noticed that the CI is currently detecting leaks as a result, see for example: https://github.com/libvips/libvips/runs/3640439857#step:17:259

I could resolve this locally with doing:
```diff
--- a/libvips/iofuncs/init.c
+++ b/libvips/iofuncs/init.c
@@ -431,6 +431,7 @@ vips__atexit( void )
 
 		if( !done ) {
 			done = TRUE;
+			vips_cache_drop_all();
 			vips_leak();
 		}
 	}
```

Perhaps we should still call `exit(1)` when it detects any leaks? FWIW, although that is a dangerous thing to do, it is consistent with what LSan does.
https://github.com/llvm/llvm-project/blob/d480f968ad8b56d3ee4a6b6df5532d485b0ad01e/compiler-rt/lib/lsan/lsan_common_linux.cpp#L116-L121

**Comment by kleisauke** [comment]
A release candidate of NetVips.Native v8.12.0 is now available for testing.
https://www.nuget.org/packages/NetVips.Native/8.12.0-rc1

See the release notes for some more details: https://www.libvips.org/2021/11/14/What's-new-in-8.12.html.

**Comment by kleisauke** [comment]
[NetVips.Native v8.12.1](https://www.nuget.org/packages/NetVips.Native/8.12.1) is now available.
