### ISSUE TITLE
Working with multiband hyperspectral images in ENVI BIL format (raw, hdr). Saving bands to 2D image.

### ISSUE THREAD

**Issue by pablo-01** [kleisauke/net-vips#138]
Hi, 

I am beginning to learn more about net-vips and starting to use it more for various projects. 
So far mainley worked with regular 2d images and I find the performance and mamory usage amazing.  

I have recently started to learn about hyperspectral images (HSI) but due to a lack of information having a hard time figuring out how to get started with net-vips. 

I'm fairly new to net-vips and HSI so please go easy on me if get the terminology wrong. 

I have a sample HSI image in ENVI BIL (Band-interleaved-by-line) format (.raw and .hdr - header file). 
I am trying to learn how to do some basic operations on it e.g.: extracting bands to 2d images, joining bands and saving them to 2d images.

My header file gives me information about the file/format:

```
ENVI
samples = 2883
lines = 4094
bands = 306
header offset = 0
file type = ENVI Standard
data type = 4
interleave = bil
wavelength units = nm
binning = {4,4}
wavelength = {"list of wavelengths here"}
```

I did try to use the `Rawload()` and started reading the documentation but I'm stuck.
Should I be looking at `Enums.Interpretation` and `Enumbs.BandFormat`? 

```csharp
  static void Main(string[] args)
        {

            string selectedFile = @"C:\hsi.raw";
            int datatype = 4;    // Floating - point: 32 - bit single - precision
            int samples = 2883;  // width
            int lines = 4094;    // height
            int bands = 306;     // number of bands (channels)


            using (var image = Image.Rawload(selectedFile, samples, lines, bands, access: Enums.Access.Sequential))
            {
                var splited = image.Bandsplit();
                int counter = 0;
                foreach (var im in splited)
                {
                    im.WriteToFile("img" + counter + ".jpg");
                    counter++;
                }
            }

        }

```

```csharp
 static void Main(string[] args)
       {
           string selectedFile = @"C:\hsi.raw";
           int datatype = 4;    // Floating - point: 32 - bit single - precision
           int samples = 2883;  // width
           int lines = 4094;    // height
           int bands = 306;     // bands (channels)

           using (var image = Image.Rawload(selectedFile, samples, lines, bands, access: Enums.Access.Sequential))
           {
               image[0].WriteToFile("test.jpg");
           }
       }
```

![test](https://user-images.githubusercontent.com/35709452/132945139-a1e0eedb-be3f-4e74-9806-da00342a3f8e.jpg)

I have also tried to do this manually with FileStream, calculating positions, using Buffer.BlockCopy and attempting to get an image from a byte array.

I was wondering if someone with more experience in the subject could help me get started/give some examples if possible? 

Many thanks. 

EDIT: 
I have managed to get some results to extract one band manually: using` FileStream`, setting img dimensions and positions of bands then looping while doing `BlockCopy` to` float[]`. 
Eventually converting `float[]` to `byte[]` then using Net-Vips `Image.FromMemory` to save as jpg.

Still trying to figure out if this could be more straightforward with net-vips? (like using the Rawload and then working on bands).

**Comment by kleisauke** [comment]
Hi @PavKmiec,

I think [`Image.Rawload`](https://kleisauke.github.io/net-vips/api/NetVips.Image.html#NetVips_Image_Rawload_) ([`vips_rawload`](https://libvips.github.io/libvips/API/current/VipsForeignSave.html#vips-rawload) in libvips) is indeed the preferred way to open such images. Have you tried opening your image with `format: Enums.BandFormat.Float`? By default, `vips_rawload` opens the image with format set to `Enums.BandFormat.Uchar` (`VIPS_FORMAT_UCHAR` in libvips).

Also, do you have a sample image handy that I can test with?

/cc @jcupitt Since I don't have much experience with hyperspectral images.

**Comment by jcupitt** [comment]
Hello everyone,

Yes, I would use `rawload` to make a huge one-band image, then extract one band from that with `subsample`. Set the horizontal sampling to 1 and the vertical to 512 (for example) and you'll have an image with every 512th line. You can use `crop` before `subsample` to move down the image. Once you have all the bands, you can just `bandjoin` them to make the interleaved image.

In Python, something like:

```python
bil_image = pyvips.Image.rawload(...)
n_bands = 512
bands = [bil_image.crop(0, band, bil_image.width, bil_image.height - band).subsample(1, n_bands)
         for band in range(0, n_bands)]
image = bands[0].bandjoin(bands[1:])
```

It'll be fast and won't need much memory. Don't use `sequential` --- `rawload` doesn't need it, it'll map the file on disc and you'll get fast random access.

What file format do you plan to use for your hyperspectral images?

**Comment by PavKmiec** [comment]
Hi @kleisauke, @jcupitt. Hope you are well. 
 
Thank you for the reply. 
I did try to use `format: Enums.BandFormat.Float`.
The file I have is a stitching and it's over 13GB. 
I don't take the images myself, I only work on the images after they have been taken but I will ask if I can get a much smaller sample next week and will get back to you.

@jcupitt 
I have tried the code both in python and c# but the resulting image ended up being 2883px x 13px.

![image](https://user-images.githubusercontent.com/35709452/133883002-903d86fc-54dd-4b12-bb97-85f65a456998.png)

What I am tying to get is a full band image of 2883px width and 4094px height. 

The file format is a .raw (ENVI BIL) with a .hdr header file that contains information about the sizes, bands data type and so on.
I will try to see if I can get a sample that I could share next week and will get back to you.

Many thanks.

**Comment by kleisauke** [comment]
@PavKmiec Were you able to make any progress with this?

**Comment by PavKmiec** [comment]
Hi, apologies for abandoning this issue. 

I have not made any progress using NetVips and implemented it manually in plain C#, then I moved on to some other tasks and completely forgot about this. 

I made a small crop of the sample image as the whole image is too big.
It has: 
```
306 bands/channels 
width: 460
height: 285
```

The `.raw` file is the image cube file. 
The `.hdr` file is a header file (can be opened in notepad) and contains information about the file format and its content (e.g. bands, format, wavelengths...)

Here is a link to the files:
https://caledonianac-my.sharepoint.com/:f:/g/personal/pkmiec200_caledonian_ac_uk/EvyQoPWEQAFIkVPAGKG5Xe8BylLaGI18CKrB9WksvjabFA?e=3dcrMc


Here is an example of one band/channel from the cube displayed.  
![image](https://user-images.githubusercontent.com/35709452/142481118-7304d15a-192b-4830-92d8-8ecb81961491.png)




I was hoping to be able to read those types of files with NetVips. Be able to extract/read bands/channels correctly, save images and generally do further processing with NetVips. 

As for the data format (ENVI, BIL - Band-interleaved-by-line ) of the file itself, some further information can be found [here](https://www.l3harrisgeospatial.com/docs/enviimagefiles.html).

Many thanks.

**Comment by kleisauke** [comment]
Thanks for the sample image! I had a quick attempt to implement John's idea in C#:
```csharp
static Enums.BandFormat DataTypeToVips(int dataType)
{
    return dataType switch
    {
        // Byte: 8-bit unsigned integer
        1 => Enums.BandFormat.Uchar,
        // Integer: 16-bit signed integer
        2 => Enums.BandFormat.Short,
        // Long: 32-bit signed integer
        3 => Enums.BandFormat.Int,
        // Floating-point: 32-bit single-precision
        4 => Enums.BandFormat.Float,
        // Complex: Real-imaginary pair of single-precision floating-point
        6 => Enums.BandFormat.Complex,
        // Double-precision complex: Real-imaginary pair of double precision floating-point
        9 => Enums.BandFormat.Dpcomplex,
        // Unsigned integer: 16-bit
        12 => Enums.BandFormat.Ushort,
        // Unsigned long integer: 32-bit
        13 => Enums.BandFormat.Uint,
        // Double-precision: 64-bit double-precision floating-point
        // 64-bit long integer (signed)
        // 64-bit unsigned long integer (unsigned)
        _ => Enums.BandFormat.Double, // TODO(kleisauke): Is this correct?
    };
}

static void Main(string[] args)
{
    const string fileName = "stitchedRefl_CROPPED4.raw";

    Enums.BandFormat format = DataTypeToVips(4); // 4 = Floating-point: 32-bit single-precision
    const int width = 460;  // samples
    const int height = 285; // lines
    const int nBands = 306; // number of bands (channels)

    using var bilImage = Image.Rawload(fileName, width, height * nBands, 1, format: format);
    Image[] bands = new Image[nBands];
    for (int band = 0; band < nBands; band++)
    {
        bands[band] = bilImage.Crop(0, band, bilImage.Width, bilImage.Height - band).Subsample(1, nBands);
    }
    using var image = bands[0].Bandjoin(bands[1..nBands]);
    image.WriteToFile("result.jpg");
}
```

But that produces a black image, I probably made a mistake somewhere. Let me investigate this further.

**Comment by jcupitt** [comment]
It looks like the sample image uses 0 - 1 for black to white, so I think adding a `*256` will fix it.

I had a go in python:

```python
#!/usr/bin/python3

import sys
import pyvips

# read a band-interleaved-by-line image

samples = 460
lines = 285
bands = 306

# load as a huge one-band image and chop into bands in the loop below
# "scrgb" uses 0-1 for black to white, which is convenient for us
raw = pyvips.Image.rawload("bil/stitchedRefl_CROPPED4.raw",
                           samples, lines * bands, 1, 
                           format="float")

bands = [raw.crop(0, b, raw.width, raw.height - b).subsample(1, bands)
         for b in range(bands)]

# join the bands up
combined = bands[0].bandjoin(bands[1:])

# the iamge uses 0 - 1 for black to white ... convert to 0 - 255 uint8 for
# convenience
combined = (combined * 256).cast("uchar")

print("writing hyperspectral x.tif ...")
combined.write_to_file("x.tif")

# also save an RGB image as a sample ... these are the 450, 550 and 
# 750nm bands
print("writing RGB x.jpg ...")
combined[28].bandjoin([combined[80], combined[181]]).write_to_file("x.jpg")
```

It makes this:

![x](https://user-images.githubusercontent.com/580843/143469002-cb994fc4-83c7-43dc-aab5-d40f21e3deb5.jpg)

I suppose we'd need to add something about the SPD to fix the blueness.

**Comment by jcupitt** [comment]
Threading really doesn't help this program, interestingly --- I see:

```
$ VIPS_CONCURRENCY=1 /usr/bin/time -f %M:%e ./read-bil.py 
writing hyperspectral x.tif ...
124492:0.93
```

So 120mb of memory and 0.9s with 1 thread, but with 32 threads:

```
$ /usr/bin/time -f %M:%e ./read-bil.py 
writing hyperspectral x.tif ...
292024:3.64
```

300mb of memory and 3.6s. I suppose the subsample is causing a lot of over-computation.

**Comment by kleisauke** [comment]
I hope this information helped. Please feel free to re-open if questions remain.
