### ISSUE TITLE
Unable to copy file libvips-42.dll

### ISSUE THREAD

**Issue by hieudole** [kleisauke/net-vips#140]
Hi @kleisauke 

I got the error "Unable to copy file libvips-42.dll" to "bin\libvips-42.dll" (and some other the native libraries) every time I rebuild my web app project after these libraries are loaded into the memory. It's very inconvenient for me to restart the web server if I cannot build the project. So I changed the setting CopyToOutputDirectory in the .targets file from Always to PreserveNewest then it works fine. Is there any reason to set it to Always, otherwise it should be changed back to PreserveNewest as I've seen in the previous version?

Thank you!

**Comment by kleisauke** [comment]
Hi @hieudole,

The reason that it was changed to `Always` was that these binaries could change in the output directory. For example, when building with `AnyCPU` and the `Prefer 32-bit` option is set to (un-)checked. But you're right, this will end up always copying the binaries to the output directory and there's no option to disable this behavior (unless you manually modify the `.targets` file). It's somewhat unfortunate that there is no `CopyIfDifferent` option, or that this behavior cannot be overridden with:
```xml
<ItemDefinitionGroup>
  <None>
    <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
  </None>
</ItemDefinitionGroup>
```
(as reported in https://stackoverflow.com/q/53946530)

Given this, I reverted to `PreserveNewest` with commit https://github.com/kleisauke/net-vips/commit/087f9f7245b425285d548847d2f6f2c9abef28e3. For the usecase given above, this can be easily resolved by running `msbuild ProjectFile /t:Clean` after switching.

If you want to test this, you can use the nightly version of NetVips.Native. Add the `https://ci.appveyor.com/nuget/net-vips` feed in the `<packageSources>` section of your `NuGet.config`:
```xml
<packageSources>
  <add key="netvips-nightly" value="https://ci.appveyor.com/nuget/net-vips" />
</packageSources>
```

And use NetVips.Native v8.11.3.2 from there. This will be in v8.11.4, due in a couple of days.

**Comment by kleisauke** [comment]
[NetVips.Native v8.11.4](https://www.nuget.org/packages/NetVips.Native/8.11.4) is now available with this fix included. Thanks for reporting this!
