### ISSUE TITLE
Trying to update OME-TIFF metadata, but resulting file is a fraction of the original size

### ISSUE THREAD

**Issue by michael-scott-phoseon** [kleisauke/net-vips#145]
I'm trying to inject additional information into the OME-TIFF metadata of a multi-image ome-tiff file.  This sample tiff file contains 2 regular images, and a set of pyramidal images.  I'm using the following code, but the resulting file is over HALF the size of the other.  any ideas what I'm doing wrong:

The OME-TIFF file I am working with is here:

https://downloads.openmicroscopy.org/images/OME-TIFF/2016-06/sub-resolutions/Fluorescence/LuCa-7color_Scan1.ome.tiff 

And the code I am using is below.  Suggestions of what I am doing wrong?  Ultimately, I want to save this to the same file, but saving the changed file to another one is OK for now.

                        using (var img = NetVips.Image.NewFromFile(slide))
                        {
                            var strImageDescription = img.Get("image-description");

                            XmlSerializer Serializer = new XmlSerializer((typeof(OME)));
                            using (TextReader tr = new StringReader(strImageDescription.ToString()))
                            {
                                metadata = (OME)Serializer.Deserialize(tr);
                            }

                            // Convert to List
                            List<object> lstItems = new List<object>(metadata.Items.ToList());

                            // If Experimenter doesn't exist, add it
                            if (lstItems.Any(i => i.GetType() == typeof(Experimenter)) == false)
                            {
                                lstItems.Add((object)new Experimenter()
                                    {
                                        FirstName = "Fred", LastName = "Flintstone,
                                        Email = "Fred.Flintstone@SlateQuarry.com", Institution = Constants.CompanyName,
                                        UserName = Environment.UserName
                                    });
                            }

                            // Get or create StructuredAnnotations block
                            StructuredAnnotations structuredAnnotations =
                                (StructuredAnnotations)lstItems.FirstOrDefault(i => i.GetType() == typeof(StructuredAnnotations));

                            // We need the Index, so we can delete / replace it later
                            int structuralAnnotationsIdx = lstItems.FindIndex(i => i.GetType() == typeof(StructuredAnnotations));

                            if (structuredAnnotations == null)
                                structuredAnnotations = new StructuredAnnotations();

                            // Get and / or create list of TagAnnotation Annotations
                            List<Annotation> lstAnnotations = new List<Annotation>();
                            if (structuredAnnotations.Items?.Length > 0)
                                lstAnnotations = structuredAnnotations.Items.ToList();

                            if (lstAnnotations.Any(i => i.GetType() == typeof(TagAnnotation)) == false)
                            {
                                lstAnnotations.Add(new TagAnnotation() { ID = "Ann:1", Description = "RosyBrown", Value = "Note 1" });
                                lstAnnotations.Add(new TagAnnotation() { ID = "Ann:2", Description = "RoyalBlue", Value = "Note 2" });
                                lstAnnotations.Add(new TagAnnotation() { ID = "Ann:3", Description = "SpringGreen", Value = "Note 3" });
                            }

                            // Add TimestampAnnotation
                            lstAnnotations.Add(new TimestampAnnotation() 
                                    { Description = $"UserName: {Environment.UserName}", Value = DateTime.Now });

                            // Delete old Structured Annotations
                            if (structuralAnnotationsIdx >= 0)
                                lstItems.RemoveAt(structuralAnnotationsIdx);

                            // Add then add new one back
                            structuredAnnotations.Items = lstAnnotations.ToArray();
                            lstItems.Add((object)structuredAnnotations);
                            
                            // Now update Metadata Items
                            metadata.Items = lstItems.ToArray();

                            // And convert it to XML string
                            string newMetadata = string.Empty;
                            XmlSerializer serializer = new XmlSerializer(typeof(OME));
                            using (StringWriter sw = new StringWriter())
                            {
                                serializer.Serialize(sw, metadata);
                                newMetadata = sw.ToString();
                            }

                            using var mutated = img.Mutate(mutable =>
                            {
                                foreach (var field in img.GetFields())
                                {
                                    if (field == "image-description")
                                        mutable.Set(GValue.GStrType, nameof(newMetadata), newMetadata);
                                }
                            });

                            img.WriteToFile("C:\\abcd.OME.TIFF");
                        }

**Comment by kleisauke** [comment]
Let's track this in https://github.com/libvips/libvips/discussions/2458.
