### ISSUE TITLE
NuGet: NetVips vs NetVips.Native.win-x64

### ISSUE THREAD

**Issue by michael-scott-phoseon** [kleisauke/net-vips#146]
I've added both of these packages to my solution (which is an x64 app).  My question is... do I NEED both?

**Comment by kleisauke** [comment]
The `NetVips.Native.*` NuGet packages contains the native (i.e. unmanaged) libraries for libvips. These packages are not needed if you have libvips installed globally, which is also the reason why it can be installed optionally.

**Comment by kleisauke** [comment]
Ah, I guess I misunderstood that you wanted to target Windows x64 only. In that case, the [NetVips.Native.win-x64](https://www.nuget.org/packages/NetVips.Native.win-x64/) NuGet package is required, unless you have libvips installed globally.

**Comment by michael-scott-phoseon** [comment]
Yes, this is an x64 only app.  So I have the following NuGet packages.  From what I understand now, I need all 3 NetVips packages below, correct?  And no, I don’t have LibVips installed globally – just these 3 packages

I’m looking into LibTiff.NET for stitching for the large images, as I haven’t been able to find examples in either LibVips or NetVips for loading the tiles that make up the large images, or breaking up the large images themselves into tiles in code.

***@***.***

Michael Scott
NOTICE: This communication may contain privileged or other confidential information. If you have received it in error, please advise the sender by reply email and immediately delete the message and any attachments without copying or disclosing the contents. Thank you.

**Comment by kleisauke** [comment]
Sorry, I missed your last question. If you don't have libvips installed globally, and you need the `ToBitmap()` and/or `ToVips()` functions, then yes, you need those 3 packages.

**Comment by kleisauke** [comment]
Hope this helped, please feel free to re-open if questions remain.
