### ISSUE TITLE
Jp2ksaveStream throws an error: Is Jpeg 2000 not fully implemented?

### ISSUE THREAD

**Issue by michael-scott-phoseon** [kleisauke/net-vips#147]
We have images in a pyramidal tiff file that are of 81920 x 98304, so using JpegsaveStream won't work, as it has a 65500 x 65500 size limit. So we are trying to use Jp2ksaveSteam instead.  However, it throws this error:

          NetVips.VipsException: 'no such operation jp2ksave_target VipsOperation: class "jp2ksave_target" not found

Does libvips and / or NetVips not support Jpeg 2000?  We are trying to insert a libvips Image into a WPF Window, so are trying to move the stream into a BitmapSource.  But I am even willing to place it into a Windows Forms Bitmap. Here is the method I'm using:

        private static BitmapImage NetVipsToImageSource(NetVips.Image img)
        {
            using (MemoryStream memory = new MemoryStream())
            {
                img.Jp2ksaveStream(memory);
                //img.JpegsaveStream(memory);
                //img.WriteToStream(memory, ".jpg");
                memory.Position = 0;
                BitmapImage bitmapImage = new BitmapImage();
                bitmapImage.BeginInit();
                bitmapImage.StreamSource = memory;
                bitmapImage.CacheOption = BitmapCacheOption.OnLoad;
                bitmapImage.EndInit();

                return bitmapImage;
            }
        }

Am I doing something wrong?  Is Jpeg 2000 not supported?  Is there another way to do this?

Michael

**Comment by kleisauke** [comment]
See https://github.com/kleisauke/net-vips/issues/142#issuecomment-927118133 for the reason why saving to JPEG 2000 isn't supported by default.

You could use the [NetVips.Extensions](https://www.nuget.org/packages/NetVips.Extensions) NuGet package for converting a GDI+ bitmap to NetVips and vice versa (with the `ToBitmap()` and `ToVips()` functions). It should be faster than encoding/decoding the image to a JPEG (or PNG, TIFF, etc.) memory stream. Note that the conversion to a WPF image isn't supported by this package (see https://github.com/kleisauke/net-vips/issues/81).

**Comment by michael-scott-phoseon** [comment]
Kleis,

I’ve installed NetVips.Extensions, and will look into .ToBitmap.  However, I now have 3 NuGet packages installed:

     NetVips 2.0.1 : .NET bindings for libvips (though I suspect this may be a 32bit version of NetVips.Native.winx64 so may not need it, but am unsure)
     NetVips.Extensions 2.0.0: a set if extension methods and helpers for NetVips (heard a rumor that it contains a .ToBitmap method which may solve one of my other problems)
     NetVips.Native.win-64 8.11.4 (I suspect this replaces the need for NetVips 2.0.1)

Is NetVips 2.0.1 necessary if I also have NetVips.Native.win-64 8.11.4 also installed?  Or the other way around?  And if I have one (or both) of these installed, do I *also* have libvips installed now?  Or is that an entirely separate installation?

Michael

**Comment by kleisauke** [comment]
I'm not sure if there is a workaround for this GDI+ limitation other than avoiding `System.Drawing` or cropping and stitching the image (as John said in https://github.com/libvips/libvips/discussions/2478#discussioncomment-1618041).

**Comment by kleisauke** [comment]
I hope this information helped. Please feel free to re-open if questions remain.
