### ISSUE TITLE
Lock on image file after Dispose() if pyramid=true or tile=true

### ISSUE THREAD

**Issue by LionelArn2** [kleisauke/net-vips#150]
Hello :)

Great work on your library!

I noticed some unexpected behavior of `Tiffload` when reading an image: it seems the file system keeps a lock on an image if libvips reads it using `Tiffload` if this image was written using `Tiffsave` using either `pyramid=true` or `tile=true`:
Here's some code to illustrate the issue:

```            
string filePath = @"Path\To\Image.tiff";
if (File.Exists(filePath))
    File.Delete(filePath);

// Create an new image
var image = NetVips.Image.Black(256, 256);

// Write it
//image.Tiffsave(filePath2);                    // OK
//image.Tiffsave(filePath2, bigtiff: true);     // OK
//image.Tiffsave(filePath2, pageHeight: 64);    // OK
//image.Tiffsave(filePath2, tile: true);        // exception at File.Delete(filePath) below
image.Tiffsave(filePath, pyramid: true);        // exception at File.Delete(filePath) below

// Open and read it
using (var loadedImage = NetVips.Image.Tiffload(filePath))
{
    loadedImage.Getpoint(0, 0);
}

// Try to delete it
File.Delete(filePath);
```
As written in the code, I tested the bigtiff and pageHeight parameters and they do not seem to cause the problem. I only tested this using .Net

Thanks for your help!

**Comment by kleisauke** [comment]
I hope this information helped. Please feel free to re-open with more details if further assistance is required.
