### ISSUE TITLE
Is it possible to create an SRGB image from an array?

### ISSUE THREAD

**Issue by bbfe** [kleisauke/net-vips#156]
Can't find a single example on the internet. Seems like such a basic thing. Can't believe it isn't one of the examples.

I just want to do something like this only with RGB values instead of grayscale.

NetVips.Image i = NetVips.Image.NewFromArray(new[,]
            {
                { 256 * 256, -1, -1},
                {-1, 16, -1},
                {-1, -1, -1}
            });

**Comment by kleisauke** [comment]
Hello, I think you can use the [`Image.NewFromMemory`](https://kleisauke.github.io/net-vips/api/NetVips.Image.html#NetVips_Image_NewFromMemory_) operation for this.

So, to process an RGBRGB style array you can just do:
```csharp
var red = new byte[] { 255, 0, 0 };
var width = 100;
var height = 100;
var memory = Enumerable.Repeat(red, width * height).SelectMany(col => col).ToArray();

using var image = Image.NewFromMemory(memory, width, height, 3, Enums.BandFormat.Uchar);
image.WriteToFile("red.png");
```

**Comment by kleisauke** [comment]
I hope this information helped. Please feel free to re-open if questions remain.
