### ISSUE TITLE
gifsave_buffer: frame too large

### ISSUE THREAD

**Issue by c23-cbu** [kleisauke/net-vips#157]
Hello,
I'm trying to load a PDF and making a GIF from the 10 first pages. But it seems, it doesn't work.

I got this error message:
`NetVips.VipsException: unable to call gifsave_buffer
gifsave_buffer: frame too large`

Link of the PDF: https://filesamples.com/samples/document/pdf/sample1.pdf
Here is my code: 
```c#
      var fileBytes = File.ReadAllBytes(filePath);
      int pageCount = 0;

      using (var image = Image.NewFromBuffer(fileBytes))
      {
        pageCount = (int)image.Get("n-pages");
      }

      if (pageCount > 9) pageCount = 10;

      var pages = new List<Image>(); ;
      for (int i = 0; i < pageCount; i++)
      {
        using var page = Image.PdfloadBuffer(fileBytes, page: i, n: 1, scale: 2, dpi: 150);
        pages.Add(page);
      }

      // join all pages
      using var join = Image.Arrayjoin(pages.ToArray(), across: 1);
      return join.GifsaveBuffer();

```

If I generate a JPG with JpegsaveBuffer, it works.
I tried to read this post: https://github.com/libvips/libvips/issues/1167 but not sure if my problem come from frames.

Any idea ?
Thanks

**Comment by kleisauke** [comment]
Hi @c23-cbu,

Sorry for the delay. The new GIF saver can only save GIF images smaller than 2000x2000 pixels, see:
https://github.com/libvips/libvips/blob/d9c00eb5ca577018b40533f041230754484ace7e/libvips/foreign/cgifsave.c#L437-L442

You're trying to save a GIF image of 2550x3300 pixels, which will not work after PR https://github.com/libvips/libvips/pull/2445. There was some discussion to revert the GIF saver behavior by generating global palettes (and thus removing this limit), but it's not there yet.
