### ISSUE TITLE
Optimiser bug in libgsf

### ISSUE THREAD

**Issue by gjactat** [kleisauke/net-vips#16]
Hello,
I have noticed that sometimes, calls to Dzsave produce the following exception : 

`  Exception= System.AccessViolationException: Tentative de lecture ou d'écriture de mémoire protégée. Cela indique souvent qu'une autre mémoire est endommagée (i.e : Attempt to read or write protected memory. This often indicates that another memory is damaged.)
   à NetVips.Internal.VipsOperation.VipsCacheOperationBuild(Operation operation)
   à NetVips.Operation.Call(String operationName, VOption kwargs, Object[] args)
   à NetVips.ExtensionMethods.Call(Image image, String operationName, VOption kwargs, Object arg)
   à NetVips.Image.Dzsave(String filename, String basename, String layout, Nullable'1 pageHeight, String suffix, Nullable'1 overlap, Nullable'1 tileSize, Nullable'1 centre, String depth, String angle, String container, Nullable'1 properties, Nullable'1 compression, Nullable'1 strip, Double[] background)
`

It's quite hard to figure out when and why it happens. These exceptions generally lead the whole process to a crash (even with . From what I've observed, once the process has successfully produced one pyramid, the following ones will be OK. It happened on several hosts, which exclude an hardware memory issue or something host related.

This happens with 32bits release of LibVips but could be reproduced with the 64bits release as well (with code that allocates memory before calling NetVips to get closer to real life conditions). Maybe this could be related to the amount of available memory for the thread. Anyway, pushing the limits with memory usually lead to a more classic (and sympathetic) exception (like "not enough memory for..." which is perfect)... But sometimes, I get this deadly low level AccessViolationException which make the whole process unstable and finally crash it down).

I'll try to upgrade NetVips and LibVips to the latest releases (who knows...). But if it's something that you already experienced, I'd be interested in a hint :-)

Thanks for your attention

**Comment by gjactat** [comment]
Windows Event Viewer reports the following error : 
`
Nom du module défaillant : libgobject-2.0-0.dll, version : 2.54.3.0, horodatage : 0x00000000
`

**Comment by kleisauke** [comment]
Hello, it looks like you've run into https://github.com/lovell/sharp/issues/1151 which will be addressed in the next release of NetVips. The next release will bundle and depend upon the forthcoming libvips v8.7.0.

You can test this now by downloading the pre-compiled binaries from: https://github.com/kleisauke/build-win64-mxe/releases

**Comment by gjactat** [comment]
Well, it fells like I'm in the same boat indeed. Multi-threading and same stack trace. I will test your latest release as soon as possible and give you my feedback.

Thanks for the help !

**Comment by gjactat** [comment]
Yes !... The bug seems clearly gone. I've tested tens of launches and did not observed any crash at startup. I was having this problem in nearly half of my previous tests.

Thanks !

**Comment by kleisauke** [comment]
I've just released NetVips 1.0.5 which bundle and depend upon libvips 8.7.
