### ISSUE TITLE
IccTransform("srgb", embedded: true, inputProfile: "srgb") transform 16bit images to 8bit images

### ISSUE THREAD

**Issue by fredprodibi** [kleisauke/net-vips#160]
Hello I have an input file that is 16bit, after the call to IccTransform("srgb", embedded: true, inputProfile: "srgb") the file is now 8bit.

is it a bug or by design? 
how can you do IccTransform on 16bit file and preserve the bit depth?

```
using NetVips;

using var original = Image.NewFromFile(@".\16bit.tif");
original.Jxlsave(@".\16bit.jxl", distance: 0.5);

using var conformSrgb = original.IccTransform("srgb", embedded: true, inputProfile: "srgb");
conformSrgb.Jxlsave(@".\16bit_conformSrgb.jxl", distance: 0.5);
```
demo file:
https://prodibifileshare.blob.core.windows.net/libvips/16bit.tif

results:
https://prodibifileshare.blob.core.windows.net/libvips/16bit.jxl
https://prodibifileshare.blob.core.windows.net/libvips/16bit_conformSrgb.jxl

tool to check the bitdeph on jxl files
https://prodibifileshare.blob.core.windows.net/libvips/jxlinfo.exe

**Comment by kleisauke** [comment]
By default, `IccTransform` / `vips_icc_transform` will output an 8-bit image. You can set the depth argument to 16 to get a 16-bit image.
```csharp
using var original = Image.NewFromFile("16bit.tif");
original.Jxlsave("16bit.jxl", distance: 0.5);

using var srgb = original.IccTransform("srgb", embedded: true, inputProfile: "srgb", depth: 16);
srgb.Jxlsave("16bit_srgb.jxl", distance: 0.5);
```

**Comment by kleisauke** [comment]
You can check if `.Interpretation` equals `Enums.Interpretation.Rgb16` (`VIPS_INTERPRETATION_RGB16`). For example, to convert to sRGB/Display P3, depending on whether pixel values are 16-bit:
```csharp
using var original = Image.NewFromFile("16bit.tif");

// Are pixel values in this image 16-bit integer?
var is16Bit = original.Interpretation == Enums.Interpretation.Rgb16;

// Ensure images with P3 profiles retain full gamut
var processingProfile = is16Bit ? "p3" : "srgb";

// Convert to sRGB/P3 using embedded profile
using var transformed = original.IccTransform(processingProfile,
    embedded: true,
    inputProfile: "srgb", // Fallback to sRGB
    intent: Enums.Intent.Perceptual, // Use "perceptual" intent to better match *magick
    depth: is16Bit ? 16 : 8);
transformed.Jxlsave("16bit.jxl");
```

**Comment by fredprodibi** [comment]
Thank you it helps a lot
