### ISSUE TITLE
Pdf thumbnails and bcmap files

### ISSUE THREAD

**Issue by gjactat** [kleisauke/net-vips#161]
Hello,

I need to produce thumbnails from pdf files that are a bit special because they require ".bcmap" files to render properly.
I first noticed that those files were different as I was try to display them through pdfjs while my web server wasn't set up to serve ".bcmap" files at all (mime types issue).

In that case, most of the text is missing. So I enabled those files on my web server and everything displayed OK in the browser... You can confirm this by displaying the attached pdf file through the [pdfjs demo page](https://mozilla.github.io/pdf.js/web/viewer.html).

You will notice that [the following file ](https://github.com/mozilla/pdf.js/blob/master/external/bcmaps/Adobe-Japan1-UCS2.bcmap)is loaded by the browser and is required to render the pdf properly. If you block this file (with Chrome DevTools), the text will be missing.

![image](https://user-images.githubusercontent.com/1826064/157194275-15095ecf-3374-4879-b782-671ec37a59a8.png)

Same goes for NetVips I guess. The produced output is missing most of the text, just like pdfjs when the bcmap file is not loaded successfully.

Is there a way to provide NetVips with a "bcmap" folder path so that the rendering engine can leverage them ? I've never met those "bcmap" files before. From what I've read, they are "binary cmap files".

Thanks for your attention.

Sample Pdf file :
[Archery SpectatorGuide_sports_Archery_oly_en.pdf](https://github.com/kleisauke/net-vips/files/8203847/Archery.SpectatorGuide_sports_Archery_oly_en.pdf)

NetVips Thumbnail (missing text highlighted in red) :
![image](https://user-images.githubusercontent.com/1826064/157193406-9e2ebf8f-ea9b-4ee7-879d-ddc9cc4e354a.png)

**Comment by kleisauke** [comment]
Hi @gjactat,

I think you'll need the optional `poppler-data` encoding files to render CJK and Cyrillic characters properly. These encoding files have different license(s) as Poppler, and thus not distributed within the `-all` variant of the libvips Windows binaries.

To install this, you can download:
https://poppler.freedesktop.org/poppler-data-0.4.11.tar.gz

And extract this to `$VIPSHOME\share\poppler`, where `$VIPSHOME` is the installation location of libvips. If you have git installed, I might be easier to just clone the https://gitlab.freedesktop.org/poppler/poppler-data repository. For example:
```powershell
PS C:\> cd vips-dev-8.12\share
PS C:\vips-dev-8.12\share> git clone https://gitlab.freedesktop.org/poppler/poppler-data.git poppler
```

Running:
```bash
$ vipsthumbnail.exe Archery.SpectatorGuide_sports_Archery_oly_en.pdf -s 300x -o tn_%s.png
```

On my Windows PC with these encoding files installed, produces this thumbnail:
![tn_Archery SpectatorGuide_sports_Archery_oly_en](https://user-images.githubusercontent.com/12746591/157861830-51a29670-7009-4208-87cc-40a88cd87372.png)

**Comment by gjactat** [comment]
Hello @kleisauke,
Thank you very much for your quick answer !
It works perfectly well.
