### ISSUE TITLE
How to package libvips native binaries to use with NetVips

### ISSUE THREAD

**Issue by fredprodibi** [kleisauke/net-vips#163]
Hello,

I made a build of libvips including libjxl with and Ubuntu docker container.

If I manually add the content of the build/libvips to the runtimes\linux-x64\native folder the app seems to work and be able to decode jxl files.

Do you know how I can package those binaries and setup my visual studio project so that they are added to runtimes\linux-x64\native when I build or publish the app?

may be a packaging like you do for NetVips.Native.linux-x64 ? but I don't know how to do that

any help would be welcome

**Comment by kleisauke** [comment]
The [kleisauke/libvips-packaging](https://github.com/kleisauke/libvips-packaging) repository and [`Build.cs`](https://github.com/kleisauke/net-vips/blob/master/build/Build.cs) script are used for this.

Note that NetVips will always looks for a globally installed libvips, so this should not be necessary in most cases. Especially on Linux, setting the `LD_LIBRARY_PATH` environment variable should be more appropriate if you've installed libvips on a non-standard path (anything other than `/usr` or `/usr/local`).

**Comment by kleisauke** [comment]
I hope this information helped. Please feel free to re-open if questions remain.
