### ISSUE TITLE
Where can I download magick library?

### ISSUE THREAD

**Issue by qtbui159** [kleisauke/net-vips#166]
When I use Image.Magickload，it throws NetVips.VipsException:“no such operation magickload
VipsOperation: class "magickload" not found”. So where download magick library?

Plaform:windows 10 x64; .net 4.8;

Thx.

**Comment by kleisauke** [comment]
On Windows, the `-all` variant available on https://github.com/libvips/build-win64-mxe/releases includes a complete copy of ImageMagick.

Note that this variant contains ALL the file format loaders that libvips supports, including some very minor ones. It can process many different file types, but it is also rather vulnerable to hacking. It also contains GPL licensed libraries, so it's slightly problematic to distribute binaries that uses this variant.

**Comment by kleisauke** [comment]
I hope this information helped. Please feel free to re-open if questions remain.

**Comment by ChrisAbra** [comment]
Hi, the above somewhat solves the issue for windows but not necessarily for mac and linux, or replicate the ease of packaging as using the precompiled nuget packages and being able to compile projects purely from the C# solution which is crucial for shipping an app which uses the libraries.

If i also have the Magic.NET package from nuget, is there a way to get NetVips to know this and use it for MagickLoad?

I'd rather not have to do the buffer transfers and use Magick by default for file loading, it is an option i'll try in the meantime though.
