### ISSUE TITLE
Question: Writing EXIF

### ISSUE THREAD

**Issue by jeromenelson** [kleisauke/net-vips#167]
Hello there,

Hoping this is a quick one. How to insert IFD2/Lens tags into an image? I was able to set many other tags without any issues, anything related to Lens info (`exif-ifd2-LensModel`, `exif-ifd2-LensSpecification`, `exif-ifd2-LensSerialNumber`, `exif-ifd2-LensMake`) does not seem to work.

```
            using var image = NetVips.Image.NewFromFile(Path.Join(_path, "img_no_exif.jpg"));
            image.Mutate(m => m.Set(GValue.GStrType, "exif-ifd2-LensMake", "Canon"));
            image.WriteToFile(Path.Combine(_path, "img_with_lens_info.jpg"));

            using var exifed = NetVips.Image.NewFromFile(Path.Join(_path, "img_with_lens_info.jpg"));
            bool hasLensMake = exifed.Contains("exif-ifd2-LensMake");
```

Side note: I tried both `GValue.GStrType` and `GValue.RefStrType` with no luck. For other tags, I figured out how to successfully set certain values through trial and error - for example, while working with other numeric fields (say `exif-ifd2-FNumber`), instead of directly using `GValue.GDoubleType` I had to convert it to a rational string and then use the type `GValue.RefStrType` to successfully set. But this simple string field, I just can't get to the bottom of it. 

Thank you in advance!

**Comment by kleisauke** [comment]
Hi @jeromenelson,

These ASCII tags were added in the EXIF 2.3 specification, which libvips is currently unaware of. I've just opened PR https://github.com/libvips/libvips/pull/2795 that allows you to modify/create these tags in libvips. After that, this should work without any problems:
```csharp
using var image = Image.NewFromFile("x.jpg");
using var mutated = image.Mutate(m => m.Set(GValue.GStrType, "exif-ifd2-LensMake", "Canon"));
mutated.WriteToFile("x2.jpg");

using var image2 = Image.NewFromFile("x2.jpg");
Debug.Assert(image2.Contains("exif-ifd2-LensMake"));
```

**Comment by jerome-zenfolio** [comment]
Thank you for the quick response, any idea how long would it take for this PR to make it into the next release?

**Comment by jeromenelson** [comment]
Thank you for the quick response, any idea how long would it take for this PR to make it into the next release?

**Comment by kleisauke** [comment]
We aim for a release in late May, see: https://github.com/libvips/libvips/issues/2790. Setting `exif-ifd2-LensSpecification` should be possible after PR https://github.com/libexif/libexif/pull/85, e.g.:
```csharp
using var image = Image.Black(100, 100);
using var mutated = image.Mutate(m => m.Set(GValue.GStrType, "exif-ifd2-LensSpecification", "5/1 10/1 100/1 200/1"));
mutated.WriteToFile("x2.jpg");

using var image2 = Image.NewFromFile("x2.jpg");
Debug.Assert(image2.Contains("exif-ifd2-LensSpecification"));
```

**Comment by kleisauke** [comment]
[NetVips v2.2.0](https://www.nuget.org/packages/NetVips/2.2.0) and [NetVips.Native v8.13.0](https://www.nuget.org/packages/NetVips.Native/8.13.0) is now available. 

Note that setting `exif-ifd2-LensSpecification` would require libexif to be built from the `master` branch, the pre-built binaries provided by NetVips are built against libexif v0.6.24.

**Comment by jeromenelson** [comment]
Thank you, super excited about the other new features as well!
