### ISSUE TITLE
Is it possible to use System.Drawing.Bitmap to construct NetVips.Image object?

### ISSUE THREAD

**Issue by Gigas002** [kleisauke/net-vips#17]
I add Picture.png file as resource to my project and read it as Bitmap in code:

`var bitmap = Properties.Resources.Picture;`

Can I use that object to somehow create the Image object?

**Comment by Gigas002** [comment]
Thanks, that worked for me! I have one more question, if you don't mind. 
Sometimes I need to proceed the images with 2 or 3 bands together with 4 bands images to Image.Arrayjoin method, and it throws an exception:

> NetVips.VipsException: unable to call arrayjoin: not one band or 4 bands

The following line for ImageMagick workied fine with those images:

> montage 1.jpg 2.jpg 3.jpg 4.jpg -background none PNG24:5.jpg

Is there any way to do the same with NetVips?

**Comment by kleisauke** [comment]
Just make sure that all images have the have the same number of bands, for example:
```csharp
var images = new[] {
    // 3 bands
    Image.NewFromFile("lichtenstein.jpg", access: Enums.Access.Sequential),
    // 4 bands
    Image.NewFromFile("transparency_demo.png", access: Enums.Access.Sequential),
};

// Get the maximum number of bands for this sequence of images.
var maxBands = images.Max(i => i.Bands);

for (var i = 0; i < images.Length; i++)
{
    var image = images[i];
    var bands = image.Bands;

    // Do we need to normalize?
    if (bands == maxBands)
    {
        continue;
    }

    // Normalize the number of bands by joining them up bandwise.
    for (var j = bands; j < maxBands; j++)
    {
        // 255 to opaque, 0 to transparent.
        images[i] = images[i].Bandjoin(255);
    }
}

var joined = Image.Arrayjoin(images);
joined.WriteToFile("test.png");
```

**Comment by Gigas002** [comment]
Nice solution! Thanks alot for your quick and informative response!
