### ISSUE TITLE
Writing Dzsave to a stream instead of folder

### ISSUE THREAD

**Issue by mhd420** [kleisauke/net-vips#173]
Thank you for maintaining these bindings, this library has helped our developer significantly speed up splitting very large satellite imagery in our application.

We are using the Dzsave function to generate image pyramids and saving the data into a temporary folder. Later, we have to read these files back in to store them into a Sqlite database. 

Is it possible to call Dzsave in a way where we can grab the output streams and insert them directly? I have a feeling that this is likely a limitation of the upstream libvips library, but thought it would be worth asking. I had a look through the provided samples and couldn't see anything relevant with the Dzsave method.

Thanks

**Comment by kleisauke** [comment]
libvips 8.13.0 provides a `dzsave_target` function, which will be available as `Dzsave{Target,Stream}` in the forthcoming NetVips v2.2.0 - see:
https://www.libvips.org/2022/05/28/What's-new-in-8.13.html#tiffsave-and-dzsave-to-target

I'm assigning this to the 2.2.0 milestone.

**Comment by kleisauke** [comment]
[NetVips v2.2.0](https://www.nuget.org/packages/NetVips/2.2.0) and [NetVips.Native v8.13.0](https://www.nuget.org/packages/NetVips.Native/8.13.0) is now available.

**Comment by kleisauke** [comment]
Hope this helped, please feel free to re-open if questions remain.
