### ISSUE TITLE
AVX requirement?

### ISSUE THREAD

**Issue by majora2007** [kleisauke/net-vips#176]
I have multiple users that have issues running any NetVips Image Save (or Thumbnail) operations when their CPU does not have AVX instruction set available. Is there any requirement of this library? 

I searched and didn't see any mention of this. For example:
https://github.com/Kareadita/Kavita/issues/1423
https://github.com/Kareadita/Kavita/issues/1413

STM Monaco STiH412 Processor is the CPU shared by these users (others have reported not having AVX). 

When NetVips operations occur, the application crashes and Illegal Instruction occurs and the core dumps. 

This has occured on many versions since last 2 years, but still present in NetVips 2.2.0 and NetVips.Native 8.13.0

**Comment by kleisauke** [comment]
The prebuilt binaries provided by NetVips doesn't require the AVX and AVX2 instruction sets. However, it can still use these instructions via runtime dispatch.

As of [NetVips.Native v8.10.6](https://www.nuget.org/packages/NetVips.Native/8.10.6) and lovell/sharp-libvips#88, the prebuilt binaries for Linux x64 now require a Westmere CPU or later, which is pretty much all the Intel and AMD CPUs made in the last 11 years (so we can use SSE4.2, POPCNT, AES and PCLMUL intrinsics). We could possibly lower this to `x86-64-v2` to be able to run on Intel Nehalem (which doesn't support AES and PCLMUL), I just opened issue https://github.com/lovell/sharp-libvips/issues/153 for this.

The prebuilt binaries for Windows x64/i686 require at least Windows 7 (see https://github.com/libvips/libvips/discussions/2292#discussioncomment-844896), which implies that it needs SSE2 or higher starting with the March 2018 Windows 7 updates.

The prebuilt binaries for Linux ARMv7 requires the Neon instruction set and VFPv4 floating-point extensions. The AArch64 architecture doesn't have any additional CPU requirements.

> STM Monaco STiH412 Processor

This CPU is based on ARMv7 and supports the Neon instruction set, but not VFPv4, it only supports VFPv3. Perhaps changing [`-mfpu=neon-vfpv4`](https://github.com/lovell/sharp-libvips/blob/a40f861fae54f23d8ea396a483a2d2b93288fc91/linux-armv7/Dockerfile#L48) to `-mfpu=neon-fp16` would allow it to run on Synology DS216play.

**Comment by majora2007** [comment]
Maybe I'm using NetVips wrong, but do I need NetVips AND NetVips.Native or can i just use NetVips directly? 

From the detailed answer, I'm reading as no, there is no hardset AVX instruction set requirements, however form ARM, VFPv4 needs to be present. Otherwise, with linux there is a SSE4.2 requirements, but nothing else drastically required. 

I've only ran into a handful of users complaining, usually with older CPUs and since this library is where the code crashes, I always assumed there was some requirement, but it sounds like for the most part, there aren't many requirements.

**Comment by kleisauke** [comment]
You can use NetVips directly if you have libvips installed globally (e.g. via the package manager), which is also why these NetVips.Native packages can be installed optionally.

Indeed, the requirements are not drastically (sharp also a handful of Linux users that complained). I'm aware that in 2022 more distros/packages will be raising the x86-64 platform requirement to x86-64-v2. For example, RHEL 9 (and its derivatives) raised the platform requirement to this microarchitecture level - see:
https://developers.redhat.com/blog/2021/01/05/building-red-hat-enterprise-linux-9-for-the-x86-64-v2-microarchitecture-level

**Comment by majora2007** [comment]
Going to close this issue, thanks again Kleis.
