### ISSUE TITLE
Processing .fits Images

### ISSUE THREAD

**Issue by ZENUAV** [kleisauke/net-vips#180]
Hi, I'm getting the error

VipsForeignLoad: source is not in a known format

When trying to process a .fits file. I assume this functionality is not part of the standard build.

```
    <PackageReference Include="NetVips" Version="2.2.0" />
    <PackageReference Include="NetVips.Native.win-x64" Version="8.13.2" />
```

I was hoping just putting the libcfitsio.dll in the output folder would do the trick, but it does not.

Do I need to rebuild libvips using the Meson build system and what do I need to edit for .fits support.

I'm using Visual Studio, and have never used Meson, are there and instructions anywhere?

Thanks in advance, Jason.

**Comment by kleisauke** [comment]
I hope this information helped. Please feel free to re-open if questions remain.
