### ISSUE TITLE
NetVips is set on loading dlls on Arch linux

### ISSUE THREAD

**Issue by Silverdimond** [kleisauke/net-vips#186]
While trying using NetVips Version 2.2.0 on linux with dotnet7 I keep getting exceptions telling me the libvips-42.dll was not found
```
System.DllNotFoundException: Unable to load shared library 'libvips-42.dll' or one of its dependencies. In order to help diagnose loading problems, consider using a tool like strace. If you're using glibc, consider setting the LD_DEBUG environment variable:
(PROJECT BIN DEBUG DIR)/runtimes/linux-x64/native/libvips-42.dll.so: cannot open shared object file: No such file or directory
/usr/share/dotnet/shared/Microsoft.NETCore.App/7.0.0/libvips-42.dll.so: cannot open shared object file: No such file or directory
(PROJECT BIN DEBUG DIR)/libvips-42.dll.so: cannot open shared object file: No such file or directory
(PROJECT BIN DEBUG DIR)/runtimes/linux-x64/native/liblibvips-42.dll.so: cannot open shared object file: No such file or directory
/usr/share/dotnet/shared/Microsoft.NETCore.App/7.0.0/liblibvips-42.dll.so: cannot open shared object file: No such file or directory
(PROJECT BIN DEBUG DIR)/liblibvips-42.dll.so: cannot open shared object file: No such file or directory
(PROJECT BIN DEBUG DIR)/runtimes/linux-x64/native/libvips-42.dll: cannot open shared object file: No such file or directory
/usr/share/dotnet/shared/Microsoft.NETCore.App/7.0.0/libvips-42.dll: cannot open shared object file: No such file or directory
(PROJECT BIN DEBUG DIR)/libvips-42.dll: cannot open shared object file: No such file or directory
(PROJECT BIN DEBUG DIR)/runtimes/linux-x64/native/liblibvips-42.dll: cannot open shared object file: No such file or directory
/usr/share/dotnet/shared/Microsoft.NETCore.App/7.0.0/liblibvips-42.dll: cannot open shared object file: No such file or directory
(PROJECT BIN DEBUG DIR)/liblibvips-42.dll: cannot open shared object file: No such file or directory
```
With NetVips.Native Version 8.13.2 `(PROJECT BIN DEBUG DIR)/runtimes/linux-x64/native/libvips.so.42` does exist but `(PROJECT BIN DEBUG DIR)/runtimes/linux-x64/native/libvips-42.dll.so` doesn't.
Decompiling using fuget 
![image](https://user-images.githubusercontent.com/46320280/206878730-49eadd53-64ec-4346-a934-469228284e28.png)
And decompiling using jetbrains rider 
![image](https://user-images.githubusercontent.com/46320280/206878760-4ed04aaa-9efd-458a-abf9-293b0b1d7b5a.png)
Leads me to believe it is trying to find the a sort of .dll.so hybrid which is just not present in the runtimes native folder.
Either way renaming `(PROJECT BIN DEBUG DIR)/runtimes/linux-x64/native/libvips.so.42` to `(PROJECT BIN DEBUG DIR)/runtimes/linux-x64/native/libvips-42.dll.so` doesn't fix the issue because it requests a different dll `libgobject-2.0-0.dll`.
According to nuget.info libgobject-2.0-0 isn't even shipped 
![image](https://user-images.githubusercontent.com/46320280/206878932-4af0ed8b-fd55-4500-afc8-fd22c903791b.png) but I am assuming it is referring to `libglib-2.0.so` (provided by glib2 on the arch linux core repo)
But it can't load `libglib-2.0.so` by asking for `libgobject-2.0-0.dll.so`
I doubt that the distro has anything to do with this but I am using EndeavourOS with the 5.15.82-1-lts kernel

**Comment by kleisauke** [comment]
It looks like this is being tracked in issue https://github.com/dotnet/runtime/issues/62554, which also affects the `System.IO.Ports` NuGet package.

> the second command's result is empty

This is expected, you can overridde the detected RID with that environment variable, so in most cases it's not set.
