### ISSUE TITLE
TIFF file handle not released

### ISSUE THREAD

**Issue by feelgood-interface** [kleisauke/net-vips#187]
My use case is an API which receives a file and generates a thumbnail. When I receive the file I am saving it as a temp file, because keeping the file in memory caused high memory usage. After processing, I delete the temp file.

It is working, except for TIFF files. When attempting the delete, I get an exception that the file is still being used. I also tried to explicitly call _Dispose()_ on the image. Here is the sample code:
```
var stream = new MemoryStream();
using (var image = NetVips.Image.NewFromFile(filePath))
{
    image.WriteToStream(stream, ".jpg");
}
File.Delete(filePath);
```

**Comment by kleisauke** [comment]
Hello, I think the file is being held open in libvips' cache. Please see https://github.com/kleisauke/net-vips/issues/6#issuecomment-394379299 and [the corresponding libvips documentation](https://www.libvips.org/API/current/VipsOperation.html#vips-cache-set-max-files).

**Comment by feelgood-interface** [comment]
I already tried that, still the same problem.

**Comment by kleisauke** [comment]
FWIW, this problem only occurs on Windows, other platforms let you delete open files. Recently there was some [discussion about this](https://github.com/libvips/libvips/discussions/3185#discussioncomment-4236746), but those workarounds are probably not worth the effort.
