### ISSUE TITLE
Blazor Server Net-Vips

### ISSUE THREAD

**Issue by GraemeWellington** [kleisauke/net-vips#189]
Here is a Net-Vips sample working in Blazor Server net7.0.
The following Nugets required: NetVips / NetVips.Native

[NetVipsGo.razor.txt](https://github.com/kleisauke/net-vips/files/10415489/NetVipsGo.razor.txt)

**Comment by kleisauke** [comment]
Hi @GraemeWellington,

Nice to see that NetVips is usable in Blazor Server. I recommend https://github.com/kleisauke/wasm-vips if you want to run libvips client-side in the browser. It has a similar API as the .NET binding. The online playground can be useful for making prototypes:
http://kleisauke.github.io/wasm-vips/playground/

I'll close, as this is not actionable.
