### ISSUE TITLE
Openslideload   mrxs

### ISSUE THREAD

**Issue by 1115284051** [kleisauke/net-vips#193]
open mrxs file
  NetVips.Image openImg = NetVips.Image.Openslideload(@"D:\slide\G48117.mrxs");

error:
   NetVips.VipsException:“no such operation openslideload VipsOperation: class "openslideload" not found”

Can't use openslide?

**Comment by kleisauke** [comment]
Hello, did you see #18?

**Comment by kleisauke** [comment]
I hope this information helped. Please feel free to re-open if questions remain.
