### ISSUE TITLE
Memory leak with Image.Resize?

### ISSUE THREAD

**Issue by ionut-gheorghe** [kleisauke/net-vips#194]
Hi, I an using netvips to create an image from an array and resize it to its real dimensions. The problem is that the memory keeps growing everytime i resize the image.

Here is the screenshot of the method and memory. In 5 executions the memory keeps growing (tested with more than 100 executions also)
![image](https://user-images.githubusercontent.com/54311614/216293386-0e3e1f6b-e37d-4b88-bfb9-33fd03f9295b.png)
If I comment the highlighted line the memory does not increase, stays at a constant value.
What am I doing wrong?

![image](https://user-images.githubusercontent.com/54311614/216296306-4fffcc0a-b8b3-4c65-b058-637937a01c03.png)

**Comment by kleisauke** [comment]
Are you able to provide a sample image and a standalone code sample that demonstrates this problem? Looking at those screenshots, I think you should do:
```diff
-using var resized = image.Resize(heightScale, vscale: widthScale);
+using var resized = image.Resize(widthScale, vscale: heightScale);
```

However, you might consider using `Image.Thumbnail` instead. Otherwise, none of the very fast shrink-on-load tricks are possible.

**Comment by ionut-gheorghe** [comment]
It scales correctly, the variables names are measleading. I noticed that after 8 or 10 images the memory does not increase anymore. Could this be related to caching?

**Comment by kleisauke** [comment]
@ionut-gheorghe Were you able to make any progress with this?

**Comment by kleisauke** [comment]
I hope this information helped. Please feel free to re-open if questions remain.
