### ISSUE TITLE
Missing Remove method

### ISSUE THREAD

**Issue by fredprodibi** [kleisauke/net-vips#195]
Hi,

In this post it seems that a Remove method exists to remove metadata, I can't find it in .NET

https://github.com/libvips/libvips/discussions/2283

**Comment by kleisauke** [comment]
Hello, did you see #121 and https://kleisauke.github.io/net-vips/introduction.html#metadata-and-attributes?

**Comment by fredprodibi** [comment]
Thank you! I just tested it works!
