### ISSUE TITLE
v8.14.1 release date?

### ISSUE THREAD

**Issue by fredprodibi** [kleisauke/net-vips#197]
Just curious, on any idea when [v8.14.1](https://github.com/libvips/libvips/releases/tag/v8.14.1) will be available for .net?

Thank you

**Comment by kleisauke** [comment]
There are some useful fixes accumulated in the upcoming libvips v8.14.2 (and its dependencies), so I plan to release the prebuilt binaries on NuGet for this version instead.

**Comment by kleisauke** [comment]
[NetVips.Native v8.14.2](https://www.nuget.org/packages/NetVips.Native/8.14.2) is now available.
