### ISSUE TITLE
Some Tif file does not convert. (Using code not yet in table)

### ISSUE THREAD

**Issue by AndrePScope** [kleisauke/net-vips#201]
Hello @kleisauke and @jcupitt !

We have a problem with converting some **Tif** files by Net(Lib)Vips.

We got the error:
```
"unable to call tiffsave
source input: Using code not yet in table
tiff2vips: read error"
```

To reproduce it you can use a very simple .Net code:
``` C#
var image = Image.NewFromFile(filePath, access: Enums.Access.Sequential);
var targetFilePath = Path.ChangeExtension(filePath, ".new.tif");
image.Tiffsave(targetFilePath);
```

Probably the reason of the problem can be in the source image file, but I do not what exactly.
This picture opens via ```System.Drawing.Image```  quite well.

``` C#
var image = System.Drawing.Image.FromFile(fileName);
image.Save(targetFileName, ImageFormat.Tiff);
```

I have attached the example zip file with Tif image to this ticket.
[example.zip](https://github.com/kleisauke/net-vips/files/10805098/example.zip)

Thank you in advance 
  for your research and explanation.

Andrii

P.S.
```
  <ItemGroup>
    <PackageReference Include="NetVips" Version="2.2.0" />
    <PackageReference Include="NetVips.Extensions" Version="2.1.0" />
    <PackageReference Include="NetVips.Native" Version="8.13.2" />
  </ItemGroup>
```

**Comment by jcupitt** [comment]
Hi @AndrePScope,

Your zip file only contains one JPEG image. Did you upload the right file?

**Comment by AndrePScope** [comment]
Sorry for the wrong file.
The Tif image has 30M size, so I had to compress and split it on two files with Zip.
This zip with 2 parts is correct:

[example.001.zip](https://github.com/kleisauke/net-vips/files/10805501/example.001.zip)
[example.002.zip](https://github.com/kleisauke/net-vips/files/10805514/example.002.zip)

But, please rename the files from 
```
example.001.zip
example.002.zip
```
to 
```
example.zip.001
example.zip.002
```
(because of restriction of extensions on Github)

**Comment by jcupitt** [comment]
Ah, I have it now.

I tried with `tiffcp`, the official TIFF copy program:

```
$ tiffcp example.tif x.tif
example.tif: Using code not yet in table.
example.tif: Error, can't read strip 46.
```

So I guess this file does not follow the TIFF spec. somehow.

Do you know how it was created? It looks like a photoshop file, but has it been also processed by any other program?

**Comment by jcupitt** [comment]
It fails to load into photoshop 24 with a "tiff parse error".

It loads into windows picture viewer, interestingly, but with rendering issues:

![Untitled](https://user-images.githubusercontent.com/580843/220701234-b9069b17-0249-4b3e-a8c6-d36bf41973b3.png)

That's the same strip that libtiff fails on.

Anyway, it looks like the image has been corrupted somehow.

**Comment by AndrePScope** [comment]
Thank you, @jcupitt , very much for your investigation!

I am trying to find out how this file was created. 
For now, I do not know. This issue came to us from the customer side.

Yes, I also guess that it is some problem with the source file.

You know, we work with NetVips on .Net 6.
And here, I can do some workaround...

I read this file via **System.Drawing** library from .Net (it works, but only for Windows OS), and then I convert this to NetVips Image via **NetVipsExtensions** library.

And then I can work with this NetVips object and do different conventions with NetVips.
This code works well:

``` C#
var image = System.Drawing.Image.FromFile(fileName);
var vipsImage = image.ToVips();

vipsImage.Tiffsave(targetFileName);
```
It looks like System.Drawing.Image do some fix on the fly during reading...

Ok, so, if you approve that this file is corrupted, I will close this ticket.

**Comment by jcupitt** [comment]
System.Drawing isn't fixing the file, it's just ignoring the errors. Your file will still be damaged (see the screenshot).

**Comment by AndrePScope** [comment]
Yes, you are right.
Better to say System.Drawing is ignoring the errors.

**Comment by AndrePScope** [comment]
Ok, I am closing the issue.
Probably we will do the workaround and in such cases will re-open file with SystemDrawing to ignore errors.

But if you decide to add some parameter in your method for ignoring errors, let us know, please.

Thank you for your explanation and quick feedback!
