### ISSUE TITLE
heif: Unsupported feature: Unsupported codec (4.3000)

### ISSUE THREAD

**Issue by Charltsing** [kleisauke/net-vips#202]
I use NetVips.2.3.0

pic : https://charltsing.lanzoum.com/iUQkB0r16reb

It looks like NetVips.Native.win.8.14.2 is using a version of libvips+libheif compiled without support for libde265. 
https://github.com/libvips/libvips/discussions/3407

I found libvips support libheif (ensure compatibility with libheif > 1.14.2 [kleisauke])
https://github.com/libvips/libvips/releases/tag/v8.14.2

what can i do?

**Comment by kleisauke** [comment]
Reading HEIC images requires a custom, globally-installed libvips that has itself been compiled with support for libde265.

The prebuilt binaries _will not_ include any support for HEIC whilst it is patent-encumbered.

**Comment by Charltsing** [comment]
> Reading HEIC images requires a custom, globally-installed libvips that has itself been compiled with support for libde265.
> 
> The prebuilt binaries _will not_ include any support for HEIC whilst it is patent-encumbered.

Where can I download the libvips binaries with support for libde265？

**Comment by kleisauke** [comment]
I hope this information helped. Please feel free to re-open if questions remain.
