### ISSUE TITLE
Can't remove metadata

### ISSUE THREAD

**Issue by feelgood-interface** [kleisauke/net-vips#204]
Good day,
I am trying to remove the EXIF orientation data from the image. In my application I am getting the error: _"can't remove metadata "exif-ifd0-Orientation" on shared image"_. However, If I execute the same code in a clean project it works fine. I tried disabling autorot and cache (as suggested here [https://github.com/janko/image_processing/issues/64](https://github.com/janko/image_processing/issues/64)), but still the same error message.
I am using NetVips 2.1.0 (Vips 8.12.2).

```
using (var image = Image.NewFromFile("C:\\temp\\exif.png"))
{
  using (var mutated = image.Mutate(mutable =>
  {
	  var removed = mutable.Remove("exif-ifd0-Orientation");
	  // removed == false: 
  }))
  {
  }
}
```

**Comment by kleisauke** [comment]
> Vips 8.12.2

Are you sure? Those errors were removed with commit https://github.com/libvips/libvips/commit/e4db74746a195b4688b5c40d0cb2da5abccc224a, released in libvips v8.9.2.

**Comment by feelgood-interface** [comment]
Using the `strip` option works. I will close the issue and post a comment if I find the reason for the problem.

**Comment by feelgood-interface** [comment]
I found the problem. There was a referenced package in my application, which had libvips DLLs of an old version.
