### ISSUE TITLE
Issue while save multi-page tiff image every tried everything as I can.

### ISSUE THREAD

**Issue by dayastark** [kleisauke/net-vips#205]
Hi, basically I need to merge couple of jpg image into one tiff multi frame image, which need to create new tiff image. here is my code, I tried everything but always get a vertical joined image which I doesn't required. 
@kleisauke  can please help me for this issue?

`      public static async Task<bool> MergePngToTiff(string[] files, string outputFile)
        {
            try
            {
                var mainImage = Image.NewFromFile(files[0]);
                var pageHeight = mainImage.PageHeight;
                var height = mainImage.Height;
                var width = mainImage.Width;
                var idx = 0;
                foreach (var file in files.Skip(1))
                {
                    var image = Image.NewFromFile(file);
                    mainImage = mainImage.Join(image, Direction.Vertical);
                    await Console.Out.WriteLineAsync($"Merge Image for {idx}/{files.Length}");
                    idx++;
                }
                mainImage = mainImage.Mutate(m =>
                {
                    m.Set(GValue.GIntType, "page-height", height);
                });

                mainImage.Tiffsave(outputFile);
                mainImage.Dispose();
                return true;
            }
            catch (Exception ex)
            {
                Console.WriteLine(ex.Message);
                return false;
            }
        }`

**Comment by kleisauke** [comment]
Hello, did you see #93? I think you'll need to pass `expand: true` to ensure the output will be expanded to contain all of the input pixels.
```diff
-                    mainImage = mainImage.Join(image, Direction.Vertical);
+                    mainImage = mainImage.Join(image, Direction.Vertical, expand: true);
```

Though, I would use `Image.Arrayjoin` in this case, which would be faster and use much less memory. See for example:
```csharp
string[] files = { "image1.png", "image2.png", "image3.png" };

var images = new Image[files.Length];
for (var i = 0; i < files.Length; i++)
{
    images[i] = Image.NewFromFile(files[i], access: Enums.Access.Sequential);
}

// We fetch the page height from the first image
// If the `page-height` property is not set, it defaults to the image height
var pageHeight = images[0].PageHeight;

// Join new pages
using var joined = Image.Arrayjoin(images, across: 1);

// Set page height
using var mutated = joined.Mutate(mutable =>
{
    mutable.Set(GValue.GIntType, "page-height", pageHeight);
});
mutated.Tiffsave("out.tif");
```

**Comment by kleisauke** [comment]
I hope this information helped. Please feel free to re-open if questions remain.
