### ISSUE TITLE
AVIF (Limited?) Support Question

### ISSUE THREAD

**Issue by majora2007** [kleisauke/net-vips#206]
I'm trying to load an AVIF file and save as PNG, like I do with many of the other formats, but I get:

```
NetVips.VipsException: unable to call VipsForeignSaveSpngFile
source_custom: bad seek to 83048
heif: Invalid input: Unspecified: Bitstream not supported by this decoder (2.0)

```

when using it on https://raw.githubusercontent.com/link-u/avif-sample-images/master/fox.profile0.10bpc.yuv420.avif

NetVips code:
```
 using var thumbnail = Image.ThumbnailBuffer(Convert.FromBase64String(encodedImage), thumbnailWidth);
fileName += (saveAsWebP ? ".webp" : ".png");
thumbnail.WriteToFile(_directoryService.FileSystem.Path.Join(_directoryService.CoverImageDirectory, fileName));
```

My knowledge of AVIF is pretty low, but is this something that is planned to be enhanced in the future (by libvips) or should I just hold off on AVIF support? It seems like 10bit images are the key which don't have support? 

I wanted to validate against these free images to understand NetVips support for the format, given Firefox has just released with full support.

https://github.com/link-u/avif-sample-images/blob/master/fox.profile0.10bpc.yuv420.avif

**Comment by kleisauke** [comment]
This AVIF image is 10-bit, which is unsupported by the pre-built libvips binaries provided by NetVips.
```console
$ heif-info -d fox.profile0.10bpc.yuv420.avif | grep bit
| | | bits_per_channel: 10,10,10
| | | high_bitdepth: 1
| | | twelve_bit: 0
```

See the [`CHANGELOG.native.md` for 8.10.6](https://github.com/kleisauke/net-vips/blob/master/CHANGELOG.native.md#8106---2021-03-30).
> * Build aom without HBR/WebM support (https://github.com/lovell/sharp-libvips/pull/94).

Please subscribe to [lovell/sharp-libvips#97](https://github.com/lovell/sharp-libvips/issues/97) for updates about a possible switch to smaller/faster alternatives for AVIF that might allow reading higher bit depth images again.

**Comment by majora2007** [comment]
Thanks kleisauke, will do. I figured it might be the 10bits, but wasn't sure if libvips had plans around support it further.
