### ISSUE TITLE
FindLoad and unicode characters

### ISSUE THREAD

**Issue by gjactat** [kleisauke/net-vips#210]
Hello,

For some reason, I had to deal with images that have funny names (like "L'Œuvre_(1915-09-24).jpg"). As you can see, there is a special character "Œ" in that name.

While "NetVips.Image.NewFromFile" works as expected with such a file name, "Image.FindLoad" returns null (instead of "VipsForeignLoadJpegFile"). The problem goes away as soon as I rename the file to avoid the "Œ" character.

To give you some context, I use "FindLoad" to check whether or not NetVips can process submitted files. I also use the result to discriminate pdf files.

Thanks for your attention
Guillaume

**Comment by gjactat** [comment]
I've dug a little deeper. ProcessMonitor shoewd me that the original file path was actually converted to "L'OEuvre_(1915-09-24).jpg" (s you can see, the "Œ" character has been changed to "OE".

I guess the following highlighted code is what makes the "Image.NewFromFile" ok  :

![image](https://github.com/kleisauke/net-vips/assets/1826064/9657c771-ba84-40fd-afff-36cdf91dffe2)

**Comment by kleisauke** [comment]
Commit 61d9d5ba9ac85a05f4b539104019376025961f52 should fix this. Thanks for reporting this!
 
If you want to test this, you can use the nightly version of NetVips. Add the `https://ci.appveyor.com/nuget/net-vips` feed in the `<packageSources>` section of your `NuGet.config`:
```xml
<packageSources>
  <add key="netvips-nightly" value="https://ci.appveyor.com/nuget/net-vips" />
</packageSources>
```

And update NetVips to 2.3.0 (build number 426 - prerelease). I'll make a new release soon.

**Comment by gjactat** [comment]
That was really quick !
Thank you !

**Comment by kleisauke** [comment]
[NetVips v2.3.1](https://www.nuget.org/packages/NetVips/2.3.1) is now available.
