### ISSUE TITLE
strange error on fedora 38: Processing failed: unable to call pngsave_buffer VipsImage: file has been truncated

### ISSUE THREAD

**Issue by lanyusan** [kleisauke/net-vips#213]
I have a desktop app built with avalonia running well on ubuntu. 

I have got a new PC that is running fedora 38. And I got this error:

Processing failed: unable to call pngsave_buffer
VipsImage: file has been truncated

 ```
    at NetVips.Operation.Call(String operationName, VOption kwargs, Image matchImage, Object[] args)
   at NetVips.Image.PngsaveBuffer(Nullable`1 compression, Nullable`1 interlace, String profile, Nullable`1 filter, Nullable`1 palette, Nullable`1 q, Nullable`1 dither, Nullable`1 bitdepth, Nullable`1 effort, Nullable`1 strip, Double[] background, Nullable`1 pageHeight)
```

This happens when it is processing frames of GIFs and it happens randomly. My app processes frame by frame sequentially but I suspect it is caused by corruption of data during parallel processing by vips. It is just a guess.

lib version:
```
		<PackageReference Include="NetVips" Version="2.3.1" />
		<PackageReference Include="NetVips.Extensions" Version="2.3.0" />
		<PackageReference Include="NetVips.Native" Version="8.14.3" />

```

**Comment by kleisauke** [comment]
@lanyusan Were you able to make any progress with this?

**Comment by lanyusan** [comment]
@kleisauke 

I just decided to still use Ubuntu as workstation OS. All is fine.
I haven't had a chance to investigate it further on Fedora. Feel free to close it. 

Thanks.

**Comment by kleisauke** [comment]
I'll close this issue for now, without a reproduction it'll be hard to debug further.
