### ISSUE TITLE
Advice on lowering memory usage

### ISSUE THREAD

**Issue by Darkle** [kleisauke/net-vips#215]
Hi, I was hoping to get some tips or tricks on lowering memory usage and fixing a possible memory leak in my code.

My F# code here is a simplified version of what I have in my regular code: https://github.com/Darkle/netvips-memtest/blob/main/Program.fs
You should be able to run it with a `dotnet restore` and `dotnet run`

Some notes:
* Using `Parallel.ForEach`, the memory usage goes past 4GB and slowly keeps going up.
* I also tried using `Array.Parallel` in case there was an issue with `Parallel.ForEach`, but the memory keeps rising for that too. 
    * You can try it out by commenting out the `Parallel.ForEach` code and uncommenting out the `Array.Parallel` code.
* I also tried a simple for loop, and while it uses much less memory, the memory does slowly rise.
* Switching from `Enums.Access.Sequential` to `Enums.Access.SequentialUnbuffered` helped a bit to lower the memory usage.
* I'm totally willing to sacrifice speed for lower memory usage. 

Details:
* OS: Debian Linux Bullseye
* .Net version: 7.0.306
* NetVips version: 2.3.1
* NetVips.Native version: 8.14.3

Any advice would be appreciated.
Thanks.

**Comment by Darkle** [comment]
So I was looking through the Go lib for libvips and it has this section: https://github.com/davidbyttow/govips#memory-usage-note
So i tried setting `MALLOC_ARENA_MAX=2` and now I have no more memory leak! 🎉

**Comment by kleisauke** [comment]
I think this is a memory fragmentation issue. You might consider using a different memory allocator such as [jemalloc](https://github.com/jemalloc/jemalloc) to prevent memory fragmentation in long-running, multi-threaded, glibc-based Linux processes. See https://github.com/lovell/sharp/issues/955 to learn more about memory allocation and why the choice of a memory allocator is important.

For the same reason [Redis ships with jemalloc by default since version 2.4](http://oldblog.antirez.com/post/everything-about-redis-24.html).
> Since we introduced the specially encoded data types Redis started suffering from fragmentation. We tried different things to fix the problem, but basically the Linux default allocator in glibc sucks really, really hard. […] Every single case of fragmentation in real world systems was fixed by this change, and also the amount of memory used dropped a bit.

Please see https://github.com/lovell/sharp-libvips/issues/95 for a future possible enhancement that relates to this.

**Comment by kleisauke** [comment]
Alternatively, you could also consider switching to a Alpine-based Docker image, as the memory allocator in musl, upon which Alpine Linux is based, is generally considered very good in terms of lack of fragmentation and returning freed memory.

FWIW, I'm also aware that sharp reduces the default concurrency to 1 when glibc' memory allocator is used, see commit:
https://github.com/lovell/sharp/commit/5a9cc835b33001c805a0d5fcb05e6d71135cc79d

This can be controlled in NetVips with the `VIPS_CONCURRENCY` environment variable or the `NetVips.Concurrency` setter.
https://github.com/kleisauke/net-vips/blob/43c043c7fe694032108e0b3bf885e4c2006c3685/src/NetVips/NetVips.cs#L155-L162

**Comment by Darkle** [comment]
Thanks for the info. 👍

I also tried running my code in an Alpine Linux docker container and that also fixed the issue.

So for anyone reading this thread in the future, and you are also running into memory issues, try the following:
1. Set the env variables: `VIPS_CONCURRENCY=1 MALLOC_ARENA_MAX=2`
2. If the above doesn't work, try running your code in an Alpine Linux docker container
3. If the above doesn't work, try changing the default memory allocator you are using to jemalloc
