### ISSUE TITLE
Read compression type in tif files

### ISSUE THREAD

**Issue by jetic83** [kleisauke/net-vips#216]
Is it possible to read the compression type in TIFF files? ForeignTiffCompression seems to be suited, but I only find how to use it when writing an image.

Background: from a TIFF file, I want to know which compression is used internally.

**Comment by kleisauke** [comment]
libvips does not expose `TIFFTAG_COMPRESSION` in its metadata. libtiff have a tool called `tiffinfo`, I think that would work for you.

**Comment by kleisauke** [comment]
I hope this information helped. Please feel free to re-open if questions remain.
