### ISSUE TITLE
NetVips exiting (crashing?) program when encountering avif encoding bitdepth issue

### ISSUE THREAD

**Issue by Darkle** [kleisauke/net-vips#217]
Hi, I think I am encountering NetVips causing the program to exit silently when it has an issue encoding an avif file.

Here is a basic repro: https://github.com/Darkle/netvips-exit-issue/. You should be able to run it with `dotnet restore && dotnet run`

The program should either print "finished creating avif" on success or "Error in convertToAvif: &lt;error here&gt;" on exception, however it does neither and silently exits.

I searched through the libvips issues and found this: https://github.com/libvips/libvips/issues/3323. I found that setting the bitdepth to 8 does make it convert just fine and "finished creating avif" is printed to the console. 

However I though I should perhaps report the issue of the silent exiting (crashing?). Ideally it should throw an exception in dotnet right?

Details:
* Debian Linux Bullseye
* .Net version: 7.0.306
* NetVips version: 2.3.1
* NetVips.Native version: 8.14.3

**Comment by kleisauke** [comment]
I think this is the same issue as https://github.com/lovell/sharp/issues/3358, i.e. writing a high bit rate AVIF image with the pre-built binaires would cause a segfault. To mitigate this, I recommend enforcing a `bitdepth` of 8 for the time being.

I'll investigate whether we can always enforce a `bitdepth` of 8 in libvips when aom is configured with `-DCONFIG_AV1_HIGHBITDEPTH=0`. Alternatively, and perhaps more promisingly, the future possible enhancement being discussed at https://github.com/lovell/sharp-libvips/issues/97 might reintroduce the capability to write AVIF images with higher bit depths.

**Comment by Darkle** [comment]
Ok, thanks. Since its a segfault I guess there's nothing you can do on the dotnet side to catch/prevent that. I'll stick with setting the bitdepth to 8 when converting to avif.

Thanks.
