### ISSUE TITLE
w3wp.exe process crashing if AppDomain recycles

### ISSUE THREAD

**Issue by victor-mikhalev** [kleisauke/net-vips#218]
ASP.NET 4.8 application with Net-Vips cause application crash.
Steps to reproduce:
1. Start app and use Net-Vips library (ex. generate thumbnail)
2. Recycle AppDomain (rebuild app, deploy, modify web.config etc.)
3. After process recycles you got exception: Attempted to access an unloaded AppDomain. Threads will hang on generating thumbnails.
![image](https://github.com/kleisauke/net-vips/assets/273995/f268215f-4fd0-478f-8ee3-2b250b2dbf76)

Here is sample project to reproduce the issue.
https://github.com/victor-mikhalev/NetVipsCrash

**Comment by kleisauke** [comment]
I could not reproduce this with IIS Express using the provided sample project.

libvips delays thread creation until it needs them, the first thread is only created when the first pixel is processed. Once it starts processing pixels, it sets up the threading system. As far as I know, recycling the AppDomain should be fine after that (see #164), but trying to use `fork()` after that point will probably end in disaster.

As a possible solution, you could try to init and shutdown libvips within ASP.NET's `Application_Start` and `Application_End` lifecycle functions, for example:
`Global.asax`:
```asp
<%@ Application CodeFile="Global.asax.cs" Inherits="NetVipsCrash.MyApplication" Language="C#" %>
```

`Global.asax.cs`:
```cs
namespace NetVipsCrash
{
    using System;
    using System.Web;
    using NetVips;

    public partial class MyApplication : HttpApplication
    {
        void Application_Start(object sender, EventArgs e)
        {
            NetVips.Init();
        }

        void Application_End(object sender, EventArgs e)
        {
            NetVips.Shutdown();
        }
    }
}
```

However, I'm not sure if this will work.

**Comment by kleisauke** [comment]
@victor-mikhalev Were you able to make any progress with this?

**Comment by victor-mikhalev** [comment]
> @victor-mikhalev Were you able to make any progress with this?

I have tried your workaround, but it does not help. 
I solved the issue by moving NetVips to microservice on .NET Core.
