### ISSUE TITLE
Upgrading Native.win-x64 from 8.12.1 to 8.14.4 breaks openslide

### ISSUE THREAD

**Issue by j-hudecek** [kleisauke/net-vips#219]
Hi, I'm using NetVips with openslide and when I update the NetVips.Native.win-x64 to 8.14.4 openslide fails to load with error:

    System.DllNotFoundException: Unable to load DLL 'libopenslide-0.dll' or one of its dependencies: The specified procedure could not be found. (0x8007007F)

I've checked the dependency walker but it didn't report any problems (of course because nothing else changed in the system and dependency walker doesn't look into the runtimes folder), so I checked the contents of the debug folders before and after the upgrade and narrowed it down to `runtimes\win-x64\native\libglib-2.0-0.dll` which went from version 2.70.1 to 2.77.1 (and it lost some 300KB in the process). If I copy the old library over, it runs, with the new one it doesn't. 

Can you double check what's going on? Is that the right build? It seems it's missing something that libopenslide (3.4.1) or one of its dependencies needs.

**Comment by kleisauke** [comment]
Hello, did you see #18? If you want to use the `-all` distribution (as available on https://github.com/libvips/build-win64-mxe), you'll need to remove the `NetVips.Native` package to avoid any DLL conflicts.

**Comment by j-hudecek** [comment]
Hi, thanks for taking a look. The strange thing is that this setup worked for 8.12.1 of the Native.win-x64 and it only broke after update while being unsupported. Why does copying the older glib over the new one fix it? Anyway, I'll just stick to 8.12.1 for win and update only the Native.linux-x64.
