### ISSUE TITLE
Possibility for adding a strong name to this library

### ISSUE THREAD

**Issue by kl1234567891** [kleisauke/net-vips#220]
Hello, is it possible to add a strong name to this library? I am currently using .NET Framework 4.8 and had some issues when using this library as it does not have a strong name.

To resolve this I have modified the library and added a strong name using my own `.snk` file. However it will be beneficial to add a strong name to this library so any .NET Framework users requiring a strong name can use this library without any modifications.

Thanks!

**Comment by kleisauke** [comment]
There are no plans to strong name the various NuGet packages, given it's mostly a relic from the older .NET days:
https://github.com/dotnet/runtime/blob/764d3e0cfab629bb6e594f3399c9ba7362a621c3/docs/project/strong-name-signing.md#1-microsoft-strong-names-their-assemblies-should-i

Moreover, moving from not-strong-names to strong-names would require a major version bump, which is unlikely to happen soon.
