### ISSUE TITLE
How to resize 1bit tiff and save with 1bit

### ISSUE THREAD

**Issue by webtec-lab** [kleisauke/net-vips#222]
Hi,
I need to resize big size tiff of 1 bit per sample and then save it without changing bit per sample.
Can you show me the sample code? I can not find it in Documentation.

Here is my code:
            NetVips.Image image = NetVips.Image.Tiffload(@"D:\WORK\1bit.tif");
            image.Resize(0.5, NetVips.Enums.Kernel.Nearest);
            image.Tiffsave(@"d:\123.tif", NetVips.Enums.ForeignTiffCompression.Ccittfax4);

It seems that width and height have no changes after image.Resize
and  image.Tiffsave with Ccittfax4 has a problem of bits per sample. (8bits ?)
      
Thanks.

**Comment by kleisauke** [comment]
Hi @webtec-lab,

You can use the `bitdepth` parameter of [`Tiffsave`](https://kleisauke.github.io/net-vips/api/NetVips.Image.html#NetVips_Image_Tiffsave_) to write as a 1, 2, 4 or 8 bit image. For example:
```csharp
Image image = Image.Tiffload("8bit.tif", access: Enums.Access.Sequential);
image.Tiffsave("squash.tif", bitdepth: 1);
```

> It seems that width and height have no changes after image.Resize

The [`Image`](https://kleisauke.github.io/net-vips/api/NetVips.Image.html) class is immutable, so most methods are functions that return a new image.
```diff
@@ -1,3 +1,3 @@
 NetVips.Image image = NetVips.Image.Tiffload(@"D:\WORK\1bit.tif");
-image.Resize(0.5, NetVips.Enums.Kernel.Nearest);
+image = image.Resize(0.5, NetVips.Enums.Kernel.Nearest);
 image.Tiffsave(@"d:\123.tif", NetVips.Enums.ForeignTiffCompression.Ccittfax4);
```

**Comment by webtec-lab** [comment]
Great. It works! 
Thank you.
