### ISSUE TITLE
Calling image.WriteToBuffer in parallel with a shared VOption leads to exception (solution included)

### ISSUE THREAD

**Issue by korkmazad** [kleisauke/net-vips#228]
When we call image.WriteToBuffer with a shared VOption, we receive an error:

Problematic:(Run in parallel)
```
var option = new VOption() { { "Q", JpegQuality } };
using var thumb = image.ThumbnailImage(250);
var thumbData = thumb.WriteToBuffer(".jpg", option);
thumb.Close();
```

Works:
```
using var thumb = image.ThumbnailImage(250);
var thumbData = thumb.WriteToBuffer(".jpg", new VOption() { { "Q", JpegQuality } });
thumb.Close();
```

Message:
```
at System.ThrowHelper.ThrowAddingDuplicateWithKeyArgumentException[T](T key)
   at System.Collections.Generic.Dictionary`2.TryInsert(TKey key, TValue value, InsertionBehavior behavior)
   at NetVips.ExtensionMethods.Merge(VOption self, VOption merge)
   at NetVips.Image.WriteToBuffer(String formatString, VOption kwargs)
```

So the cause and the possible fixes:

1. `Image.WriteToBuffer` calls `kwargs.Merge` with the `stringOptions`
2. `ExtensionMethods.Merge` calls `VOption[key] = value;`
3. This calls VOption's `this[string key]`'s `set `method:
```
{
    get => _internalDictionary[key];
    set => Add(key, value);
}
```
4. Which then calls this:
`        public void Add(string key, object value) => _internalDictionary.Add(key, value);
`
The problem with dictionary.Add is, non-repeatability. 
We use a workaround in our code now while calling.

But in the code there are 2 easy solution options:
1. Change VOption.Add to `Add(string key, object value) => _internalDictionary[key] = value;`
2. Add a new method called `Set(string key, object value) => _internalDictionary[key] = value;`
and call it from `set => Set(key, value);`

**Comment by kleisauke** [comment]
Commit 7b723e3d9b23cc5b35932ddc2671058fadfcf6e6 should fix this. Thanks for reporting this!
 
If you want to test this, you can use the nightly version of NetVips. Add the `https://ci.appveyor.com/nuget/net-vips` feed in the `<packageSources>` section of your `NuGet.config`:
```xml
<packageSources>
  <add key="netvips-nightly" value="https://ci.appveyor.com/nuget/net-vips" />
</packageSources>
```

And update NetVips to 2.4.0 (build number 527 - prerelease). I'll make a new release soon.

**Comment by kleisauke** [comment]
[NetVips v2.4.1](https://www.nuget.org/packages/NetVips/2.4.1) is now available.
