### ISSUE TITLE
load_buffer not found

### ISSUE THREAD

**Issue by ksnagaraj** [kleisauke/net-vips#229]
I am using Netvips Image.PdfloadBuffer. I have installed latest netvips native 8.15.1 version. But its throwing an error.
Used in windows 11, .net core version 8. 
If i install libvips in windows and set the environment path it will work. But in aws lambda its not posible to install directly.
Some options i followed which found in google like aws lambda layer and build libvips source nothing worked.
Same error i am getting load_buffer not found.
If netvips native supports lambda linux it will be great.

**Comment by kleisauke** [comment]
Hello, did you see https://github.com/kleisauke/net-vips/issues/11#issuecomment-402438726 ?

**Comment by ksnagaraj** [comment]
Thanks, I will try this.
