### ISSUE TITLE
Dzsave png image with background

### ISSUE THREAD

**Issue by gjactat** [kleisauke/net-vips#230]
Hello,

I'm trying to generate tiles for a png transparent image. As the image essentially display dark objetcs, I'd like to change the background color of the rendering.

I've seen that the "Dzsave" method has a "background" parameter but it seems to be ignored in the following code :

```
using (var source = NetVips.Image.Pngload(InputFilePath))
   source.Dzsave(DzPath, suffix:".jpg[Q=80]", background: new double[] { 255, 255, 0 });
```
The generated tiles have a black background. The same "background" parameter indeed produce a yellow background with the "JpegSave" method though.
Maybe I'm doing something wrong ?

Thanks for your attention (and for your amazing work !)

**Comment by gjactat** [comment]
Until we know more about the ability of the "Dzsave" method to handle a background, I've implemented the following workaround (inspired by [this comment from Klaus](https://github.com/kleisauke/net-vips/issues/77#issuecomment-625275715)):

```
            using (var img = Image.Pngload(InputFilePath))
            using (var background = img.NewFromImage(new double[] { 200, 0, 250 }))
            using (var composite = background.Composite(img, Enums.BlendMode.Over))
                composite.Dzsave(DzPath);
```
I imagine this may represent a slight additional cost in terms of memory consumption, since a background image of the same size as the image to be tiled must be generated.

**Comment by kleisauke** [comment]
The `background` argument of `image.Dzsave` / [`vips_dzsave()`](https://www.libvips.org/API/current/VipsForeignSave.html#vips-dzsave) is only used for the expanded edge tiles in Google layout mode. You can use the `suffix` argument to pass options to the underlying saver.
```csharp
using var image = Image.Black(1000, 1000, bands: 4);
image.Dzsave("image-pyramid", suffix: ".jpg[Q=80,background=255 255 0]");
```

**Comment by gjactat** [comment]
My bad ! I hadn't thought of passing the background color in the arguments.
Thanks again for your great work @kleisauke.
