### ISSUE TITLE
[Question] How to add Contour

### ISSUE THREAD

**Issue by 1923trk** [kleisauke/net-vips#232]
Hello, Thank you for the library.
I have png images with alpha channels. I want to add contours to these images and get a result like the examples I will share below, but I couldn't find how to do it. Additionally I should be able to control the background color.
![54](https://github.com/kleisauke/net-vips/assets/172930587/db260337-be94-4e5d-90d5-5bed5cebdd19)
![24061513YKHV-01cqkdy8yiiputopi8le3xut](https://github.com/kleisauke/net-vips/assets/172930587/83f391d7-bfd7-4246-9453-89e29c4bce5d)
![169](https://github.com/kleisauke/net-vips/assets/172930587/77d32b28-24c6-47c9-9687-e9b82f3d3319)
![24061513YKGS-t7qy707avbs1bx3p82webwwq](https://github.com/kleisauke/net-vips/assets/172930587/816d2eba-2342-4835-898c-e73e8601150a)

**Comment by kleisauke** [comment]
Cross-posted at https://github.com/libvips/libvips/discussions/4011 which is probably the right place for this, so will close.
