### ISSUE TITLE
pngload_source: IDAT stream error when using sourceImage.ThumbnailImage()

### ISSUE THREAD

**Issue by majora2007** [kleisauke/net-vips#234]
I switched up some of my code that creates a thumbnail, to instead first create an Image from `Image.NewFromStream(stream)` so that I can get some width/height to identify how to scale the image beforehand. However, after this, some images are now throwing an exception:
```
NetVips.VipsException: unable to call VipsForeignSaveSpngFile
pngload_source: IDAT stream error
```

I can't find much information about this error nor do I see anything wrong with the code. It works for most images (but not from PDF streams). 

The only thing that MIGHT be the issue is that this stream I'm using is a RecyclableMemoryStream, whereas my other image flows that pass through this code use Streams from archives or raw images. 

Any insight is appreciated. 

NetVips: 2.4.1
NetVips.Native: 8.15.2

Here's the code:
```
public string WriteCoverThumbnail(Stream stream, string fileName, string outputDirectory, EncodeFormat encodeFormat, CoverImageSize size = CoverImageSize.Default)
    {
        var (targetWidth, targetHeight) = size.GetDimensions();
        if (stream.CanSeek) stream.Position = 0;
        using var sourceImage = Image.NewFromStream(stream);
        if (stream.CanSeek) stream.Position = 0;

        using var thumbnail = sourceImage.ThumbnailImage(targetWidth, targetHeight,
            size: GetSizeForDimensions(sourceImage, targetWidth, targetHeight),
            crop: GetCropForDimensions(sourceImage, targetWidth, targetHeight));

        var filename = fileName + encodeFormat.GetExtension();
        _directoryService.ExistOrCreate(outputDirectory);
        try
        {
            _directoryService.FileSystem.File.Delete(_directoryService.FileSystem.Path.Join(outputDirectory, filename));
        } catch (Exception) {/* Swallow exception */}

        thumbnail.WriteToFile(_directoryService.FileSystem.Path.Join(outputDirectory, filename));
        return filename;
    }
    public static Enums.Size GetSizeForDimensions(Image image, int targetWidth, int targetHeight)
    {
        try
        {
            if (WillScaleWell(image, targetWidth, targetHeight) || IsLikelyWideImage(image.Width, image.Height))
            {
                return Enums.Size.Force;
            }
        }
        catch (Exception)
        {
            /* Swallow */
        }

        return Enums.Size.Both;
    }

    public static Enums.Interesting? GetCropForDimensions(Image image, int targetWidth, int targetHeight)
    {
        try
        {
            if (WillScaleWell(image, targetWidth, targetHeight) || IsLikelyWideImage(image.Width, image.Height))
            {
                return null;
            }
        } catch (Exception)
        {
            /* Swallow */
            return null;
        }

        return Enums.Interesting.Attention;
    }
```

**Comment by kleisauke** [comment]
Are you able to provide a complete, standalone code sample that allows someone else to reproduce this issue?

Note that I'd avoid `ThumbnailImage`, if possible. It can't do any of the shrink-on-load tricks, so it's much, much slower.

**Comment by majora2007** [comment]
Just threw something up, but having trouble reproducing, so will need to augment with RecycleMemoryStream. 

Instead of ThumbnailImage, what would you recommend instead?

**Comment by kleisauke** [comment]
> Instead of ThumbnailImage, what would you recommend instead?

I recommend using the static `Image.Thumbnail*` functions, which accept a file, stream, or buffer as input, see:
https://github.com/kleisauke/net-vips/issues/97#issuecomment-1646551267

Additionally, you can combine these functions with the various `Image.NewFrom*` functions to determine the necessary scale. Since libvips operates lazily, it only reads the image header. Any pixel decoding occurs much later, only when the pixel values are actually needed.

**Comment by majora2007** [comment]
Here you go. It wasn't the memory stream at all. 

[NetVipsPngLoadIssue.zip](https://github.com/user-attachments/files/16116050/NetVipsPngLoadIssue.zip)

Let me try and refactor my code. I had no idea I was doing it poorly this whole time.

**Comment by jcupitt** [comment]
Hello @majora2007 and @kleisauke,

Yes, seeking a stream behind libvips's back will cause terrible problems. I think most loaders will break if you do this, won't they? 

I'm not sure I understand the use case here. Why do you need to seek a stream that libvips is still reading from?

*nix lets you do eg.:

```C
int new_fd = dup(fd);
VipsImage *image = vips_image_new_from_fd(new_fd);
```

Now the file descriptor is private to libvips, has its own read position, and no one can change it. Does C# let you dup streams? Maybe something like that could help?

**Comment by majora2007** [comment]
I actually didn't need to rewind the stream after the fact, I coded that as a safety precaution, as I've hit this type of error many times with streams. I have updated my code with Kleis' suggestion and will be testing this week to confirm that removing the rewinding works.

**Comment by majora2007** [comment]
I actually didn't need to rewind the stream after the fact, I coded that as a safety precaution, as I've hit this type of error many times with streams. I have updated my code with Kleis' suggestion and it worked fine. Thanks again for the support and this great library.
