### ISSUE TITLE
Image.SignalConnect(Enums.Signals signal, EvalDelegate callback, IntPtr data = default) reporting incorrect progress on WSL Linux

### ISSUE THREAD

**Issue by pborovina** [kleisauke/net-vips#237]
Calling the `Image.SignalConnect(Enums.Signals signal, EvalDelegate callback, IntPtr data = default)` method is producing incorrect results when run under Linux (Ubuntu 24.04 using Windows Subsystem for Linux). For example:
```csharp
public static void Test()
{
    using var image = Image.Black(1000, 1000, 3);

    void EvalHandler(Image img, VipsProgress p)
    {
        Console.Log($"NPels: {p.NPels}, TPels: {p.TPels}, Percent: {p.Percent}");
    }

    image.SetProgress(true);
    image.SignalConnect(Enums.Signals.Eval, EvalHandler);
    image.WriteToFile("test.jpg");
}
```
produces the following output when run on WSL (version 2.3.21) :
```
NPels: 7, TPels: 0, Percent: 1073741826
NPels: 7, TPels: 0, Percent: 1073741826
NPels: 7, TPels: 0, Percent: 1073741826
NPels: 7, TPels: 0, Percent: 1073741826
NPels: 7, TPels: 0, Percent: 1073741826
NPels: 7, TPels: 0, Percent: 1073741826
NPels: 7, TPels: 0, Percent: 1073741826
NPels: 7, TPels: 0, Percent: 1073741826
NPels: 7, TPels: 0, Percent: 1073741826
NPels: 7, TPels: 0, Percent: 1073741826
```
The eval delegate looks be be called the correct number of times, but the `VipsProgress` struct fields are incorrect. Changing the above test to:
```csharp
public delegate void EvalSignalDelegate(IntPtr imagePtr, IntPtr progressPtr, IntPtr userDataPtr);

public static void Test()
{
    using var image = Image.Black(1000, 1000, 3);

    void EvalDelegate(IntPtr imagePtr, IntPtr progressPtr, IntPtr userDataPtr)
    {
        if (progressPtr == IntPtr.Zero) return;
        var p = Marshal.PtrToStructure<VipsProgress>(progressPtr);
        Console.Log($"NPels: {p.NPels}, TPels: {p.TPels}, Percent: {p.Percent}");
    }

    image.SetProgress(true);
    image.SignalConnect<EvalSignalDelegate>("eval", EvalDelegate, IntPtr.Zero);
    image.WriteToFile("test.jpg");
}
```
results in the expected output. Strangely, it seems that the `VipsProgress` struct is not being marshalled correctly within the `NetVips` implementation? Note that both examples above ran as expected on Windows. Using `NetVips version 2.3.1` and `NetVips.Native version 8.14.3`

**Comment by kleisauke** [comment]
I think this was fixed with commit https://github.com/kleisauke/net-vips/commit/839c22a7a9eacf43983003121bc50c5f692b4fbb.

If you want to test this, you can use the nightly version of NetVips. Add the `https://ci.appveyor.com/nuget/net-vips` feed in the `<packageSources>` section of your `NuGet.config`:
```xml
<packageSources>
  <add key="netvips-nightly" value="https://ci.appveyor.com/nuget/net-vips" />
</packageSources>
```

And update NetVips to 2.4.1 (build number 579 - prerelease).

**Comment by pborovina** [comment]
Thank you, I'll try it out!

**Comment by pborovina** [comment]
Just tested it out and it works as expected.

**Comment by kleisauke** [comment]
[NetVips v2.4.2](https://www.nuget.org/packages/NetVips/2.4.2) is now available.
