### ISSUE TITLE
Sharpen the image using Linear filter 

### ISSUE THREAD

**Issue by vinaymuthanna0727** [kleisauke/net-vips#24]
Hi ,

I need to create sharpen image using linear filter.
I found the net-vips will create sharpen image using gaussian filter and i found this code in net vibs

/// <param name="sigma">Sigma of Gaussian</param>
        /// <param name="x1">Flat/jaggy threshold</param>
        /// <param name="y2">Maximum brightening</param>
        /// <param name="y3">Maximum darkening</param>
        /// <param name="m1">Slope for flat areas</param>
        /// <param name="m2">Slope for jaggy areas</param>
        /// <returns>A new <see cref="Image"/></returns>

**The Problem statement is** 

Input i am getting for sharpen (image processing) of linear filter and its parameter are 
**Kernal Size : 5 and Strength:10 .**

**Kernel Size:** Here, you adjust the filter kernel size. The filter kernel size indicates how many neighboring pixels from the source image are included in the calculation of a pixel in the filtered image.

**Strength:** Here, you set the weighting of the filter kernel. The higher the weighting, the better the contrast of the filtered image. However, an excessive weighting can lead to interfering effects, such as noise.

Using the above input need to create sharpen image using ney-vips library

can i use this net-vips library to create sharpen image 

public Image Sharpen(double? sigma = default(double? ), double? x1 = default(double? ), double? y2 = default(double? ), double? y3 = default(double? ), double? m1 = default(double? ), double? m2 = default(double? ))

If Yes .How can i map or convert kernal and Strength inputs to above net-vips sharpen .
Is gaussian filter and Linear filter are same algorithm ?

How can i implement this ?

Thanks 
Vinay

**Comment by kleisauke** [comment]
Answered here: https://github.com/lovell/sharp/issues/1500#issuecomment-450027326.
