### ISSUE TITLE
License of the nuget package

### ISSUE THREAD

**Issue by Leftyx** [kleisauke/net-vips#241]
Hi, I can see this software is licensed under  an MIT license but libvips has a [LGPL-2.1-or-later](https://spdx.org/licenses/LGPL-2.1-or-later) license.

Since I am planning to use your NuGet package in a non opensource commercial product, I was wondering if I am complying with the law.

Thanks.

**Comment by kleisauke** [comment]
* NetVips is made available under the terms of the MIT licence.
* libvips is made available under the terms of the LGPLv2 or any later version.
* The `NetVips.Native*` packages uses prebuilt libvips as a shared library under the terms of the LGPLv3.
* The prebuilt libvips uses various other libraries as static dependencies under [various other terms](https://github.com/kleisauke/libvips-packaging/blob/main/THIRD-PARTY-NOTICES.md) all of which are compatible with LGPLv3.

If you are using NetVips then you must comply with the terms of the MIT licence.

As a result of this question, I've clarified the licence of the `NetVips.Native*` packages with commit 8d0bfd5ac14e7b997f2659905b7ef94a97204ebb.
