### ISSUE TITLE
Could this be used to generate image tiles like gdal2mbtiles?

### ISSUE THREAD

**Issue by donnyv** [kleisauke/net-vips#242]
gdal2mbtiles is a python tool that uses vips to cut up and process large aerial images into smaller pyramid tiles. 
https://github.com/ecometrica/gdal2mbtiles 

I would love to use net-vips to build my own version of gdal2mbtile using C#. I saw the sample you have called ImagePyramid.cs. Was wondering if this would be a good starting point for my project.

Thanks

**Comment by kleisauke** [comment]
This seems possible and relatively straightforward, as gdal2mbtiles uses pyvips, which has an API similar to the .NET binding. Additionally, https://github.com/Gigas002/GTiff2Tiles could also serve as a reference.
