### ISSUE TITLE
Reading complete tiff image for RGB values

### ISSUE THREAD

**Issue by Jey1980** [kleisauke/net-vips#28]
I am using below code to get RGB values of the image for further processing, and it takes so much time, is there any other way to read RGB values?

NetVips.Image image = NetVips.Image.Tiffload(@inputFilePath, access: Enums.Access.Random);

            for (y = 0; y < tile.Height; y++)
            {
                for (x = 0; x < tile.Width; x++)
                {
                        double[] db = tile.Getpoint(x, y);
                }
           }

**Comment by kleisauke** [comment]
You can use [`WriteToMemory()`](https://kleisauke.github.io/net-vips/api/NetVips.Image.html#NetVips_Image_WriteToMemory). For example, if you have a 3x3 uchar image containing the bytes 1 to 9, read left-to-right, top-to-bottom:
```csharp
Image im = Image.NewFromMemory(new byte[,]
{
	{1, 2, 3},
	{4, 5, 6},
	{7, 8, 9}
}, 3, 3, 1, "uchar");
```

Then:
```csharp
// t equals to new byte[] {1, 2, 3, 4, 5, 6, 7, 8, 9};
byte[] t = im.WriteToMemory();
```

will return a nine byte buffer containing the values 1, 2, 3, 4, 5, 6, 7, 8, 9.

**Comment by Jey1980** [comment]
Thanks for your quick response. Another question related to WritetoMemory()

is there anyway to read will return a nine byte buffer containing the values 1, 4, 7, 2, 5, 8, 3, 6, 9. like write to memory vertically instead of horizontally?

**Comment by kleisauke** [comment]
You could rotate the image 270 degrees clockwise and flip it vertically before `WriteToMemory()`. For example:

```csharp
Image im = Image.NewFromMemory(new byte[,]
{
    {1, 2, 3},
    {4, 5, 6},
    {7, 8, 9}
}, 3, 3, 1, "uchar");

im = im.Rot270().FlipVer();

// t equals to new byte[] {1, 4, 7, 2, 5, 8, 3, 6, 9};
byte[] t = im.WriteToMemory();
```

**Comment by Jey1980** [comment]
Thanks a lot for your timely help, It worked well...  Right now I am testing with 57000*10000=57,00,00,000 and if we have 90000*70000, reading is taking lot of time and which may hit .NET restriction. I am not sure how to handle this kind of large image.

**Comment by kleisauke** [comment]
Does your subsequent processor support JPEG buffers? If so, you could use [`im.WriteToBuffer(".jpg")`](https://kleisauke.github.io/net-vips/api/NetVips.Image.html#NetVips_Image_WriteToBuffer_) to write the image to a JPEG memory buffer:
```csharp
Image im = Image.NewFromFile("x.jpg");

// Do your transformations here

// Write the image to a formatted JPEG memory buffer.
byte[] t = im.WriteToBuffer(".jpg");
```

If your subsequent processor support file input, you could use:
```csharp
Image im = Image.NewFromFile("x.jpg");

// Do your transformations here

// Write the image to a file on disc.
im.WriteToFile("output.jpg");
```

**Comment by kleisauke** [comment]
Hope this helped, please feel free to re-open if questions remain.
