### ISSUE TITLE
How to make multi band image to Greyscale image?

### ISSUE THREAD

**Issue by Jey1980** [kleisauke/net-vips#30]
Hi Team,

      When we use bitmap.WriteToMemory() and if that has multi-band and it each band data is written as separate image and it cause issue when I use the byte array values. is is possible to make multi-band image as Greyscale image? I hope there will be some solution for the same.

Many thanks in advance.

Regards
JK

**Comment by Jey1980** [comment]
rephrased

**Comment by Jey1980** [comment]
Thanks Buddy, it worked
One more quick query
if we just take first band image[0], I hope we will not lose any data in the image right?

**Comment by kleisauke** [comment]
Hope this helped, please feel free to re-open if questions remain.
