### ISSUE TITLE
BadImageException

### ISSUE THREAD

**Issue by martinweihrauch** [kleisauke/net-vips#32]
Just having the first tries with your wrapper, but I keep getting an exception, which I dont understand. I am trying to open Jpegs, Tiff, etc, but this error pops up (below) for this code:

Microsoft.Win32.OpenFileDialog openFileDlg = new Microsoft.Win32.OpenFileDialog();
            openFileDlg.RestoreDirectory = true;

            bool? result = openFileDlg.ShowDialog();
            if (result == true)
            {

                var image = NetVips.Image.NewFromFile(openFileDlg.FileName);

![grafik](https://user-images.githubusercontent.com/2306324/54905661-e0f0db00-4ee1-11e9-9f20-eefa8ca272d6.png)

**Comment by kleisauke** [comment]
The `BadImageFormatException` is thrown when a 32-bit / 64-bit conflict occurs. For example, in a 64-bit OS, an assembly built for `AnyCPU` or `x64` will throw this exception when trying to load the pre-compiled libvips binary for 32-bit.

If you're running on a 64-bit OS, make sure that you'll compile your DLL as 64-bit. When you target the `AnyCPU` platform, make sure that the `Prefer 32-bit` option is unchecked (or try targeting `x64` instead).

**Comment by kleisauke** [comment]
Hope this helped, please feel free to re-open if questions remain.
