### ISSUE TITLE
Benchmarks and commentary

### ISSUE THREAD

**Issue by JimBobSquarePants** [kleisauke/net-vips#34]
> Loads a large tiff image, shrinks by 10%, sharpens, and saves again. On this test NetVips is around 15 times faster than Magick.NET and 6 times faster than ImageSharp.

ImageSharp doesn't support Tiff but you know this already.

I'm curious about the sharpening phase of the test.  Passing `.75F` to the ImageSharp `GaussianSharpen` algorithm will create a kernel with a radius of 3. Does net-vips adjust the dimensions of the input kernel to match that radius when dividing by 8?

https://github.com/kleisauke/net-vips/blob/0da155bba0c9cdd981a9bf5f4ddeb50e4b1bd011/tests/NetVips.Benchmarks/Benchmark.cs#L44

https://github.com/kleisauke/net-vips/blob/0da155bba0c9cdd981a9bf5f4ddeb50e4b1bd011/tests/NetVips.Benchmarks/Benchmark.cs#L83

The resize phase definitely differs. Both ImageSharp and Skia are using sampling algorithms that sample more surrounding pixels than the linear sampler used in the net-vips code. I cannot comment on Magick.NET implementation as I do not know the internals.

https://github.com/kleisauke/net-vips/blob/0da155bba0c9cdd981a9bf5f4ddeb50e4b1bd011/tests/NetVips.Benchmarks/Benchmark.cs#L43

I absolutely love a bit of healthy competition and it's really nice to see others interested in the space.

**Comment by kleisauke** [comment]
Hi @JimBobSquarePants,

> ImageSharp doesn't support Tiff but you know this already.

Indeed, I've rephrased that sentence with 3769dd7.

> I'm curious about the sharpening phase of the test. Passing `.75F` to the ImageSharp `GaussianSharpen` algorithm will create a kernel with a radius of 3. Does net-vips adjust the dimensions of the input kernel to match that radius when dividing by 8?

It'll adjust the dimensions. NetVips uses the same test scenario as the official libvips benchmarks. On the official benchmarks I saw that @jcupitt uses a sigma of 75% on [the GD benchmark](https://github.com/libvips/vips-bench/blob/46f949f9c15a144a8807fcadeccc31326d4575c3/gd.c#L52), so I assume that's right.

> The resize phase definitely differs. Both ImageSharp and Skia are using sampling algorithms that sample more surrounding pixels than the linear sampler used in the net-vips code. I cannot comment on Magick.NET implementation as I do not know the internals.

You're right, I switched all benchmarks to bilinear interpolation with b2cb3c0.

> I absolutely love a bit of healthy competition and it's really nice to see others interested in the space.

👍

**Comment by JimBobSquarePants** [comment]
Great stuff!

Yeah I think that test input value is going to yield a different result.

The ImageSharp Gaussian Sharpen algorithm takes advantage of the separable nature of the convolution kernels running an optimized two pass approach. A sigma of .75F will yield the following 7x1 array. We calculate the optimal radius of the kernel based on the information found [here](http://chemaguerra.com/gaussian-filter-radius/)

```
[-0.000178435046, 
-0.0151942009, 
-0.218673661, 
1.46809256, 
-0.218673661, 
-0.0151942009, 
-0.000178435046]
```

So for an accurate comparison you would need a 7x7 input kernel

**Comment by kleisauke** [comment]
Isn't it a good idea to have a `Convolve` operation in ImageSharp? I saw that there was a [`ConvolutionProcessor{TPixel}.cs`](https://github.com/SixLabors/ImageSharp/blob/b6883c1a978f67eeaecf6c6dfd7bec952232ceb7/src/ImageSharp/Processing/Processors/Convolution/ConvolutionProcessor%7BTPixel%7D.cs) but unfortunately it is not available in the public API.

In the meantime, I've used that internal processor to correctly define the 3x3 kernel  . See commit cebb3af.

**Comment by JimBobSquarePants** [comment]
It is a good idea, we've just not done so yet because we had to standardize a way to deal with alpha channel handling during convolution. Blur for example, requires preservation while edge detection does not. I want to make sure the API is just right before making them public. 

You're changes look good for now. The bulk of the performance difference will now be in our jpeg decoder where we don't have the tools yet to bring is closer to speed.

**Comment by kleisauke** [comment]
OK, I've merged the updated and improved benchmarks to master. Let me know if there's convolve operation available (or if I need to update the benchmarks).

I think we're done for now, I'll close this issue.

**Comment by jcupitt** [comment]
This is an nice thread, thank you both for the interesting discussion.

On speed, the libvips binary is usually built with dcommander's fantastic libjpeg-turbo, which is typically 3x faster than the regular IJG libjpeg. This could explain a large part of the difference, as you say @JimBobSquarePants.

libvips is able to run the decompress and compress operations at the same time, so it gets a factor of two on compress/decompress speed there.

libvips does run-time code generation for convolution: it looks at the convolution mask and the image, and writes a short mmx/sse/neon/etc. program, depending on the host CPU, to compute the result. 

It does the same thing for the vertical part of resize, though not the horizontal, unfortunately. From memory, excluding jpg decompress/recompress, about 60% of libvips runtime on this test is in these two or three lines of unvectorised code :(

**Comment by kleisauke** [comment]
@jcupitt I remember a comment from you that you posted a while ago: https://github.com/libvips/libvips/pull/816#issuecomment-346899199. Can libjpeg-turbo's RGBX mode help vectorize `reduceh` / `shrinkh`?

**Comment by JimBobSquarePants** [comment]
> libvips is able to run the decompress and compress operations at the same time, so it gets a factor of two on compress/decompress speed there.

@jcupitt You're a wizard.

**Comment by jcupitt** [comment]
@kleisauke Oh, I'd completely forgotten that. Yes, it would be an interesting experiment. 

@JimBobSquarePants that just happens automatically with demand-driven processing, no wizardry heh.
