### ISSUE TITLE
Using MozJpeg options

### ISSUE THREAD

**Issue by generatives** [kleisauke/net-vips#35]
Hi! I am experimenting with NetVips to do cropping, scaling, and high compression progressive JPEG encoding for a web application. I am trying to use JpegsaveBuffer with all the options that reduce file size

`var bytes = image.JpegsaveBuffer(q: quality, optimizeCoding: true, interlace: true, trellisQuant: true, overshootDeringing: true, optimizeScans: true);`

When I run this I get the following output.

(NetVips:21948): VIPS-WARNING **: 10:29:07.489: ignoring trellis_quant

(NetVips:21948): VIPS-WARNING **: 10:29:07.490: ignoring overshoot_deringing

(NetVips:21948): VIPS-WARNING **: 10:29:07.491: ignoring optimize_scans

I am using NetVips v1.0.7 and NetVips.Native.win-x64 v8.7.4. I tried replacing the libjpeg file with a build of mozjpeg v3.2 as provided by [this project](https://github.com/JosePineiro/MozJpeg-wrapper) but it did not help.

My highest priority is file size so being able to use these options is important. Any advice?

Thank you!

**Comment by kleisauke** [comment]
I just added support for MozJPEG in the Windows build repo of libvips (commit https://github.com/libvips/build-win64-mxe/commit/62bdc7cd4109bf08d5b7d7d81ad171fc9d1bbff3). The binaries can be download [here](https://github.com/libvips/build-win64-mxe/issues/8#issuecomment-500236157).

See https://github.com/kleisauke/net-vips/issues/26#issuecomment-492360629 for the reason why I do not intend to switch the pre-compiled binaries on NuGet to MozJPEG.

**Comment by generatives** [comment]
Thank you, that looks like it is working.

**Comment by kleisauke** [comment]
[NetVips.Native v8.10.6](https://www.nuget.org/packages/NetVips.Native/8.10.6) is now available with prebuilt binaries containing MozJPEG instead of libjpeg-turbo.

Note that libvips resets to libjpeg-turbo's `JCP_FASTEST` defaults so this can be considered a "no-op" unless MozJPEG features are explicitly set.
