### ISSUE TITLE
Join RGB channels into image

### ISSUE THREAD

**Issue by ptrsuder** [kleisauke/net-vips#36]
Using NetVips 1.0.7 with NetVips.Native 8.7.4.

`image = imageR.Bandjoin(imageG).Bandjoin(imageB)`

Resulted image Interpretation is 'b-w'. The only way for me to write correct image to file is to use Tiffsave(). Both Pngsave() and Webpsave() results in imageR as r,g and b channels and imageG, imageB as transparency.  Am I doing something wrong here?
Also, is there a way to save tiff with 4th band as separate alpha channel, not as transparency?

**Comment by kleisauke** [comment]
Are you trying to bandwise join constants or images?

For constants, try to tag the image as `srgb` and cast the pixels to `uchar`. Like this:
```csharp
var black = Image.Black(100, 100);

var green = black.Bandjoin(new int[] {255, 0});

// Alternative way (needs NetVips >= 1.1.0-rc2):
// var green = black.Bandjoin(255, 0);
// Or just:
// var pixel = Image.Black(1, 1) + new [] {0, 255, 0};
// var green = pixel.Embed(0, 0, 100, 100, extend: "copy");

// tag as srgb and cast pixels to uint8 (unsigned char)
green = green.Copy(interpretation: "srgb").Cast("uchar");

green.WriteToFile("green.png");
```

For images, use `[]` to pull out the band element that's needed to join bandwise:
```csharp
var red = Image.NewFromFile("red.png", access: "sequential");
var green = Image.NewFromFile("green.png", access: "sequential");
var blue = Image.NewFromFile("blue.png", access: "sequential");

// take the red band from the first image, green band from second, etc.
var image = red[0].Bandjoin(green[1]).Bandjoin(blue[2]);

// Alternative way:
// NetVips >= 1.1.0-rc2:
// image = red[0].Bandjoin(green[1], blue[2]);
// or NetVips <= 1.0.7:
// image = red[0].Bandjoin(new object[] {green[1], blue[2]});

image.WriteToFile("rgb.png");
```

Otherwise, if you do:
```csharp
var image = red.Bandjoin(green).Bandjoin(blue);
```

You'll end up with a nine-band image (assuming the images each have 3 bands).

As for your tiff question, you could try to make a seven band image (for example). libvips then saves the image as an RGB image + the extra 4 channels as unassoc-alpha. See https://github.com/libvips/libvips/issues/1253#issuecomment-481793214.

**Comment by ptrsuder** [comment]
Sorry, I should have clarified. I'm joining one-band images, each one represents color channel. Resulted image has 3 bands and has Interpretation property 'b-w'. When I save it as png all color channels are the same and it has transparency.

**Comment by ptrsuder** [comment]
Okay, it seems this do the trick!
`imageResult = imageResult.Copy(interpretation: "srgb").Cast("uchar");`

**Comment by ptrsuder** [comment]
Regarding tiff and alpha, here is example of 6 band image. First alpha channel is displayed as transparency, but I guess it is photoshop specific thing maybe?
![image](https://user-images.githubusercontent.com/18538582/59569501-fca7ef80-9092-11e9-8447-cd28c6d9b80f.png)
