### ISSUE TITLE
NetVips.Version(0) invalid

### ISSUE THREAD

**Issue by toybuilder** [kleisauke/net-vips#38]
I apologize in advance if this is a newbie question, as I am still coming up the learning curve on using Visual Studio and C# (Net Core).
In the https://github.com/kleisauke/net-vips README.md, the installation instruction indicates that a test for a successful install of NetVips will result in the test program printing a valid version number.
However, NetVips.Version(0) does not resolve to a valid identifier/expression.  
It looks like there is a NetVips.ModuleInitializer.Version, however, that is supposed to return a 3-byte Integer?  (Note: the returned value is 0x080800; which matches 8.8.0 as expected.)
Is this simply a case where the method to retrieve the version number has changed?  Or am I doing something wrong with how I've configured my project to use NetVips?  

Thanks in advance!

**Comment by kleisauke** [comment]
I've renamed the base class from `Base` to `NetVips` within v1.1.0-rc2 to comply with the C# code conventions. So if you have installed NetVips v1.0.7 you can use `Base.Version`.

I'm sorry for the confusion. Next time, I'll make sure I don't update the `README.md` too early.

**Comment by kleisauke** [comment]
NetVips v1.1.0 is now available.

Feel free to re-open if there are still further questions related to this.
