### ISSUE TITLE
Composite with x,y position as array

### ISSUE THREAD

**Issue by stefanak-michal** [kleisauke/net-vips#39]
Hi.

Composite method supports more than one picture. But offset as x,y position is only integer. It will be nice, to have a opportunity to insert x,y as arrays.

https://libvips.github.io/libvips/API/current/libvips-conversion.html#vips-composite
x : VipsArrayInt, position of subimages
y : VipsArrayInt, position of subimages

**Comment by kleisauke** [comment]
NetVips v1.1.0 is now available.
