### ISSUE TITLE
GDI Interop

### ISSUE THREAD

**Issue by generatives** [kleisauke/net-vips#41]
I'm trying to use NetVips as a step in a System.Drawing.Bitmap based image processing pipeline. Eventually I want to move the whole pipeline over to NetVips but for now I am stuck using them together. I have been trying to find a fast way of creating a NetVips.Image from a Bitmap object but haven't been able to come up with a good solution. I was wondering if anyone knew of an example of this being done? Thanks for any help.

**Comment by kleisauke** [comment]
Hello, did you see https://github.com/kleisauke/net-vips/issues/17#issuecomment-424269278?

Note that this can be written even easier with NetVips >= 1.1.0-rc3:
```csharp
var bmp = new Bitmap(1024, 1024);

Image image;
using (var memoryStream = new MemoryStream())
{
    bmp.Save(memoryStream, ImageFormat.Jpeg);

    image = Image.NewFromStream(memoryStream, access: Enums.Access.Sequential);
}

Console.WriteLine(@"<NetVips.Image {0}x{1} {2}, {3} bands, {4}>", image.Width, image.Height,
    image.Format, image.Bands, image.Interpretation);
```

**Comment by CanadianHusky** [comment]
Hello, the library is very impressive. Thank you for the ongoing effort.

I have further questions regarding GDI Interop.

    GDI_img = System.Drawing.Image.FromStream(vipsImg.WriteToStream(".jpg[Q=80]")) '210 ms
    GDI_img = System.Drawing.Image.FromStream(vipsImg.WriteToStream(".tif")) '490 ms
    GDI_img = System.Drawing.Image.FromStream(vipsImg.WriteToStream(".png")) '1115 ms

Question 1:
Is the above method the recommended way to create a GDI Image from a Vips Image ? with the intention of drawing on screen, in a picturebox, or as part of the GDI Graphics object.

Question 2:
Is there any way to use a Vips image in GDI , with the GDI graphics object ? -without- converting the vips image to GDI first.

Question 3:
based on my sample file, JPG format does the vips to GDI conversion the fastest. Is there another format worth trying that will work faster ?

Question 4:
Where can I get a full list/documentation of the 'formatString' and its parameters ?
I do not have the vips command line app, I only use the .NET wrapper.

thank you kindly.

**Comment by kleisauke** [comment]
I found a better way to speed up and make the vips <--> GDI+ conversion easier (commit dc6b635). It will use the [`LockBits`](https://docs.microsoft.com/en-us/dotnet/api/system.drawing.bitmap.lockbits) and [`UnlockBits`](https://docs.microsoft.com/en-us/dotnet/api/system.drawing.bitmap.unlockbits) methods within GDI to import/export pixel data. This is faster than encoding/decoding the image to a JPEG (or PNG, TIFF, etc.) memory stream.

If you want to test this, you can use the nightly version of NetVips. Add the `https://ci.appveyor.com/nuget/net-vips` feed in the `<packageSources>` section of your `NuGet.config`:
```xml
<packageSources>
  <add key="netvips-nightly" value="https://ci.appveyor.com/nuget/net-vips" />
</packageSources>
```

And include NetVips and NetVips.Extensions 1.1.1 (build number 150 - prerelease). 

@CanadianHusky Regarding your questions:
1. The recommended way is to use the `ToBitmap()` method within the new NetVips.Extensions package. See for an example here:
   [samples/NetVips.Samples/Samples/GdiConvert.cs](https://github.com/kleisauke/net-vips/blob/master/samples/NetVips.Samples/Samples/GdiConvert.cs)
2. I don't quite understand this question. I don't see a possibility to use vips images in GDI without conversion.
3. The above methods (`ToBitmap()` / `ToVips()`) should be faster.
4. The `WriteToStream` function is very simple: it's a overload for `WriteToBuffer` that converts a byte array into a `MemoryStream`. `WriteToBuffer` looks at the suffix and finds the highest-priority saver that supports that extension. You can call the savers directly, for example:
   ```csharp
   byte[] buffer = image.JpegsaveBuffer(q: 85);
   ```
   The full set of options available depend upon the save operation that will be executed. For example, to see the available options for the JPEG saver:
   https://libvips.github.io/libvips/API/current/VipsForeignSave.html#vips-jpegsave-buffer

**Comment by CanadianHusky** [comment]
Thank you for the detailed information. 
Your library is indeed extremely capable and I am still exploring the available functions

**Comment by kleisauke** [comment]
A pre-release version of [NetVips.Extensions v1.0.0-rc1](https://www.nuget.org/packages/NetVips.Extensions/1.0.0-rc1) is now available on NuGet. This package contains the `ToBitmap()` / `ToVips()` functions for converting a GDI+ bitmap to NetVips and vice versa.

Any feedback is more than welcome!

**Comment by CanadianHusky** [comment]
Hello and thanks for the update, I tested it briefly.

1-
Tip for people that want to use the ToBitmap() / ToVips() Functions. They are extension functions and unless you 
`Imports NetVips.Extensions`
you will be wondering why it is not available.

I installed the package with 
`PM> Install-Package NetVips.Extensions -Version 1.0.0-rc1 `

2- there are serious issues with the conversion

```
Private Sub OpenandDisplayImage()
        Dim input As String = "c:\temp\test.jpg"
        Dim img As NetVips.Image = Image.NewFromFile(input,,,,)
        Dim bmp As System.Drawing.Image = img.ToBitmap 'uses extension method
        Me.PictureBox1.Image = bmp
        bmp = Nothing
        img.Dispose()
    End Sub
```

2.1- the result is badly skewed for test.jpg
![image](https://user-images.githubusercontent.com/35332003/71989997-b212de00-3243-11ea-85db-9e339aa92341.png)

2.2 - the result is severe color distortion for photo.png
![image](https://user-images.githubusercontent.com/35332003/71990141-f0100200-3243-11ea-9219-f7f73d634d04.png)

The original files are shown below and available at this link for 1 week

(https://www.dropbox.com/s/n0s3ceh6lkrshal/image%20files%20for%20netvips.zip?dl=0)

![photo](https://user-images.githubusercontent.com/35332003/71990239-19309280-3244-11ea-8e83-6de5dee40963.png)
![test](https://user-images.githubusercontent.com/35332003/71990243-19309280-3244-11ea-941a-8a69777b403d.jpg)

**Comment by kleisauke** [comment]
Thanks for testing! Sorry that I didn't catch these issues earlier.

Commit f8c819fda1635be479545cebd05072c0254ac906 should fix this. It has just been released on NuGet with [NetVips.Extensions v1.0.0-rc2](https://www.nuget.org/packages/NetVips.Extensions/1.0.0-rc2).

**Comment by CanadianHusky** [comment]
Hello, I tested NetVips.Extensions v1.0.0-rc2.

ToBitmap() and ToVips() work as expected now, without any problems on the palette/stride for 8 bit indexed and 24bit images but I have not tested other less common pixel formats.

not a big deal, but one small recommendation:

The function BitmapConverter.ToVips is expecting a GDI Bitmap object as parameter and does not 
accept a GDI Image object unless OPTION EXPLICIT = OFF or the following cast is made 

`Dim vipsImg As NetVips.Image = BitmapConverter.ToVips(CType(bmp, Bitmap))`

an overload to 
`BitmapConverter.ToVips` with Image as System.Drawing.Image could be useful

what would be really interesting though is to know if this .NET binding can handle the latest changes in the underlying libvips library, in particular the improved streaming capability as explained here https://libvips.github.io/libvips/2019/11/29/True-streaming-for-libvips.html

Thank you for updates. Great work!

**Comment by kleisauke** [comment]
[NetVips v1.2.0](https://www.nuget.org/packages/NetVips/1.2.0) and [NetVips.Extensions v1.0.0](https://www.nuget.org/packages/NetVips.Extensions/1.0.0) is now available.

@CanadianHusky The .NET binding supports this feature. See issue #33 and the [tutorial](
https://kleisauke.github.io/net-vips/tutorial/getting_started.html#custom-sources-and-targets) for more information. Make sure you've installed libvips >= 8.9 (or [NetVips.Native v8.9.1](https://www.nuget.org/packages/NetVips.Native/8.9.1) if you use the pre-compiled libvips binaries).
