### ISSUE TITLE
Slower PNG save operation

### ISSUE THREAD

**Issue by akaprasanga** [kleisauke/net-vips#42]
Hi,
I need to save an image of dimension 4000X5000 in PNG format. Just opening a jpg file and saving it to png alone is too slow(8.874 secs) but saving the same file in  V format takes 0.439 secs. 
NetVips version = 1.0.7
Is there any way around to save png images quickly?
`stopwatch.Start();
            string fname = @"D:\photo.jpg";
            var image = NetVips.Image.NewFromFile(fname);
            image.WriteToFile(@"D:\vips.v");
            stopwatch.Stop();
            Console.WriteLine(stopwatch.ElapsedMilliseconds);

            stopwatch2.Start();
            var image2 = NetVips.Image.NewFromFile(fname);
            image2.WriteToFile(@"D:\vips.png");
            stopwatch2.Stop();
            Console.WriteLine(stopwatch2.ElapsedMilliseconds);
            Console.ReadKey();`

**Comment by kleisauke** [comment]
Why do you have to convert an image of that size to PNG? PNG is rather a slow format, and it uses deflate compression, which is even slower. If you switch to TIFF instead, it gets much quicker:
```csharp
// https://commons.wikimedia.org/wiki/File:Stream_near_a_white_mountain_(Unsplash).jpg (4,000 x 5,000 pixels - 4.98 MB)
var im = Image.NewFromFile("Stream_near_a_white_mountain.jpg", access: Enums.Access.Sequential);
im.WriteToFile("x.tif", new VOption
{
    {"strip", true},
    {"compression", "jpeg"}
});
```

On my Windows PC it takes about 200 milliseconds with the above code. When I convert the same image to PNG it takes about 6.8 seconds (and the output size is 23 MB, which is quite a lot for a PNG image).

**Comment by akaprasanga** [comment]
Thank you for your response.
Actually, storage usage is my main issue. I need to go further up to 15k x 18k images where the storage usage will be huge and I also need to use PNG for color separated layers. Looks like tradeoff of the execution time is the only option.

**Comment by kleisauke** [comment]
TIFF supports tiling, so you can have a JPG-compressed image larger than 64k x 64k pixels:
```csharp
var im = Image.Black(100000, 100000);
im.WriteToFile("x.tif", new VOption
{
    {"tile", true},
    {"tile_width", 256},
    {"tile_height", 256},
    {"compression", "jpeg"}
});
```

This format breaks the image into (by default) 128x128 pixel tiles and compresses each one separately. The tiles are stored in a TIFF file with an index, so you can pull out individual tiles very quickly.

It may also be worth experimenting with WebP and Zstd compression in TIFF. These TIFF compression codecs will be available in libvips 8.9.

**Comment by akaprasanga** [comment]
Will try with this one. Thank you!

**Comment by kleisauke** [comment]
You can also try to save without compression (deflate compression is quite slow). This results in large PNG files, so I think you'd better use the above TIFF examples:

```csharp
// https://commons.wikimedia.org/wiki/File:Stream_near_a_white_mountain_(Unsplash).jpg (4,000 x 5,000 pixels - 4.98 MB)
var im = Image.NewFromFile("Stream_near_a_white_mountain.jpg", access: Enums.Access.Sequential);
im.WriteToFile("x.png", new VOption
{
    {"strip", true},
    {"compression",  0}
});
```

On my Windows PC it takes about 900 milliseconds with the above code. By default it will use a zlib compression level of 6, which takes about six seconds with NetVips.Native 8.8.1 (which has just been released).

Note that I made a performance gain of 800 milliseconds for the Windows binaries (it was 6.8 seconds in the previous release). This because libpng in the Windows binaries are now built with the appropriate compiler/optimizations flags, see commit:
https://github.com/libvips/build-win64-mxe/commit/739f9396746d05822d2c899ae75cbf7403dc9ada

**Comment by kleisauke** [comment]
You might also be interested in this issue: https://github.com/lovell/sharp-libvips/issues/25. See the relevant benchmarks: https://gist.github.com/kleisauke/879e3075a675c6f945dff3772d2ef0a3.

**Comment by kleisauke** [comment]
I'm closing this issue as NetVips can't do much about it. Any potential improvements can be tracked at https://github.com/lovell/sharp-libvips/issues/25 or https://github.com/libvips/libvips/issues/1403.
