### ISSUE TITLE
NetVips.VipsException: unable to call openslideload

### ISSUE THREAD

**Issue by ricklina90** [kleisauke/net-vips#43]
[CMU-1_001.zip](https://github.com/kleisauke/net-vips/files/3454647/CMU-1_001.zip)

Hello,
I'm trying to use NetVips function openslideload to read some svs images. I meet some problems. If the path of the picture has Chinese or the name of the picture is Chinese, an error will occur. 
 this error pops up (below) for this code:

                try
                {
                    Image thumbnail = NetVips.Image.Openslideload(path);
                }
                catch (Exception e)
                {
                    string errormessage = e.ToString();
                }

**NetVips.VipsException**: unable to call openslideload
openslide2vips: unsupported slide format

Thanks for your attention,
Rick

**Comment by kleisauke** [comment]
I could reproduce this and fix it within the MXE-based Windows builds, see commit:
https://github.com/libvips/build-win64-mxe/commit/c0cfaf681f3467f88617c9023fd56aa9d824be0a

I'll also try to include this within the official libvips Windows binaries. As a workaround, you can use [`Image.NewFromFile`](https://kleisauke.github.io/net-vips/api/NetVips.Image.html#NetVips_Image_NewFromFile_):
```csharp
var image = Image.NewFromFile("CMU-1_001/CMU-1_001┤·©ı.svs", access: "sequential");
```

Thank for reporting this!

**Comment by ricklina90** [comment]
Hi
Thanks for the quick fix! I want to build libvips/build-win64-mxe to test this problem in windows, but I unfamiliar with linux.  I use git to download mxe and build-win64-mxe, but I don''t know build build-win64-mxe in mxe. Please help me build this project, or give me executable program.

Thanks for your attention,
Rick

**Comment by kleisauke** [comment]
You can download the libvips Windows binaries (`-all` distribution) built from commit libvips/build-win64-mxe@1dfa9cd here:
https://libvips-packaging.s3.amazonaws.com/vips-dev-w32-all-8.8.1-1dfa9cd.zip
https://libvips-packaging.s3.amazonaws.com/vips-dev-w64-all-8.8.1-1dfa9cd.zip

PR libvips/build-win64#30 has been merged, so this will also be resolved in the Windows binaries of libvips 8.8.2.

Let me know if this works for you!

**Comment by ricklina90** [comment]
Thanks for the quick provide executable program. After I test the path of the picture has Chinese or the name of the picture is Chinese, the problem is solve.
Thanks for the help !

Thanks for your attention,
Rick

**Comment by kleisauke** [comment]
8.8.2 is out now and should also have this fix.
