### ISSUE TITLE
Creating Conditional image for IFTHENELSE opreration

### ISSUE THREAD

**Issue by akaprasanga** [kleisauke/net-vips#44]
I could not figure out how a conditional image can be created where the image equals to the given color value in NetVips.
In pyvips I have done something like this:
```
color_tuple= (255, 0, 0)
result_img= (original_img == color_tuple).bandand().ifthenelse( 0, 100)
```
What might be the correct and efficient implementation of above statement in C#?

**Comment by akaprasanga** [comment]
Looks like I need to use Equal function to compare with a color Tuple. My solution:
```
var color_tuple = new[] { 255, 0, 0};
var result_img = (original_img.Equal(color_tuple)).ifthenelse( 0, 100)
```
Sorry for this minor issue. I will close this one.

**Comment by kleisauke** [comment]
I'm glad you figured it out! Since version 1.1.0 you have to use `.Equal` instead of `==`. The reason for this is that it caused problems with `null` checks. For example, this statement didn't compile before v1.1.0:
```csharp
Image image = null;
if (image == null)
{
    
}
````

**Comment by akaprasanga** [comment]
Thank you for the inside story.
