### ISSUE TITLE
Writing image to byte array

### ISSUE THREAD

**Issue by Jey1980** [kleisauke/net-vips#45]
Hi @kleisauke,

          I am using bitmap.WriteToMemory() to write it to byte array, Let me know is there anyway to write those image byte values to another object, using byte[] array throws exception if the array size exceeds int limit.

**Comment by kleisauke** [comment]
My apologies for the slow reply; I'm quite busy with my study.

Indeed, `WriteToMemory` is not suitable for large images, it will easily exceed the maximum number of elements (`Int32.MaxValue`), plus you could hit the 2GB maximum object size limit.

Try [Rawsave](https://libvips.github.io/libvips/API/current/VipsForeignSave.html#vips-rawsave) instead:
```csharp
var image = Image.NewFromFile("huge.jpg", access: "sequential");
image.Rawsave("test.raw");
```

This operation writes raw pixel data to a file with no header or other metadata.

**Comment by Jey1980** [comment]
@kleisauke 

        When I try to use Rawsave to save and then after that I need to read the file as bytes, So when I try to read it again using stream, it throws exception as "it is been used by another process", It is very small image, When I checked the file location the file is 0 bytes....

Thanks
JK

**Comment by kleisauke** [comment]
Sorry for having sat on this. I could reproduce this with: 
```csharp
NetVips.CacheSetMax(0);

// Ensure that the image is disposed 
using (var image = Image.NewFromFile("images/sample2.v", access: "sequential"))
{
    image.Rawsave("test.raw");
} // .Dispose() / g_object_unref

// Used by another process
using (var input = File.OpenRead("test.raw"))
{
    Console.WriteLine("size: " + input.Length);
}
```

But not with:
```csharp
NetVips.CacheSetMax(0);

int width;
int height;
int bands;

// Ensure that the image is disposed 
using (var image = Image.NewFromFile("images/sample2.v", access: "sequential"))
{
    width = image.Width;
    height = image.Height;
    bands = image.Bands;

    image.Rawsave("test.raw");
} // .Dispose() / g_object_unref

// Try to load "test.raw"
using (var image = Image.Rawload("test.raw", width, height, bands, access: "sequential"))
{
    image.WriteToFile("test.jpg");
}
```

Regarding your second question; what do you mean with bytes? Pixel data or file content? By default `Tiffsave` / `vips_tiffsave` saves without compression, so the pixel data should be the same. For example:
```csharp
using (var image = Image.NewFromFile("images/sample2.v", access: "sequential"))
{
    image.Tiffsave("x.tiff"/*, compression: "deflate"*/);

    using var image2 = Image.NewFromFile("x.tiff", access: "sequential");

    // Sanity check
    Debug.Assert(image.WriteToMemory().SequenceEqual(image2.WriteToMemory()));
}
```

@jcupitt Is it possible to early close the file descriptor within `vips_rawsave`? For e.g. moving https://github.com/libvips/libvips/blob/1338def5353886a813a6ccbdc9ebc29cb73df82e/libvips/foreign/rawsave.c#L86 to `vips_foreign_save_raw_write` (untested).

**Comment by jcupitt** [comment]
@kleisauke sure, it sounds like a safe change.

We should probably rework raw load/save for the new source/target API -- we'd get early close for free.

**Comment by kleisauke** [comment]
Let's track the raw load/save enhancement in https://github.com/libvips/libvips/issues/1541.
