### ISSUE TITLE
High Memory Usage in Sequential Access Mode

### ISSUE THREAD

**Issue by akaprasanga** [kleisauke/net-vips#46]
Hi,
I was trying to get the Emboss like map from an **PNG** image of dimension: **15000X18000**. When I tried with **sequential access mode** the memory usage is above **1 GB** but in **random access mode** the memory usage is only **100MB**. Is this natural or I am doing something wrong?I want to use sequential mode for faster operation with low memory usage, is this possible?
Windows 10 and NetVips version :: 1.1.0
```
// Opening 3 images to use Wrap in sequential mode
string filename = "D:\\A.png";
NetVips.Image img = NetVips.Image.NewFromFile(filename, access:Enums.Access.Sequential).Colourspace("b-w");
NetVips.Image imgOne = NetVips.Image.NewFromFile(filename, access: Enums.Access.Sequential).Colourspace("b-w");
NetVips.Image imgTwo = NetVips.Image.NewFromFile(filename, access: Enums.Access.Sequential).Colourspace("b-w");
            
var embossKernel = Image.NewFromArray(new[,]
                                {
                                    {0.0, 0.0, -1.0},
                                    {0.0, 0.0, 0.0},
                                    {1.0, 0.0, 0.0}
                                }, scale: 0.25, offset: 0);

// Creating Outline of an Image
var moveRight = imgOne.Wrap(x: 1, y: 0);
var moveUp = imgTwo.Wrap(x: 0, y: 1);
var outline = (moveRight - img).Abs() + (moveUp -img).Abs();
outline = outline.RelationalConst("more", new double[] {50}).Invert();

//Applying Kernel
outline = outline.Ifthenelse(255, 200).Gaussblur(2);
outline = (outline.Conv(embossKernel, precision: "float") + 128);
outline = (outline > 200).Ifthenelse(200, outline);

outline.WriteToFile("D:\\Carving.jpg");
```

**Comment by akaprasanga** [comment]
After some trials, I figured out Wrap method in Y-axis uses a lot of memory which seems obvious regarding working of the Libvips in sequential mode. But is there any other workaround similar to Wrap in Y-axis in sequential access mode with low memory consumption?

Furthermore, I am using Wrap method to create an outline of the edges in PNG images. If there is any other method to trace out the outline of a color-separated PNG image then please suggest me.

**Comment by kleisauke** [comment]
My apologies for the slow reply; I'm quite busy with my study.

You can use the canny edge detector, which was [introduced in libvips 8.7](https://libvips.github.io/libvips/2018/07/26/What's-new-in-8.7.html#new-operators). For example:
```csharp
var im = Image.Thumbnail("images/lichtenstein.jpg", 512);

// Optionally, convert to greyscale
// im = im.Colourspace("b-w");

// Canny edge detector
im = im.Canny(1.4, precision: Enums.Precision.Integer);

// Canny makes a float image, scale the output up to make it visible.
im *= 64;

im.WriteToFile("canny.jpg");
```

Input: https://upload.wikimedia.org/wikipedia/commons/e/e8/Lichtenstein.jpg

Output:
![canny](https://user-images.githubusercontent.com/12746591/67225959-6ca8f680-f434-11e9-8884-036c7daf609d.jpg)

**Comment by akaprasanga** [comment]
I forgot to mention that I am actually dealing with PNG images with limited colors so I thought Canny would be a slower way to create an outline, so I opted to Wrap and subtract the original image. Anyway, thank you for the reply and it's not late though :grinning:

**Comment by kleisauke** [comment]
As far as I know is embossing not a edge detection algorithm, it's more used for artistic effects. You might consider using the simple sobel edge detection algorithm:
```csharp
var img = Image.Thumbnail("images/lichtenstein.jpg", 512);

// Convert to greyscale
img = img.Colourspace("b-w");

// Apply sobel filter
img = img.Sobel();

img.WriteToFile("sobel.jpg");
```

Or:
```csharp
var img = Image.Thumbnail("images/lichtenstein.jpg", 512);

// Convert to greyscale
img = img.Colourspace("b-w");

// Sobel kernel
var kernel = Image.NewFromArray(new[,]
{
    {1.0, 2.0, 1.0},
    {0.0, 0.0, 0.0},
    {-1.0, -2.0, -1.0}
});

// Apply sobel filter
var sobel = img.Conv(kernel, precision: Enums.Precision.Float).Abs() +
            img.Conv(kernel.Rot90(), precision: Enums.Precision.Float).Abs();

// Cast back to original band format
sobel = sobel.Cast(img.Format);

sobel.WriteToFile("sobel.jpg");
```

Both code snippets produces the same output:
![sobel](https://user-images.githubusercontent.com/12746591/67310672-8151c100-f4fe-11e9-8080-2b6c8d978e94.jpg)

The first one should be a little faster, because it has a fast path for `uchar` images. The second one is more tunable, I think you can also use this to apply a emboss effect. 

This general image processing question sounds like it may be more suited to StackOverflow or similar.

**Comment by akaprasanga** [comment]
> This general image processing question sounds like it may be more suited to StackOverflow or similar.

Actually, my initial concern was about high memory usage of Wrap function along Y-axis but, our conversation took a shift towards general Image processing question. Sorry for that. And, thank you so much for the help!

**Comment by kleisauke** [comment]
> Actually, my initial concern was about high memory usage of Wrap function along Y-axis but, our conversation took a shift towards general Image processing question. Sorry for that. And, thank you so much for the help!

My bad, I just realised that I missed a question.

> But is there any other workaround similar to Wrap in Y-axis in sequential access mode with low memory consumption?

Instead of:
```csharp
var moveRight = imgOne.Wrap(x: 1, y: 0);
var moveUp = imgTwo.Wrap(x: 0, y: 1);
```

You could try this:
```csharp
var moveRight = imgOne.Replicate(2, 1).ExtractArea(img.Width - 1, 0, img.Width, img.Height);
var moveUp = imgTwo.Replicate(1, 2).ExtractArea(0, img.Height - 1, img.Width, img.Height);
```

Or if you just want to shift:
```csharp
var moveRight = imgOne.Embed(1, 0, img.Width, img.Height);
var moveUp = imgTwo.Embed(0, 1, img.Width, img.Height);
```



@jcupitt Perhaps we could use a fast path for `x == 0` or `y == 0` within `vips_wrap`, see for example:
```diff
diff --git a/libvips/conversion/wrap.c b/libvips/conversion/wrap.c
index 1111111..2222222 100644
--- a/libvips/conversion/wrap.c
+++ b/libvips/conversion/wrap.c
@@ -10,6 +10,8 @@
  * 31/5/13
  * 	- redone as a class
  * 	- added rotquad behaviour if x/y not set
+ * 5/11/19 kleisauke
+ * 	- fast path for x == 0 or y == 0
  */
 
 /*
@@ -83,14 +85,21 @@ vips_wrap_build( VipsObject *object )
 	/* Clock arithmetic: we want negative x/y to wrap around
 	 * nicely.
 	 */
-	x = wrap->x < 0 ? 
-		-wrap->x % wrap->in->Xsize : 
-		wrap->in->Xsize - wrap->x % wrap->in->Xsize;
-	y = wrap->y < 0 ? 
-		-wrap->y % wrap->in->Ysize : 
-		wrap->in->Ysize - wrap->y % wrap->in->Ysize;
-
-	if( vips_replicate( wrap->in, &t[0], 2, 2, NULL ) ||
+	if( wrap->x == 0 )
+		x = 0;
+	else if( wrap->x < 0 )
+		x = -wrap->x % wrap->in->Xsize;
+	else
+		x = wrap->in->Xsize - wrap->x % wrap->in->Xsize;
+
+	if( wrap->y == 0 )
+		y = 0;
+	else if( wrap->y < 0 )
+		y = -wrap->y % wrap->in->Ysize;
+	else
+		y = wrap->in->Ysize - wrap->y % wrap->in->Ysize;
+
+	if( vips_replicate( wrap->in, &t[0], x == 0 ? 1 : 2, y == 0 ? 1 : 2, NULL ) ||
 		vips_extract_area( t[0], &t[1], 
 			x, y, wrap->in->Xsize, wrap->in->Ysize, NULL ) ||
 		vips_image_write( t[1], conversion->out ) )
```

This patch ensures that the image is not replicated across when `x == 0` or  replicated down when `y == 0`. I didn't benchmark it, so maybe it doesn't matter.

**Comment by akaprasanga** [comment]
Thank you for the quick fix.

**Comment by jcupitt** [comment]
Oh, interesting @kleisauke. I think it won't make a difference to run speed, but I've not benchmarked either.

@akaprasanga as you found, don't use `wrap()` for things like this, just do a convolution. This code:

```C#
var moveRight = imgOne.Wrap(x: 1, y: 0);
var outline = (moveRight - img).Abs()
```

Is exactly the same as:

```python
outline = imgOne.conv([[-1, 1]]).abs()
```

(python, I don't have C# handy). Most add / subtract / multiply of pixels within a region can be done with `conv`.

In any case, as Kleis says, `canny` should give a better edge effect.

**Comment by akaprasanga** [comment]
> outline = imgOne.conv([[-1, 1]]).abs()

Ohh its too cool. I was searching for this kind of matrix from starting thank you @jcupitt !
