### ISSUE TITLE
Cropping using 4 corner points

### ISSUE THREAD

**Issue by Jey1980** [kleisauke/net-vips#47]
If we try to Crop using 4 corners top and bottom with different width and height, by just providing topright, Topleft , width and height will provide wrongly clipped image

EX: 
TopRight = (   198,   195)
TopLeft   = (  359,   195)
BottomLeft = (  339,  1612)
BottomRight =(   168,  1606)

will never work, just by using TopRight, topLeft

@jcupitt @kleisauke

**Comment by jcupitt** [comment]
Cross-posted here: https://github.com/libvips/libvips/issues/1438

Please don't open multiple issues with the same question -- it just makes more work for volunteers who are trying to support free software.

**Comment by Jey1980** [comment]
Opened in another request
