### ISSUE TITLE
Loading PDF

### ISSUE THREAD

**Issue by chebude** [kleisauke/net-vips#48]
Hi,

I'm trying to load PDF using net-vips, however I keep getting this error : 

`var vipsImage = NetVips.Image.NewFromFile(@"pdfFile.pdf");`
`unable to load from file pdfFile.pdf" is not a known file format`

I understand I require poppler for the PDF support, but i'm not exactly sure, how to integrate poppler support to my vips code, any help is appreciated.
I included all the dll (including libpoppler-91) in the same folder as libvips, but no luck

Thanks

**Comment by kleisauke** [comment]
Hello, did you see https://github.com/kleisauke/net-vips/issues/11#issuecomment-402438726 ?

**Comment by chebude** [comment]
Yes, it's working now. Thanks
