### ISSUE TITLE
Output Mosaic Image is White when using Globalbalance

### ISSUE THREAD

**Issue by NiteshSaxena** [kleisauke/net-vips#5]
Hi,

I am using Mosaic with Global balance to merge images. Only using Mosaic merge images but using Globalbalance makes the ouput Image white? The resolution of two source images is 1600x1200, and I want to overlap vertical on 180 px.

Below is my code:

            var image = Image.NewFromFile("source1.tif");
            var secondaryImage = Image.NewFromFile("source2.tif");
            Image mosaicedImage = image.Mosaic(secondaryImage, "vertical", 0, 1020, 0, 180);

            var ouptutImage = mosaicedImage.Globalbalance();
            ouptutImage.WriteToFile("output.tif");

Any suggestions?

**Comment by kleisauke** [comment]
Hello @NiteshSaxena,

I've been able to reproduce this. It looks like a bug in libvips which generates white images for mosaic images when there's no compression. If you set the compression, the correct image is outputted:

```csharp
var image = Image.NewFromFile("images/cd1.1.jpg");
var secondaryImage = Image.NewFromFile("images/cd1.2.jpg");
var mosaicedImage = image.Mosaic(secondaryImage, Enums.Direction.Horizontal, 531, 0, 100, 0);
var outputImage = mosaicedImage.Globalbalance();

outputImage.WriteToFile("output.tif", new VOption
{
    {"compression", "jpeg"},
    {"Q", 95}
});
```
(tested with the example images from: https://stackoverflow.com/a/50190264/1480019)

@jcupitt, Is it needed to set the compression for mosaic images? I could also reproduce this in pyvips:
```python
im = pyvips.Image.new_from_file("images/cd1.1.jpg")
im2 = pyvips.Image.new_from_file("images/cd1.2.jpg")

mosaiced = im.Mosaic(im2, "horizontal", 531, 0, 100, 0)
output = mosaiced.Globalbalance()

output.write_to_file("output.tif")
```

**Comment by jcupitt** [comment]
Hello Kleis,

`globalbalance` outputs a float image, since it needs to be able to represent >255 and <0 pixels. You have to do any final adjustments in float before converting to uchar and saving.

TIFF of course can save float images, so it just saves them directly. TIFF float expects 0 - 1 for black to white, so the image looks very, very white when you load it back. 

I would add `.cast('uchar')` before the final write.

**Comment by kleisauke** [comment]
Ah I see, `globalbalance` outputs indeed a float image. Thanks for your help!

@NiteshSaxena This should work in your case:
```csharp
var image = Image.NewFromFile("source1.tif");
var secondaryImage = Image.NewFromFile("source2.tif");
var mosaicedImage = image.Mosaic(secondaryImage, Enums.Direction.Vertical, 0, 1020, 0, 180);

var outputImage = mosaicedImage.Globalbalance().Cast(Enums.BandFormat.Uchar);
outputImage.WriteToFile("output.tif");
```

Let me know if this solves the problem.

**Comment by NiteshSaxena** [comment]
@kleisauke , It worked but one more thing, the mosaic has black borders in left and right side. Did you also see the black border when you reproduced the issue?

**Comment by kleisauke** [comment]
I didn't see black borders using the test images from https://stackoverflow.com/a/50190264/1480019. I'll try some other images.

**Comment by jcupitt** [comment]
The source images are here, in case you need a larger set:

https://github.com/jcupitt/nip2/tree/master/share/nip2/data/examples/1_point_mosaic

![x](https://user-images.githubusercontent.com/580843/39921827-3fb56304-5514-11e8-95ae-06207468a65d.jpg)

If you start nip2 and click File / Open Examples / 1_point, nip2 will load a demo workspace that assembles this mosaic for you.

**Comment by jcupitt** [comment]
... the black edges here are pixels which don't exist in the mosaic. libvips uses 0 to indicate transparency in mosaic operations.

**Comment by kleisauke** [comment]
I have made an example with the larger set from nip2 (commit https://github.com/kleisauke/net-vips/commit/9b2fe32f3d50ee326c60d9d85a059302ef2dcca2). It generates the following image:
<details>
 <summary>1 point mosaic example</summary>

![1-pt-mosaic](https://user-images.githubusercontent.com/12746591/39930986-6989440c-553c-11e8-80b9-46de38a6b28a.jpg)
</details>

&nbsp;
It's approximately the same as the nip2 output (I only skipped the sharpen operation).

**Comment by kleisauke** [comment]
@NiteshSaxena Were you able to make any progress with this?

**Comment by NiteshSaxena** [comment]
@kleisauke The black borders on the side depends on the Overlap settings, Changing the overlap size minimizes the borders. For some of my input samples, I am getting the border while for some I am able to merge. 

Anyway, on the merged image, one can see where the overlap happened as it shows in your 1-point mosaic example.

**Comment by jcupitt** [comment]
If you post a pair of source images, the mosaic command you ran, and the problem you see in the output, I'll try to investigate.

**Comment by kleisauke** [comment]
Feel free to re-open with more details if further help is required.

**Comment by NiteshSaxena** [comment]
Seems like there is no way around the issue, I cropped the sides to get the better output image.
