### ISSUE TITLE
Question: use custom libvips build in /opt directory

### ISSUE THREAD

**Issue by vkappie** [kleisauke/net-vips#50]
Hi,
I built custom libvips with poppler-glib support.
These libraries are bundled and deployed to AWS Lambda using Lambda layer, so they are located in /opt/lib
I've tried to set LD_LIBRARY_PATH env, but still get

> Unable to load shared library 'libvips.so.42' or one of its dependencies. In order to help diagnose loading problems, consider setting the LD_DEBUG environment variable: liblibvips.so.42: cannot open shared object file: No such file or directory

Since <UseGlobalLibvips> has been removed in the latest releases I cannot find a way to force NetVips to search LD_LIBRARY_PATH folders

Thanks in adnvance.

**Comment by vkappie** [comment]
I am closing this issue.. 
I found out that in AWS lambda you need to put /opt/lib at the first place inside LD_LIBRARY_PATH environment variable(by default it's in the end).

**Comment by kleisauke** [comment]
Ah, I forgot to respond to this. The `LD_LIBRARY_PATH` environment variable should indeed fix this if you install libvips in a non-standard path (anything other than `/usr` or `/usr/local`).

According to [this page](https://docs.aws.amazon.com/lambda/latest/dg/configuration-envvars.html#configuration-envvars-runtime) the environment variable on AWS Lambda already contains the `/opt/lib` directory. Anyways, glad it's resolved!
