### ISSUE TITLE
Dzsave not embeding srgb or tinysrgb profile to tile

### ISSUE THREAD

**Issue by fredprodibi** [kleisauke/net-vips#52]
Hello, I m trying to get the srgb or tinysrgb profile to be embedded in tiles but without success.

```
using (var image = Image.NewFromFile(@"C:\dz\dz 2.jpg"))
            {
                image.Dzsave(@"C:\dz\dz", basename: "dz",
                suffix: ".jpg[Q=78,optimize_coding=1,strip=1,profile=srgb,no_subsample=0]", container: "fs");
            }
```
or

```
using (var image = Image.NewFromFile(@"C:\dz\dz 2.jpg"))
            {
                image.Dzsave(@"C:\dz\dz", basename: "dz",
                suffix: ".jpg[Q=78,optimize_coding=1,strip=1,profile=C:/dz/tinyrgb.icc,no_subsample=0]", container: "fs");
            }
```

is it possible to do it?

**Comment by kleisauke** [comment]
libvips 8.9  (which has just been released) has a new `no_strip`  option for `dzsave` (see https://github.com/libvips/libvips/issues/1451). In NetVips, the equivalent is `noStrip` (snake_case -> camelCase). For example:
```csharp
const string input = "images/sample2.v";
const string output = "dz/dz.dzi";

using (var image = Image.NewFromFile(input))
{
    image.Dzsave(output, basename: "dz",
        suffix: ".jpg[Q=78,optimize_coding=1,profile=srgb]", noStrip: true);
}
```
```bash
$ vipsheader -a dz/dz_files/9/0_0.jpg | grep icc-profile-data
icc-profile-data: 6922 bytes of binary data
```

The above code requires [NetVips >= v1.2.0-rc1](https://www.nuget.org/packages/NetVips/1.2.0-rc1) and optionally [NetVips.Native >= v8.9.0-rc4](https://www.nuget.org/packages/NetVips.Native/8.9.0-rc4) (if you wish to use the pre-compiled libvips binaries).

**Comment by kleisauke** [comment]
[NetVips v1.2.0](https://www.nuget.org/packages/NetVips/1.2.0) and [NetVips.Native v8.9.1](https://www.nuget.org/packages/NetVips.Native/8.9.1) is now available.
