### ISSUE TITLE
System.Drawing.Bitmap to NetVips.Image: buffer is not in a known format

### ISSUE THREAD

**Issue by blasky** [kleisauke/net-vips#57]
I know this is not an ideal path, memory wise. But I have been trying to get the following working (...as I've seen suggested here and elsewhere) to convert some existing System.Drawing.Bitmap data to a NetVips.Image for further processing and saving.

```
Bitmap bitmap = <some bitmap object>;
byte[] imageBytes;

using (MemoryStream stream = new MemoryStream())
{
    bitmap.Save(stream, ImageFormat.Png);
    imageBytes = stream.ToArray();
}

Image img = Image.NewFromBuffer(imageBytes,  access: Enums.Access.Sequential);
```

However, this fails with the following exception...

```
NetVips.VipsException: unable to load from buffer
VipsForeignLoad: buffer is not in a known format
```

What horribly obvious thing am I missing? Thanks.

**Comment by blasky** [comment]
My bad. Sorry. I found a bug elsewhere in my code that was the culprit. The pattern above is doing its thing.

**Comment by kleisauke** [comment]
I'm glad you resolved it! You might be interested in the [NetVips.Extensions](https://www.nuget.org/packages/NetVips.Extensions) NuGet package. It contains the `ToBitmap()` / `ToVips()` functions for converting a GDI+ bitmap to NetVips and vice versa.

It should be faster than encoding/decoding the image to a JPEG (or PNG, TIFF, etc.) memory stream.

**Comment by blasky** [comment]
Thanks.
