### ISSUE TITLE
Jpegsave hangs for particular pdf files

### ISSUE THREAD

**Issue by s-neumann** [kleisauke/net-vips#59]
Hello, I have problems with few pdf files with big construction plans inside. The pdf file size is about 9MB. With other files in same size it is working well. After calling Jpegsave nothing goes on - only the initial 0 percent will be notified to VipsProgress.
Making a jpeg directly with libvips in powershell is working well, _so my question is, how can i find out, where the problem is. Is there any knowen issue?_

```
string inputFileName = @"Q:\TestFactory\testdaten\5_A_GR_00_01_0000_0P_F.pdf";
				string tempFileName = System.IO.Path.Combine(@"C:\Testdaten\Vips", $"{ Guid.NewGuid().ToString()}.jpg");
				using (NetVips.Image image = NetVips.Image.Pdfload(inputFileName, null, null, null, 1, null, null, null, null))
				{
					image.SetProgress(true);

					image.SignalConnect(Enums.Signals.PreEval, (Image.EvalDelegate)EvalHandler);
					image.SignalConnect(Enums.Signals.Eval, (Image.EvalDelegate)EvalHandler);
					image.SignalConnect(Enums.Signals.PostEval, (Image.EvalDelegate)EvalHandler);

					image.Jpegsave(tempFileName, null, null, null, null, null, null, null, null, null, true, null, null);
				}
```

**Comment by kleisauke** [comment]
I'm not aware of any problems within the PDF loader of libvips. I've a few questions:
1. Did you use the pre-compiled binaries (`vips-dev-w64-all-x.y.z.zip`) from the [main libvips repo]( https://github.com/libvips/libvips/releases) or from the [build-win64-mxe repo](https://github.com/libvips/build-win64-mxe/releases)?
libvips uses [Poppler](https://poppler.freedesktop.org/) for PDF rendering. The MXE-binaries depends on an newer version (v0.84.0  - released on Dec 28, 2019) whereas the binaries from the libvips repo depends on an older version (v0.79.0 - released on July 16, 2019).
3. Did you remove the `NetVips.Native.*` NuGet packages?
The binaries within the `NetVips.Native.*` NuGet packages may conflict with the globally installed binaries found on your `PATH` environment variable.
4. Are you able to provide some more details of the PDF that causes this hang?

(These questions assume that you're testing on Windows with the latest pre-compiled libvips binaries)

**Comment by s-neumann** [comment]
1. I use the binaries from build-win64-mxe repo
2. I don't use NetVips.Native NuGet packages
3. I'll try to offer a pdf for further testing ..

**Comment by kleisauke** [comment]
A PDF that reproduces this would be useful. fwiw, I'll try to package the latest version of Poppler (v0.85.0) when the next libvips version is released.

**Comment by kleisauke** [comment]
I've updated Poppler to v0.87.0 in https://github.com/libvips/build-win64-mxe/commit/3d230301710759ee8279179fd1320147342422d4. I could upload these binaries to S3, if you want to test this.

**Comment by kleisauke** [comment]
You can download the latest binaries (with Poppler v0.87.0 included) from the [build-win64-mxe repo](https://github.com/libvips/build-win64-mxe/releases).

I'll close this issue for now, without a reproduction file it'll be hard to debug further. Please re-open if you are able to provide the (standalone) code and input PDF that exhibit this behaviour.
