### ISSUE TITLE
Unable to delete original image file after calling NetVips.Image.Tiffsave

### ISSUE THREAD

**Issue by goarsna** [kleisauke/net-vips#6]
Hi,

I encounter errors trying to delete an input JPEG file after saving it to a TIFF file by calling NetVips.Image.Tiffsave(). Although Internal.GObject.GObjectUnref() and  Internal.VipsObject.VipsObjectUnrefOutputs() are called it seems that not all handles are released.

Are there any additional steps I have to take, to fully release handles on the input image?

I'm using libvips 8.6.3 and NetVips 1.0.2. If you need any further information just let me know.

Thank you in advance.

**Comment by kleisauke** [comment]
Hello, I think the file is being held open in libvips' cache.

You could try to set the file cache to zero:
```csharp
Operation.VipsCacheSetMaxFiles(0);
```

before saving it to a TIFF file. See [here](https://jcupitt.github.io/libvips/API/current/VipsOperation.html#vips-cache-set-max-files) for more info.

**Comment by goarsna** [comment]
Hey,

thank you for your quick response. Now i got it working. In addition to setting VipsCacheSetMaxFiles to 0 I also had to set VipsCacheSetMax to 0.

My solution now is calling this little method at program startup:

```
void InitializeNetVips()
{
	NetVips.ModuleInitializer.Initialize();
	NetVips.Operation.VipsCacheSetMax(0);
	NetVips.Operation.VipsCacheSetMaxFiles(0);
}
```

Thanks again for your help and the great work you did with NetVips!
