### ISSUE TITLE
Unable to get net-vips to work in Windows container

### ISSUE THREAD

**Issue by surgicalcoder** [kleisauke/net-vips#61]
Trying to get netvips working in a Windows container (image is  mcr.microsoft.com/dotnet/core/aspnet:3.1.1-nanoserver-1809),

No matter what I try, it refuses to load the DLLs with the following error:

System.DllNotFoundException: Unable to load DLL 'libvips-42.dll' or one of its dependencies: The specified procedure could not be found. (0x8007007F)
   at NetVips.Internal.VipsSourceCustom.New()
   at NetVips.SourceCustom..ctor()
   at NetVips.SourceStream..ctor(Stream stream)

I've tried including the NetVips.native package, I've also tried copying the entirety of Vips package to a path (c:\vips) and adding that into the PATH, with no luck.

Funnily enough, with just NetVips.native on linux (container is mcr.microsoft.com/dotnet/core/aspnet:3.1-buster-slim) it works fine.

**Comment by surgicalcoder** [comment]
Forgot to add, using NetVips v1.20 and NetVips.Native v8.9.1 from Nuget.

**Comment by hey-red** [comment]
Try place all native dlls along with your app dll(it's default behavior when publish).

**Comment by surgicalcoder** [comment]
Tried that, tried putting it into path, it's not complaining that it can't find the file (which is 0X8007007E, The specified module cannot be found), it's unable to load the procedure itself,

I have a feeling this may be because nanoserver does not contain GDI, and vips has dependency on GDI.

**Comment by surgicalcoder** [comment]
Running Depwalker, one of the ImageMagick dlls reference GDI, which is unavailable in Nanoserver.

I've build an Asp Net core container against Windows Server Core and that appears to be working - surgicalcoder/windowsservercore-netcore on Docker hub.

Closing this as it's not a Net Vips issue.

**Comment by kleisauke** [comment]
Glad it's resolved! 

> I have a feeling this may be because nanoserver does not contain GDI, and vips has dependency on GDI.

Note that only the [`NetVips.Extensions`](https://www.nuget.org/packages/NetVips.Extensions) NuGet package depends on GDI (for converting a bitmap to vips and vice versa). libvips itself (and thus the `NetVips.Native*` packages) does not depend on GDI.

**Comment by surgicalcoder** [comment]
@kleisauke I don't think that's entirely accurate from what I've seen - libvips-42.dll has a direct dependency on GDI32.dll according to dependency walker:

![image](https://user-images.githubusercontent.com/1169543/74359326-f6514b00-4dba-11ea-856f-17daaf1a2f08.png)

**Comment by kleisauke** [comment]
Ah, you're right. Looks like Cairo is the [only one that depends on `GDI32.dll`](https://user-images.githubusercontent.com/12746591/74532325-3df8e380-4f2f-11ea-85c2-fcacd561aa05.png). The `NetVips.Native*` NuGet packages are static linked so it will become a direct dependency of `libvips-42.dll`.

Fxed with https://github.com/libvips/build-win64-mxe/commit/acc156ccdcc4a8a6e0f14818b07f2eeb701a3c6, I now see:
![after](https://user-images.githubusercontent.com/12746591/74532330-418c6a80-4f2f-11ea-9893-da40d6f7e107.png)
<sup>(checked with https://lucasg.github.io/Dependencies/)</sup>

This Dockerfile seems to be working properly now:
```dockerfile
FROM mcr.microsoft.com/dotnet/core/sdk:3.1 AS build
WORKDIR /source

COPY *.csproj .
COPY local-packages local-packages/
RUN dotnet restore -r win-x64 -v n

COPY . .
RUN dotnet publish -c release -o /app -r win-x64 --self-contained false --no-restore

FROM mcr.microsoft.com/dotnet/core/runtime:3.1-nanoserver-1909
WORKDIR /app

COPY --from=build /app .
ENTRYPOINT ["dotnet", "NetVips.TestProgram.dll"]
```

Thanks for reporting this! The fix will be included in the forthcoming NetVips.Native release.

**Comment by surgicalcoder** [comment]
@kleisauke Do we have a date for when NetVips.Native will be released with those fixes? Am keen to try it out (and shrink the size of my containers while I'm at it)

**Comment by kleisauke** [comment]
I can't give any dates, unfortunately. I was waiting for libvips 8.9.2, but it hasn't been released yet. In the meantime, you could try testing these binaries:
https://github.com/libvips/build-win64-mxe/releases/tag/v8.9.1-static

I'm reopening this issue to keep track of it.

**Comment by kleisauke** [comment]
[NetVips.Native v8.9.2](https://www.nuget.org/packages/NetVips.Native/8.9.2) is now available.
