### ISSUE TITLE
Loading pdf file throws No such operation pdfload_buffer

### ISSUE THREAD

**Issue by tomrucki** [kleisauke/net-vips#62]
When trying to load pdf file on ubuntu 18 I'm getting this
![vips_exception](https://user-images.githubusercontent.com/25545240/74216859-fad80f80-4ca5-11ea-83af-387c4be336b9.png)

Any idea what could be wrong?

**Comment by kleisauke** [comment]
Hello, did you see https://github.com/kleisauke/net-vips/issues/11#issuecomment-402438726 ? To check if libvips was built with PDF support:
```bash
$ vips -l pdfload
          VipsForeignLoadPdfFile (pdfload), load PDF with libpoppler (.pdf), priority=0, is_a, get_flags, get_flags_filename, header, load
```

**Comment by tomrucki** [comment]
Thanks for responding so quickly. Yes I saw it and started digging deeper. I somehow managed to build it with pdfium. It seems to work.

**Comment by kleisauke** [comment]
I'm glad it works! Please feel free to re-open if questions remain.
