### ISSUE TITLE
DrawMask() with some form of transparent "opacity"?

### ISSUE THREAD

**Issue by blasky** [kleisauke/net-vips#63]
I have a mask file that I attempting to write to another, larger file. So far so good with DrawMask(). However, DrawMask() writes a solid color mask to the destination image. I'm trying to write the mask shape as a somewhat see through mask. How can I write the mask with an "opacity" level or other such blending to allow the original image to bleed through underneath the mask?
```
using (Image mask = Image.NewFromFile(maskFile.Path))
{
    finalImage = finalImage.DrawMask(color, mask, p.x, p.y);
}
```
Thanks.

**Comment by kleisauke** [comment]
I think you're looking for the `image.Composite` function. This will blend a pair of images with a blend mode. For example:
```csharp
using var main = Image.NewFromFile("Gugg_coloured.jpg", access: Enums.Access.Sequential);
using var mask = Image.NewFromFile("PNG_transparency_demonstration_1.png", access: Enums.Access.Sequential);

// composite the two images using the PDF "over" mode
using var composite = main.Composite(mask, Enums.BlendMode.Over, x: 100, y: 100);

composite.WriteToFile("composite.jpg");
```

To make:
![composite](https://user-images.githubusercontent.com/12746591/74337874-6f43a900-4da1-11ea-91fb-4756bb601cac.jpg)

See [`vips_composite()`](https://libvips.github.io/libvips/API/current/libvips-conversion.html#vips-composite) for more details.

**Comment by blasky** [comment]
Awesome. I've been experimenting with DrawMask(), Insert(), Embed(), etc., but somehow I missed Composite(). Thank you!

I've got it working and it is definitely the direction I need to go. But I do see that the transparent alpha channel in my png mask file is getting blended with the main image in such a way that you can see the outline of the mask image as faintly darker than the original.

I've been playing with the BlendMode options and will continue to, but is there a choice or another process that will guarantee that the blend will not alter the main pixel underneath an alpha pixel during the Composite operation? (Hope that makes sense.)

**Comment by kleisauke** [comment]
Looks like you're describing the atop blend mode (`Enums.BlendMode.Atop`), but I'm not sure.

The Cairo docs have a nice explanation of all the blend modes: https://www.cairographics.org/operators/ (the non-separable modes are not implemented within libvips)

**Comment by kleisauke** [comment]
Hope this helped, please feel free to re-open if questions remain.
