### ISSUE TITLE
Can shrink on load be used with streams?

### ISSUE THREAD

**Issue by kDanil** [kleisauke/net-vips#64]
Hi,

I'm slowly migrating to streams and haven't found replacement for ShrinkJpegOnLoad with stream as a parameter.

How correctly apply Shrink operation on early stage with streams?
Does it mean that I would have performance degradation using streams?

Thanks

**Comment by kleisauke** [comment]
Hello @kDanil,

The `ThumbnailSource` and `ThumbnailStream` operations does support JPEG's shrink-on-load feature. You can see how it's handled in libvips here:
https://github.com/libvips/libvips/blob/54ff9dabf7e20e01d4ee07183b24ab6861909192/libvips/resample/thumbnail.c#L1301-L1358

[`thumbnail_image()`](https://libvips.github.io/libvips/API/current/libvips-resample.html#vips-thumbnail-image) (`ThumbnailImage` within NetVips) is the only operation that doesn't support any of the shrink-on-load tricks, so I'd avoid that (if possible).

**Comment by kleisauke** [comment]
To check if it's actually using the shrink-on-load features you can set the `G_MESSAGES_DEBUG=VIPS` environment variable and GLib will display informational and debug messages from libvips.

You can also do this in the code, for example:
```csharp
var handlerId = Log.SetLogHandler("VIPS", Enums.LogLevelFlags.All, (domain, level, message) =>
{
    Console.WriteLine(message);
});

using (var input = File.OpenRead("lichtenstein.jpg"))
{
    var thumbnail = Image.ThumbnailStream(input, 300, height: 300);
    Console.WriteLine(thumbnail.ToString());

    using var output = File.OpenWrite("thumbnail-stream.jpg");
    thumbnail.WriteToStream(output, ".jpg");
}

Log.RemoveLogHandler("VIPS", handlerId);
```

Output:
```
thumbnailing source
selected loader is VipsForeignLoadJpegSource
input size is 1967 x 2421
loading with factor 4 pre-shrink
pre-shrunk size is 491 x 605
converting to processing space srgb
residual reducev by 0.495868
reducev: 13 point mask
reducev: using vector path
reducev sequential line cache
residual reduceh by 0.495868
reduceh: 13 point mask
<NetVips.Image 243x300 uchar, 3 bands, srgb>
```

**Comment by kleisauke** [comment]
Hope this helped, please feel free to re-open if questions remain.
