### ISSUE TITLE
Question : .Net Equivalent of color search replace

### ISSUE THREAD

**Issue by CanadianHusky** [kleisauke/net-vips#66]
Hello,

Can someone please share the the Netvips .NET binding equivalent of this code taken from

https://github.com/libvips/libvips/issues/884

Is there a link with more advanced .Net use example other than the 'Getting Started' page at https://kleisauke.github.io/net-vips/tutorial/getting_started.html

thank you
```
require 'vips'

image = Vips::Image.new_from_file ARGV[0], access: :sequential

# the colour we search for as an RGB triple 
match = [40, 100, 90]

# find  euclidean distance between each RGB pixels in the input and our match
# colour
distance = Vips::Image.sum(((image - match) ** 2).bandsplit) 

# swap pixels more than 50 away for white
image = (distance > 50 ** 2).ifthenelse([255, 255, 255], image)

image.write_to_file ARGV[1]
```

**Comment by kleisauke** [comment]
Hello @CanadianHusky,

There is not so much difference between the Ruby and C# libvips binding. This could be written in C# as:

```csharp
var image = Image.NewFromFile(args[0], access: Enums.Access.Sequential);

// the colour we search for as an RGB triple 
var match = new [] {40, 100, 90};

// find euclidean distance between each RGB pixels in the input and our match
// colour
var distance = Image.Sum((image - match).Pow(2).Bandsplit());

// swap pixels more than 50 away for white
image = (distance > Math.Pow(50, 2)).Ifthenelse(new []{255, 255, 255}, image);

image.WriteToFile(args[1]);
```

The power operator (`**` in Ruby) in C# doesn't exist, so these are written as `Math.Pow` and `image.Pow`. Other than that, all methods are almost the same, there is only a small difference between the snake_case -> PascalCase naming conventions.

More advanced samples can be found in the [NetVips.Samples](https://github.com/kleisauke/net-vips/tree/master/samples/NetVips.Samples/Samples) project.

**Comment by CanadianHusky** [comment]
Fantastic. Thank You. 
Execution speed is impossible to match with any other library and extreme large bitmaps that will cause out of memory work fine as well
