### ISSUE TITLE
how to set VIPS_DISC_THRESHOLD

### ISSUE THREAD

**Issue by CanadianHusky** [kleisauke/net-vips#70]
Hello,

Is the flag VIPS_DISC_THRESHOLD a variable within the Netvips/Libvips system that is set via code ? If yes, how do we set it, or is it an Environment variable of the Operation System ? Can someone please supply an example.

I want to load images that use less then 1 GB (uncompressed memory) directly into memory by setting the memory = true flag at the open command 
`Image.NewFromFile(inputfile, True, access:=Enums.Access.Sequential);`
and larger images over temp file to avoid excessive memory usage. What is the best way ?

thank you

**Comment by kleisauke** [comment]
Currently this can only be changed by setting the `VIPS_DISC_THRESHOLD` environment variable or passing the `--vips-disc-threshold` flag via the command-line. 

To create an environment variable stored in the current process, you can do this in C#:
```csharp
Environment.SetEnvironmentVariable("VIPS_DISC_THRESHOLD", "1g");

var image = Image.NewFromFile("huge.jpg", access: Enums.Access.Sequential);
```

@jcupitt Is it perhaps useful to add a convenience function, just like `vips_pipe_read_limit_set()`, to make it easier to change this threshold (e.g. `void vips_set_disc_threshold( size_t threshold )`)?

**Comment by CanadianHusky** [comment]
thank you!

do I assume correct that strings like below have the expected format
Environment.SetEnvironmentVariable("VIPS_DISC_THRESHOLD", size_string);

"200m" = 200 Megabytes
"500k" = 500 Kbytes

**Comment by kleisauke** [comment]
> do I assume correct that strings like below have the expected format
> Environment.SetEnvironmentVariable("VIPS_DISC_THRESHOLD", size_string);
> 
> "200m" = 200 Megabytes
> "500k" = 500 Kbytes

Yes, sizes can be specified in bytes, kilobytes (suffix k) or megabytes (suffix m), for example, `1024`, `8k`, `1m`. You can also specify gigabytes using the g suffix.

**Comment by jcupitt** [comment]
@kleisauke We're going to have a lot of API if we have convenience functions for all these settings :(

If C# has a nice setenv function, perhaps that's the best way to control these things?

**Comment by CanadianHusky** [comment]
Me personally I am totally fine the suggested Environment.SetEnvironmentVariable("VIPS_DISC_THRESHOLD", size_string);

**Comment by kleisauke** [comment]
I agree, if a similar `setenv` function is available, that's probably the best way to control these things. I think every programming language supports that these days.

An alternative way to avoid implementing every setting within the API is to use .ini-like configuration files. For example, a configuration file could look like this:

<details>
  <summary>Details</summary>
  
```ini
[vips]

## General settings

# Can take a unit postfix of "k", "m" or "g" to indicate kilobytes, megabytes or gigabytes
disc_threshold=100m # default 100m
pipe_read_limit=1g # default 1g
min_stack_size=0 # do nothing below 2m

## Concurrency / vectorization

concurrency=0 # 0 = default (the number of threads available on the host machine)
vector_enabled=true

## Caching

cache_max=100 # the maximum number of operations to cache (default 1000 operations)
cache_max_mem=50m # the maximum memory in MB to use for this cache (default 50m)
cache_max_files=20 # the maximum number of files to hold open (default 20 files)

## Logging

log_level=warning # or info, debug, etc.

## Plugins / foreign

plugin_dir=/home/vips-plugins-8-10 # https://github.com/libvips/libvips/issues/1141

# Disable builtin-loaders on runtime
# (can be useful for reducing the attack surface)
foreign_disabled=heifload;heifsave;pdfload;magickload;magicksave
```
</details>

The configuration file could be read/parsed during `vips_init` using GLib's key file parser. But I'm not sure if libraries are supposed to do this kind of things.
