### ISSUE TITLE
Checkerboard pattern on transparency

### ISSUE THREAD

**Issue by kalozka1** [kleisauke/net-vips#73]
Hi,

I need to generate jpg thumbnail for some tiff or png images which has transparency in it.
How can i make the transparent parts turn to a checkerboard patterned area?
The thumb generation works well when i turn the transparent part to a solid color (ex. white), but the goal is the checkerboard pattern...

Can someone tell me how to do this?

Istvan

**Comment by CanadianHusky** [comment]
create a seperate background image with the checkboard pattern that is large enough for the thumbnail
then use the foreground as a mask and compose the foreground thumbnail with the background
see documentation for the Image.ifthenelse() function how to compose 2 images

here is some pseudo code
mask = foreground.colorspace("b-w") < threshold
result = mask.ifthenelse(foreground, background, false)

**Comment by kalozka1** [comment]
@CanadianHusky thanks for the suggestion, now I'm looking into that direction.
I will posit it when i have some results.

**Comment by CanadianHusky** [comment]
I didn't think its a complex task, so I gave you pseudo code only.
There isn't much to look into...., its a one liner. Here is the working code

```
    Dim thumbnail As Image = Image.Pngload("c:\temp\otter-tr.png")
        Dim background As Image = Image.Pngload("c:\temp\background.png")
        Dim result As Image = (thumbnail.Colourspace("b-w") < 254)(0).Ifthenelse(thumbnail, background, False)
        result.Pngsave("C:\temp\output.png")

```

input file has transparent background, white will work too : 
![image](https://user-images.githubusercontent.com/35332003/80475912-508d9100-8952-11ea-8ebf-b69831dfc480.png)

background file:
![image](https://user-images.githubusercontent.com/35332003/80475967-68fdab80-8952-11ea-91bb-8fb0f16aa47b.png)

result:
![image](https://user-images.githubusercontent.com/35332003/80476032-79158b00-8952-11ea-94a2-6e7f98cd57d8.png)

crop the result to whatever size you like with Image.ExtractArea or Image.Crop function if the background and foreground images are not the same size

**Comment by kalozka1** [comment]
That's right! Thx!

**Comment by kleisauke** [comment]
SVG images are ideal for this. Try something like this:

```csharp
// Single checker size in pixels
const int checkerSize = 10;

// Single checker opacity as percentage
const int checkerOpacity = 25;

var main = Image.NewFromFile("images/PNG_transparency_demonstration_1.png", access: Enums.Access.Sequential);
var svg = $@"
<svg width='{main.Width}' height='{main.Height}'>
  <!-- Let's define the pattern -->
  <!-- The width and height should be double the size of a single checker -->
  <pattern id='pattern-checkers' x='0' y='0' width='{checkerSize * 2}' height='{checkerSize * 2}' patternUnits='userSpaceOnUse'>
    <!-- Two instances of the same checker, only positioned apart on the `x` and `y` axis -->
    <rect x='0' y='0' width='{checkerSize}' height='{checkerSize}'></rect>
    <rect x='{checkerSize}' y='{checkerSize}' width='{checkerSize}' height='{checkerSize}'></rect>
  </pattern>

  <!-- Define the shape that will contain our pattern as the fill -->
  <rect x='0' y='0' width='100%' height='100%' fill='url(#pattern-checkers)' fill-opacity='.{checkerOpacity}'></rect>
</svg>";
var background = Image.NewFromBuffer(svg, access: Enums.Access.Sequential);

var output = background.Composite(main, Enums.BlendMode.Over);
output.WriteToFile("checkerboard.png");
```

To make:
![checkerboard](https://user-images.githubusercontent.com/12746591/80497383-a8d08d00-896a-11ea-9b1c-ab5c3509b9c4.png)

**Comment by kalozka1** [comment]
Thnx @kleisauke, it works like clock! The quality is way better than what i could achieve so far. I think this quality can be good to go to production :)
Have a nice day!
