### ISSUE TITLE
Question: how to count Pixels

### ISSUE THREAD

**Issue by CanadianHusky** [kleisauke/net-vips#75]
Hello,

I have a pure black/white image created with something like
`img = img.colorspace("b-w") > 128`

how can I get the **count** of black/white pixels ?

Thank you

**Comment by kleisauke** [comment]
A simple way of doing this is to take a histogram of the image.

https://libvips.github.io/libvips/API/current/libvips-arithmetic.html#vips-hist-find-ndim

For example, in C#:
```csharp
const int nBins = 2;

var im = Image.Black(50, 100);
var test = im.Insert(im.NewFromImage(255), 40, 0, expand: true);

// make a 3D histogram of the image ... 2 bins in each axis
var hist = test.HistFindNdim(bins: nBins);

var blackCount = hist[0, 0][0];
var whiteCount = hist[1, 0][0];

Console.WriteLine($"Number of black pixels = {blackCount}"); // 4000
Console.WriteLine($"Number of white pixels = {whiteCount}"); // 5000
```
