### ISSUE TITLE
How can I get in touch with the contributors of this project?

### ISSUE THREAD

**Issue by kalozka1** [kleisauke/net-vips#76]
Sorry for the unconventional way, but i feel a bit stuck...
I would like to talk to the contributors of this project.
Can someone give me maybe an email address?

**Comment by kleisauke** [comment]
Although it's tempting, don't reach out to maintainers privately unless you need to share sensitive information (such as security issues). When you keep the conversation public, more people can learn and benefit from your exchange. Discussions can be, in themselves, contributions.

https://opensource.guide/best-practices/#keep-communication-public

**Comment by kalozka1** [comment]
You are completely right.
I work for a company dealing with images and I'm looking for someone who has the knowledge to help us out in image related questions and I thought that the people who has the knowledge to write this library may also capable to help us.
I sent you a mail @kleisauke to info@kleisauke.nl address about a week ago. Did I miss the address?

**Comment by kleisauke** [comment]
That e-mail is correct, but please use it only for security issues as I'm not open for private consultancy.

If you work at a for-profit organisation that relies on NetVips, consider donating to the libvips OpenCollective at https://opencollective.com/libvips to say thank you and help with its continued support.

**Comment by kalozka1** [comment]
Thanks for the answer!
