### ISSUE TITLE
Question: Colored canvas using Image.NewFromMemory

### ISSUE THREAD

**Issue by jupagose** [kleisauke/net-vips#77]
I have this piece of code from samples

`var a = Image.NewFromMemory(Enumerable.Repeat((byte)255, 1200).ToArray(), 20, 20, 3, "uchar")`

It makes an image of 20x20 white, if I change (byte)255 to (byte)0 color change to black, any other value change color to gray, How can I do to generate a canvas for example white, blue or any RGB combination?

**Comment by CanadianHusky** [comment]
I struggled with the same how to create canvas or blank images at any size and color until I understood the principles of the underlying libvips and the what the artithmetic operation like + (plus) means within the context of images

here is how I do it

```
Dim img As Image = Image.Black(800, 600, 3) ; create 3 channel (RGB) image with Black. All pixels are{0,0,0}
img = img + {150, 200, 100} ; add the RGB values, this makes lime green
img.WriteToFile("c:\temp\test.jpg")
```

**Comment by jupagose** [comment]
@CanadianHusky Tks for answer , I'm trying to understand second line 
`img = img + {150,200,100};` 
I'm trying to port this instruction to  c#

**Comment by kleisauke** [comment]
There's also a convenience function for this. 
https://libvips.github.io/libvips/API/current/VipsImage.html#vips-image-new-from-image

This creates a constant image of an existing image. The image that is returned will have the same size, interpretation, resolution and format as the image you call it on, but with every pixel having the constant value you specify.

For example, in C#:
```csharp
var im = Image.Black(100, 100);
var limeGreen = im.NewFromImage(50, 205, 50);

limeGreen.WriteToFile("lime-green.png");
```
