### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by auriou** [kleisauke/net-vips#78]
I used Netvips in one of my controllers in .net core 3.1 and I noticed that objects were not released
memory usage is constantly increasing

        [ApiController]
        [Route("/")]
        public class ImageController : ControllerBase
        {
        [HttpGet("test/{*imageUri}")]
        public ActionResult GetTest(string imageUri)
        {
            var file = Path.Combine(@"C:\Temp\dam", imageUri);
            if (!System.IO.File.Exists(file)) return BadRequest();
            using (var stream = System.IO.File.OpenRead(file))
            {
                using (var image = Image.NewFromStream(stream))
                {
                    using (var memory = new MemoryStream())
                    {
                        image.JpegsaveStream(memory);
                        memory.Seek(0, SeekOrigin.Begin);
                        var bytes = memory.ToArray();
                        return base.File(bytes, "image/jpeg");
                    }
                }
            }
        }

![image](https://user-images.githubusercontent.com/1873587/82209637-e3946800-990d-11ea-937e-280fe136b620.png)

here are the objects not released, how to solve this problem, I have disposed all the objects!

![image](https://user-images.githubusercontent.com/1873587/82210170-d330bd00-990e-11ea-85e7-12d2f7c91653.png)

![image](https://user-images.githubusercontent.com/1873587/82210273-04a98880-990f-11ea-80af-f4ea927d3b41.png)

**Comment by auriou** [comment]
here I made 4 calls, and none of my items were released

![image](https://user-images.githubusercontent.com/1873587/82212870-856a8380-9913-11ea-9473-f514fbfe85bb.png)

**Comment by auriou** [comment]
I no longer have the problem when I use

buffer = image.JpegsaveBuffer();

**Comment by kleisauke** [comment]
Thanks for reporting this! It's not strictly a leak -- if you let the program run to the end, all memory is freed. Nevertheless, the associated streams were freed early for the `NewFromStream` and `WriteToStream` functions within commit 7a7543f, but somehow I forgot to do this for the automatically generated stream functions (`*loadStream` / `*saveStream`) as well. 

Commit https://github.com/kleisauke/net-vips/commit/1cc64ba8a18946d3835a6711cab4d0cb69b413cb should fix this. If you want to test this, you can use the nightly version of NetVips. Add the `https://ci.appveyor.com/nuget/net-vips` feed in the `<packageSources>` section of your `NuGet.config`:
```xml
<packageSources>
  <add key="netvips-nightly" value="https://ci.appveyor.com/nuget/net-vips" />
</packageSources>
```

And update NetVips to 1.2.1 (build number 184 - prerelease). I'll make a new release soon.

**Comment by auriou** [comment]
I could only check this on Monday, thanks

**Comment by auriou** [comment]
![image](https://user-images.githubusercontent.com/1873587/82876824-ad706d00-9f39-11ea-904a-02058c90f1d1.png)

it's good the objects are well released

**Comment by kleisauke** [comment]
[NetVips v1.2.2](https://www.nuget.org/packages/NetVips/1.2.2) is now available. Thanks for testing!
