### ISSUE TITLE
An unhandled exception of type 'System.TypeInitializationException' occurred in System.Windows.Forms.dll

### ISSUE THREAD

**Issue by cqpx** [kleisauke/net-vips#8]
Hi Kleis,

I've been trying to solve this issue myself for a few days and still don't know how.
The steps I've done today:

1. Install a new copy of Windows 10 64-bit in Virtualbox
2. Install Visual Studio Community and choose only C# Form Application Development.
3. Start Visual Studio and create a Console Application, install NetVips 1.0.3 from Nuget manager in the Reference section.
4. Paste the test code from net-vips README to main() function, using NetVips and build.

The error will stop the execution.

Any steps I missed?
Thank you.

**Comment by FullSpectrumLaser** [comment]
Hi cqpx:

Ensure the Build->"Prefer 32-bit" checkbox is unchecked for the project. Even when running with "Any CPU" enabling this checkbox will result in a x86 compiled winforms app calling into x64 libvips binaries which is included in the nuget package. You may see HRESULT: 0x8007000B as part of the exception.

On a side note, calling x86 libvips binaries also do not work, but I've created a separate issue for this.

**Comment by cqpx** [comment]
Thank you very much, Phil. @FullSpectrumLaser

**Comment by kleisauke** [comment]
I never understood why "Prefer 32-bit" is set by default when compiling for "Any CPU". Hopefully this option will be turned off by default in the future.

Anyway, I'll update the readme with Phil's advice. Thanks for reporting!
