### ISSUE TITLE
Why do osx-x64 and linux-x64 not have targets?

### ISSUE THREAD

**Issue by jsm174** [kleisauke/net-vips#80]
I'm helping out on a project that uses NetVips and would like to get it running on macOS. 

The project file currently has a reference:

```
	<Import Project="..\.packages\NetVips.Native.win-x64.8.9.2\build\net45\NetVips.Native.win-x64.targets" Condition="Exists('..\.packages\NetVips.Native.win-x64.8.9.2\build\net45\NetVips.Native.win-x64.targets')" />
```

In `AfterBuild`, there is a copy step that copies the dll's to a vendor directory.

```
	<Target Name="AfterBuild">
		<ItemGroup>
			<BuildFiles Include="$(OutDir)*.dll;$(OutDir)*.xml" Exclude="$(OutDir)Unity*;$(OutDir)VisualPinball.*;$(OutDir)MiniZ32.dll;$(OutDir)System.Runtime.CompilerServices.Unsafe.*" />
		</ItemGroup>
		<Copy SourceFiles="@(BuildFiles)" DestinationFolder="..\VisualPinball.Unity\Vendor" SkipUnchangedFiles="true" />
	</Target>
```

To get it running in macOS, I figured I could do the same with the osx-64 package and then just update `AfterBuild` to include `$(OutDir)*.dylib` 

```
	<Import Project="..\.packages\NetVips.Native.osx-x64.8.9.2\build\net45\NetVips.Native.osx-x64.targets" Condition="Exists('..\.packages\NetVips.Native.osx-x64.8.9.2\build\net45\NetVips.Native.osx-x64.targets')" />
```

However, this does not work, because there does not seem to be a targets directory in the osx or the linux packages:

https://github.com/kleisauke/net-vips/blob/master/build/native/NetVips.Native.win-x64.nuspec#L26-L35

vs 
 
https://github.com/kleisauke/net-vips/blob/master/build/native/NetVips.Native.osx-x64.nuspec#L26-35

I'm pretty new at nuget, so I apologize if the answer is obvious.

**Comment by kleisauke** [comment]
Hi @jsm174,

Copying binaries (i.e. *.DLL files) to the target directory is only necessary for .NET Framework and not needed for .NET Core targets, as far as I know.

Therefore, the [`<package_id>.targets`](https://github.com/kleisauke/net-vips/tree/master/build/native/targets) files, which NuGet will automatically import, have been omitted from the nuspec file of the [`NetVips.Native.osx-x64`](https://github.com/kleisauke/net-vips/blob/master/build/native/NetVips.Native.osx-x64.nuspec), [`NetVips.Native.linux-x64`](https://github.com/kleisauke/net-vips/blob/master/build/native/NetVips.Native.linux-x64.nuspec) and [`NetVips.Native.linux-musl-x64`](https://github.com/kleisauke/net-vips/blob/master/build/native/NetVips.Native.linux-musl-x64.nuspec) NuGet packages because .NET Framework is not available on Mac or Linux operating systems.

**Comment by jsm174** [comment]
@kleisauke - Thank you. I'm still trying to put all the pieces of the puzzle together. 

The project I mentioned above does target .NET Framework 4.7.2, and I'm able to compile it in Visual Studio for Mac. (It runs in Unity.)

So maybe VS is using Mono for the .NET Framework? In the about I'm seeing:

Mono Framework MDK
Runtime:
	Mono 6.10.0.104 (2019-12/5d03a6fe116) (64-bit)
	Package version: 610000104

If that is the case, having targets for OSX and Linux technically could be valid?

**Comment by jsm174** [comment]
@kleisauke - One more thing, I needed to make a library cross platform for the above project, and I modeled it heavily off of NetVips: https://github.com/jsm174/net-miniz

Anyway, I added targets to osx:  https://github.com/jsm174/net-miniz/blob/master/native/targets/NetMiniZ.Native.osx-x64.targets

And this does work in Visual Studio Mac / Unity / Mono?

Would it be possible to get the targets added when https://github.com/lovell/sharp-libvips/issues/39#issuecomment-631345789 gets implemented?

**Comment by kleisauke** [comment]
I did some tests with Mono on Linux and macOS and it looks like you are right. Mono also requires that the binaries are copied to the output folder.  Commit https://github.com/kleisauke/net-vips/commit/f89898c5489d7d3433240bade298de37413b4553 add these build targets for the Mono runtime on Linux (musl, glibc) and macOS. This is released as `v8.9.2-build2` [on NuGet](https://www.nuget.org/packages/NetVips.Native/8.9.2-build2).

The `v8.9.2-build2` release also includes a statically linked libvips binary for macOS (https://github.com/kleisauke/libvips-packaging/issues/1), which reduces the amount of dylibs from 33 to 2.

Thanks for reporting!

**Comment by jsm174** [comment]
@kleisauke - Wow! This is fantastic! Thank you very much!

**Comment by freezy** [comment]
Thanks guys, this is awesome.
