### ISSUE TITLE
Files locked after dispose

### ISSUE THREAD

**Issue by gil-c** [kleisauke/net-vips#84]
Hello,

I found the issue: https://github.com/kleisauke/net-vips/issues/12

I think there is a similar one that can be reproduced with this code:

```
const string file = @"D:\Temp\temp.vips";

try
{
    using (var image = Image.Black(1000, 800))
    {
        image.Vipssave(file);

        using (var image2 = Image.NewFromFile(file))
        {
        }

    }
}
catch (Exception ex)
{
    Console.WriteLine(ex.Message);
}
finally
{
    try
    {
        File.Delete(file);
        Console.WriteLine($"Successfully deleted {file}");
    }
    catch (Exception)
    {
        Console.WriteLine($"{file} couldn't be deleted");
    }
}
```

Just saving an image and disposing it doesn't lock the file. But it does when we read the image2. And it is only with the .vips format (Vipssave). It works fine with Tiffsave.

**Comment by kleisauke** [comment]
This is a known issue. `vips_vipsload`/`vips_vipssave` and `vips_rawload`/`vips_rawsave` (see https://github.com/kleisauke/net-vips/issues/45#issuecomment-571682546) needs to be reworked for the new source/target API. This ensures that files are closed early and prevents them from being locked.

See https://github.com/libvips/libvips/issues/1541 for an overview of the remaining loaders and savers that might be reworked.

**Comment by kleisauke** [comment]
`vips_vipsload` / `vips_vipssave` was reworked in libvips 8.11, so the above issue can no longer be reproduced.

I'll close, let's track further enhancements at https://github.com/libvips/libvips/discussions/2051.
