### ISSUE TITLE
ASP.NET Framework 4.7.2 Installed via Install-Package NetVips has missing dll's

### ISSUE THREAD

**Issue by ZENUAV** [kleisauke/net-vips#85]
I have the project targeting x64 and still get the following error.

It looks like no other dll apart from NetVips has been installed?

From what I have read, it should install all dependencies as part of nuget package?

`Unable to load DLL 'libvips-42.dll': The specified module could not be found.`

```
Attempting to gather dependency information for package 'NetVips.1.2.3' with respect to project 'XXX', targeting '.NETFramework,Version=v4.7.2'
Gathering dependency information took 956.64 ms
Attempting to resolve dependencies for package 'NetVips.1.2.3' with DependencyBehavior 'Lowest'
Resolving dependency information took 0 ms
Resolving actions to install package 'NetVips.1.2.3'
Resolved actions to install package 'NetVips.1.2.3'
Retrieving package 'NetVips 1.2.3' from 'nuget.org'.
Adding package 'NetVips.1.2.3' to folder 'C:\XXX\Web\XXX\packages'
Added package 'NetVips.1.2.3' to folder 'C:\XXX\Web\XXX\packages'
Added package 'NetVips.1.2.3' to 'packages.config'
Successfully installed 'NetVips 1.2.3' to XXX
Executing nuget actions took 1.28 sec
Time Elapsed: 00:00:02.3801399
```
Please advise on what I should do to get this working.

**Comment by jsm174** [comment]
Did you also install the native dlls?

https://www.nuget.org/packages/NetVips.Native.win-x64/

**Comment by ZENUAV** [comment]
I have now installed NetVips and NetVips.Navtive.win-x64 and it does run on my local machine now!

But it's not running when publish to live site, so I need to look into that. It's an Azure Web App running in 64bit mode, so it should work?

**Comment by ZENUAV** [comment]
I'm still getting the exception

`Unable to load DLL 'libvips-42.dll': The specified module could not be found. (Exception from HRESULT: 0x8007007E)`

on the live site?

**Comment by ZENUAV** [comment]
I have it working now. These are the steps I had to take.

1. Add VIPS dll's to a folder in my project called VIPS
2. Create post-build event to copy files from VIPS to /bin

`xcopy "$(ProjectDir)VIPS\*.dll" "$(TargetDir)" /Y`

The dlls are now available and working great!!

**Comment by kleisauke** [comment]
I'm glad it's working now! Indeed, you'll need the the [`NetVips.Native`](https://www.nuget.org/packages/NetVips.Native/) NuGet package if you don't use a globally installed libvips. It may also be necessary to adjust your 64-bit or 32-bit setting, depending on the libvips you are using, see: https://github.com/libvips/libvips/issues/1608#issuecomment-615256089.

A post-build event seems a little redundant to me. Isn't it possible to include native NuGet packages within Azure?

**Comment by kleisauke** [comment]
I hope this information helped. Please feel free to re-open with more details if further assistance is required.
