### ISSUE TITLE
JP2 Image Conversion in C#

### ISSUE THREAD

**Issue by broy-github** [kleisauke/net-vips#87]
I want to convert an image to JP image using NetVips in C#.
But, NetVips is not detecting JP2 image type.
Please let me know if it's possible.

**Comment by kleisauke** [comment]
Hello, JP2K images are loaded via libMagick. The `NetVips.Native.*` NuGet packages does not include *magick. To take advantage, you will need to compile your own libvips with support for *magick and install it globally. This is easy to do on Linux or macOS.

On Windows you'll need to download the [`vips-dev-w64-all-x.y.z.zip`](https://github.com/libvips/build-win64-mxe/releases) libvips binary and add the `vips-dev-x.y\bin` directory to your `PATH` environment variable. I've written a complete tutorial [here](https://github.com/kleisauke/net-vips/issues/3#issuecomment-386236773). 

It is recommended to uninstall the `NetVips.Native.*` package(s) if you are using a globally-installed libvips to avoid conflicts between binaries.

**Comment by broy-github** [comment]
Hello,

Can it be directly implemented in my project without making any changes in path of environment variable, please?

**Comment by kleisauke** [comment]
You could try to place the DLLs in the directory from which the application is loaded (see [the standard DLL search order](https://docs.microsoft.com/en-us/windows/win32/dlls/dynamic-link-library-search-order#standard-search-order-for-desktop-applications)).

Alternatively, see https://github.com/kleisauke/net-vips/issues/15#issuecomment-417629143 for a detailed instruction to set the libvips binary directory at runtime (i.e. in a separate directory without changing any environment variables).

**Comment by kleisauke** [comment]
I hope this information helped. Please feel free to re-open with more details if further assistance is required.
