### ISSUE TITLE
Can You support Linux ARM64 version

### ISSUE THREAD

**Issue by CrazyJson** [kleisauke/net-vips#88]
Hello, using NetVips picture processing package, found that the performance is very good;Currently, this package is required to be used on Linux ARM64. There is no official version of this package, and I tried to compile it myself but failed. Could you please help to compile a Linux ARM64 package；

https://github.com/kleisauke/libvips-packaging/releases
![image](https://user-images.githubusercontent.com/8163485/86804212-510c7b80-c0a9-11ea-9965-e6719aca4b1c.png)

**Comment by CrazyJson** [comment]
I found the record of ARM64V8 in your package release record. Is there any record support

**Comment by kleisauke** [comment]
Let's track this in https://github.com/kleisauke/libvips-packaging/issues/3.
