### ISSUE TITLE
How to build NetVips.Native.linux-x64 with WebP support?

### ISSUE THREAD

**Issue by fredprodibi** [kleisauke/net-vips#89]
Hello, I have added the package NetVips.Native.linux-x64 from Nuget and it works great. However I would need the support for webp.

Does someone has the build for that, or info on how to do it?

Thank you

**Comment by kleisauke** [comment]
Loading and saving WebP images should already be supported within all prebuilt binaries (NetVips.Native.*).

**Comment by fredprodibi** [comment]
Thank you! it works it was path issue!

I tried with HEIC but this doesn't seems to be built in, how can I add this support?

Thank you

**Comment by kleisauke** [comment]
Reading and writing HEIF images requires a custom, globally-installed libvips that has itself been compiled with support for libheif. You'll also need libde265 for decoding HEVC files and optionally x265 for encoding.

The prebuilt binaries *will not* include libde265/x265 (and will never include patent-encumbered HEVC-related logic).

Note that the royalty-free AVIF format is currently being considered for addition to the prebuilt binaries, see:
https://github.com/lovell/sharp/issues/2289#issuecomment-657580232

**Comment by fredprodibi** [comment]
Thank you very much, the avif support is a very welcome news!

I close the issue as you have helped me a lot.

**Comment by kleisauke** [comment]
[NetVips.Native v8.10.5(.1)](https://www.nuget.org/packages/NetVips.Native/8.10.5.1) is now available with prebuilt binaries that contain libaom and libheif for full AVIF decoding and encoding support.
