### ISSUE TITLE
Linux: NetVips.VipsException: unable to write to buffer VipsForeignSave: "��G��" is not a known buffer format

### ISSUE THREAD

**Issue by BurtonShane** [kleisauke/net-vips#9]
Hi,
I am unable to use Image.WriteToBuffer() in a Linux Docker image.

I'm passing in the extension like shown in the documentation:
`imageBytes = img.WriteToBuffer(".png");`

This works perfectly fine when running in Windows, but in Linux it throws an exception like "NetVips.VipsException: unable to write to buffer VipsForeignSave: "��	p�" is not a known buffer format". 

Tested in both Ubuntu and Alpine Docker images, using the same libvips install/build steps as from [here](https://github.com/kleisauke/net-vips/blob/master/Dockerfile)

Image.WriteToFile() works in Linux, but i'd prefer not to have to save things to temp files if i can avoid it

**Comment by kleisauke** [comment]
Hi Shane,

Thanks for reporting this bug! It's fixed with d96fab4 (it was due to a string pointer which was freed too early).

I've also added a unit test to ensure that this will never happen again. I'll publish a new version (1.0.4) on NuGet today.

**Comment by kleisauke** [comment]
NetVips 1.0.4 is now available on NuGet.

**Comment by BurtonShane** [comment]
Thanks for the quick fix! I tested and can confirm its working now
