### ISSUE TITLE
Image Interpretation Issue with 8bpp images

### ISSUE THREAD

**Issue by ajblair-wavedyn** [kleisauke/net-vips#91]
I need to load many 8bpp images from byte arrays and insert them into a large mosaic image. The problem I am having is if I create a black image:

var mosaic = NetVips.Image.Black(arrayX, arrayY, bands:1);

it returns with the interpretation set to 'multiband'. When I read in the byte arrays and converty them to images:

tile = NetVips.Image.NewFromMemory(bytes[l], lensletbmp.Width, lensletbmp.Height, 1, "uchar");

the tile returns with interpretation 'b-w'.

When I insert the tile images into the larger image the image stays black. If I create the mosaic image from a 8bpp file, it works correctly. The large images will be all different sizes, so using a file as the starting point won't work. Is there a way to change the interpretation of the mosaic image to 'b-w'?  Thanks.

**Comment by kleisauke** [comment]
Hi @ajblair-wavedyn,

Sorry for the delay. You can use [`.Copy`](https://libvips.github.io/libvips/API/current/libvips-conversion.html#vips-copy) to set the interpretation to `b-w` (i.e. a single-band image).
```csharp
const int arrayX = 100;
const int arrayY = 100;
var mosaic = Image.Black(arrayX, arrayY, bands: 1).Copy(interpretation: "b-w");
Debug.Assert(mosaic.Interpretation == "b-w");
```

Alternatively, see https://github.com/kleisauke/net-vips/issues/82#issuecomment-643608908 for a faster way of doing this using [`Image.Arrayjoin`](https://libvips.github.io/libvips/API/current/libvips-conversion.html#vips-arrayjoin).

**Comment by kleisauke** [comment]
Hope this helped, please feel free to re-open if questions remain.
