### ISSUE TITLE
Join multiple image to create multi-page tiff

### ISSUE THREAD

**Issue by nishars** [kleisauke/net-vips#93]
Hi,
I have a multi-page tiff consisting of around 800 pages.
I need to iterate through all the pages, identify if they are colored and set the resolution to 100x100 for colored pages alone.
And then save the entire image.

I am not able to merge the images to save them to multi-page tiff again after changing the resolution.

I tried below code, but it appends 2 images in the same page. Doesnt create second page.
Please let me know if there is any way to append pages instead of in the same page.

 NetVips.Image tempImage = NetVips.Image.Tiffload(sourceTiffFilePath);
 NetVips.Image newImgParent = tempImage.Join(newImg, "vertical", expand:true);
 newImgParent.Tiffsave(tiffFilePath);

This creates a TIFF image with 1 page.

Thank you.

**Comment by kleisauke** [comment]
Unfortunately, libvips can only write multipage TIFFs where each page has the same dimensions.

If your images are like this, you can just do:
```csharp
// How many pages do we want to append?
const int nPagesAppend = 2;

// n: is the number of pages to load, -1 means all pages in tall, thin image
var image = Image.Tiffload("sample.tif", n: -1);

// Get the height of each page from the metadata
// If the `page-height` property is not set, it defaults to the image height
var pageHeight = image.PageHeight;

// Our page to append
var page = Image.Black(image.Width, pageHeight);

// Join new pages
for (int i = 0; i < nPagesAppend; i++)
{
    image = image.Join(page, "vertical", expand: true);
}
// Or replace the above loop with:
// image = Image.Arrayjoin(new [] { image, page, page }, across: 1);

// Create a new `page-height` property if it does not exist
if (!image.Contains("page-height"))
{
    // Attaching metadata, need to copy the image
    image = image.Copy();
    image.Set(GValue.GIntType, "page-height", pageHeight);
}

image.Tiffsave("out.tif");
```

**Comment by kleisauke** [comment]
Hope this helped, please feel free to re-open if questions remain.
