### ISSUE TITLE
Converting color to transparent

### ISSUE THREAD

**Issue by blasky** [kleisauke/net-vips#95]
Another easy question, I'm sure. I'm sorry I keep taking up your time with easy/annoying ones. But I've looked through many netvips and libvips posts just trying to figure out how to take an existing image and set a particular color to act as the new transparency color. Like "all black pixels will now be transparent".

I know I can define a particular color to look for like a "var black = new int[] { 0, 0, 0, 0 }". And I believe I can search throughout the image with "img.Equal(black)". And I've been playing with ifthenelse() and various operators like "*=". But I've had no real luck so far. Thanks.

**Comment by kleisauke** [comment]
Have you seen https://github.com/libvips/libvips/issues/1165#issuecomment-439376528? It can be achieved in C# like this:

```csharp
var im = Image.NewFromFile("black.png");

var mask = im.Equal(new[] {0, 0, 0, 255}).BandAnd();
im = mask.Ifthenelse(new[] {0, 0, 0, 0}, im);

im.WriteToFile("x.png");
```

Example image: [black.png](https://user-images.githubusercontent.com/12746591/92113260-54915a00-edef-11ea-8a66-b5db2964be74.png)
Result: [x.png](https://user-images.githubusercontent.com/12746591/92113317-6c68de00-edef-11ea-9ac9-496f19fa8ee0.png)

**Comment by blasky** [comment]
Looks very similar to a couple of rounds of attempts I tried. Never had BandAnd() in the mix, though. Will try it now. Thanks.

**Comment by blasky** [comment]
The code above produces a black pixel to transparent PNG as promised. No question. But I was attempting to write out a transparent TIFF in the end. This might have been my problem. Does Netvips support TIFF transparency?

**Comment by kleisauke** [comment]
NetVips / libvips supports writing TIFF images with transparency. Make sure that you do _not_ set the compression to JPEG, as that format doesn't support transparency.

> Another easy question, I'm sure. I'm sorry I keep taking up your time with easy/annoying ones.

No problem! If you want to experiment with libvips I can recommend the online playground. It has a similar API as the .NET binding:
http://kleisauke.github.io/wasm-vips/playground/
