### ISSUE TITLE
Image Resizing

### ISSUE THREAD

**Issue by ozkanonur** [kleisauke/net-vips#97]
According to docs, there is a Resize function that changes image dimensions based on scale ratio. But what if I want to change dimensions by giving width and height values, which function should I use?

**Comment by ozkanonur** [comment]
I try https://github.com/kleisauke/net-vips/blob/b1585c9d341611cd884925a42da5bc5f47557a4f/samples/NetVips.Samples/Samples/Thumbnail.cs#L12 that one but the output's height is not correct.

**Comment by kleisauke** [comment]
Did you see https://github.com/kleisauke/net-vips/issues/71#issuecomment-609756394?

**Comment by lofcz** [comment]
This: `ThumbnailImage(w, h, size: "force");`

**Comment by ozkanonur** [comment]
> This: `ThumbnailImage(w, h, size: "force");`

Thanks!

**Comment by kleisauke** [comment]
I'd avoid `ThumbnailImage`, if possible. It can't do any of the shrink-on-load tricks, so it's much, much slower. The "force" parameter (`VIPS_SIZE_FORCE`) breaks aspect ratio, so I can't recommend that either.

**Comment by Darkle** [comment]
> I'd avoid `ThumbnailImage`, if possible. It can't do any of the shrink-on-load tricks, so it's much, much slower. The "force" parameter (`VIPS_SIZE_FORCE`) breaks aspect ratio, so I can't recommend that either.

What would be the thing to use in its place?

**Comment by kleisauke** [comment]
> What would be the thing to use in its place?

You can use the various `Image.Thumbnail*` functions for this. For example:
```diff
-using var image = Image.NewFromFile(Filename, access: Enums.Access.Sequential);
-
 // `vips_thumbnail` resize behavior is based on a square bounding box.
 // To resize along a specific axis, pass a huge value to the opposite axis.
 // See: https://github.com/libvips/libvips/pull/1639
-using var thumb = image.ThumbnailImage(300, height: 10000000);
+using var thumb = Image.Thumbnail(Filename, 300, height: 10000000);
 thumb.WriteToFile("thumbnail.jpg");
```

```diff
-using var image = Image.NewFromBuffer(Buffer, access: Enums.Access.Sequential);
-using var thumb = image.ThumbnailImage(300, height: 10000000);
+using var thumb = Image.ThumbnailBuffer(Buffer, 300, height: 10000000);
 thumb.WriteToFile("thumbnail.jpg");
```

```diff
-using var image = Image.NewFromStream(Stream, access: Enums.Access.Sequential);
-using var thumb = image.ThumbnailImage(300, height: 10000000);
+using var thumb = Image.ThumbnailStream(Stream, 300, height: 10000000);
 thumb.WriteToFile("thumbnail.jpg");
```
